In [2]:
import random as rd

insert = "insert into table "

In [3]:
Ho = [ 'Ho','Bui', 'Đoan', 'Le', 'Nguyen', 'Duong', 'Tran', 'Ly', 'Vu', 'Vo', 'Đang', 'Pham', 'Ung', 'An', 'Au','Truong', 'Lai', 'Gian' ]
tendem = ['Van','Thi','Chi','Gia','Hoang', 'Song', 'Tung' ]
ten = ['Ngoc Nhi','An','Anh','Bac','Bao','Cau','Cuc','Đan','Đang','Đuc','Thong','Tien','Tuan','Tin','Tiep','Viet','Vinh','Vu','Vy','Minh','Giang','khanh','Sang','Duy','Chi','Thuong','Chung','Phu','Quoc','Nam','Ngan','Nguyet','May' 
       ,'Tu','Thien','Tan','Han']

In [1]:
'''
NhanVien (
	MaNV 		varchar(10) primary key,
	TenNV 	varchar2(60) not null,
	Phai 		varchar2(4),
	NgaySinh 	date,
	DiaChi 	varchar2(100),
	SoDT 		varchar(10) not null unique,
	Luong 	number,
	PhuCap 	number,
	VaiTro 	varchar2(50),
	MaNQL 	varchar(10),
	PHG 		number
	
)
go
'''
'''
Nhân viên - 300
Quản lí - 20
Trưởng phòng - 8
Tài chính - 5
Nhân sự - 5
Trưởng đề án - 3
Ban giám đốc - 5
'''
sex = ['Nam', 'Nu']
import string

username = ''
MaNV = ''
TenNV = ''
Phai = ''
NgaySinh = ''
DiaChi 	= ''
SoDT 	= ''
Luong 	= 0
PhuCap 	= 0
VaiTro 	= ''
MaNQL 	= 'NULL'
PHG 	= 0
for i in range(1, 347):
    Luong = rd.randint(1000, 9999)
    PhuCap = rd.randint(1000, 2000)
    PHG = i % 8 + 1
    if i < 6:
        MaNV = '\'GD00'+ str(i) + '\''
        VaiTro 	= '\'Giam doc\''
        Luong = 55555
    elif i < 11:
        MaNV = '\'TC0'+ str(i) + '\''
        VaiTro 	= '\'Tai chinh\''
        Luong = 11000
    elif i < 16:
        MaNV = '\'NS0'+ str(i) + '\''
        VaiTro 	= '\'Nhan su\''
        Luong = 13000
    elif i < 36:
        MaNV = '\'QL0'+ str(i) + '\''
        VaiTro 	= '\'Quan li\''
        Luong = 25000
    elif i < 39:
        MaNV = '\'TDA0'+ str(i) + '\''
        VaiTro 	= '\'Truong de an\''
        Luong = 20000
    elif i < 47:
        MaNV = '\'TP0'+ str(i) + '\''
        VaiTro 	= '\'Truong phong\''
        Luong = 22000
        PHG = i - 38
    else:
        MaNV = '\'NV'+ str(i) + '\''
        VaiTro 	= '\'Nhan vien\''
        MaNQL = '\'QL0' + str((i - 47) % 20 + 16) + '\''
     
    
    account_suffix = MaNV.replace("'", "")
    username = f'\'123\''

    SoDT = '\'0945000' + str(i) + '\''
    TenNV = '\'' + rd.choice(Ho) + ' ' + rd.choice(tendem) + ' ' + rd.choice(ten) + '\''
    DiaChi = '\'227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh\'' 
    Phai = '\'' + rd.choice(sex) + '\''
    NgaySinh  = 'TO_DATE(' + '\'' + str(rd.randint(2000, 2022)) + '-' + str(rd.randint(1, 12)) + '-' + str(rd.randint(1, 28)) + '\',\'YYYY-MM-DD\')'
    
    final = MaNV + ', ' + TenNV + ', ' + Phai + ', ' + NgaySinh + ', ' + DiaChi +', ' + SoDT + ', ' + str(Luong) + ', ' + str(PhuCap) +', '+ VaiTro + ', ' + MaNQL + ', ' + str(PHG) + ', ' + username
    
    print (' into GOD.NHANVIEN values(' +  final + ')')
    
   # print('insert into TaiKhoan values(' + TenTaiKhoan + HoTen + str(Mk) + sdt + DiaChi + Email + LoaiTaiKhoan +')')

NameError: name 'rd' is not defined

In [7]:
KV = ['Quan 1', 'Quan 2', 'Quan 3','Quan 4','Quan 5','Quan 6','Quan 7','Quan 8','Quan 9','Quan 10','Quan 11','Quan 12','Quan 13', 'Quan Bình Thạnh', 'Quan Tân Bình', 'Hóoc Môn']

## Phong Ban

In [2]:
'''
PhongBan (
	MaPB 	number primary key,
	TenPB 	varchar2(60) not null,
	TrPHG 	varchar(10)
	
)	
'''


for i in range(1, 9):
    final = str(i) + ', ' + '\'Phong ' + str(i) + '\', NULL' 
    print('into GOD.PHONGBAN values(' +  final + ')')

into GOD.PHONGBAN values(1, 'Phong 1', NULL)
into GOD.PHONGBAN values(2, 'Phong 2', NULL)
into GOD.PHONGBAN values(3, 'Phong 3', NULL)
into GOD.PHONGBAN values(4, 'Phong 4', NULL)
into GOD.PHONGBAN values(5, 'Phong 5', NULL)
into GOD.PHONGBAN values(6, 'Phong 6', NULL)
into GOD.PHONGBAN values(7, 'Phong 7', NULL)
into GOD.PHONGBAN values(8, 'Phong 8', NULL)

In [7]:
for i in range(1, 9):
    print( ' UPDATE GOD.PHONGBAN set TrPHG = ' + '\'TP0'+ str(i+ 38) + '\'' + ' WHERE ' +  'MaPB = ' + str(i)+ ';')

 UPDATE GOD.PHONGBAN set TrPHG = 'TP039' WHERE MaPB = 1;
 UPDATE GOD.PHONGBAN set TrPHG = 'TP040' WHERE MaPB = 2;
 UPDATE GOD.PHONGBAN set TrPHG = 'TP041' WHERE MaPB = 3;
 UPDATE GOD.PHONGBAN set TrPHG = 'TP042' WHERE MaPB = 4;
 UPDATE GOD.PHONGBAN set TrPHG = 'TP043' WHERE MaPB = 5;
 UPDATE GOD.PHONGBAN set TrPHG = 'TP044' WHERE MaPB = 6;
 UPDATE GOD.PHONGBAN set TrPHG = 'TP045' WHERE MaPB = 7;
 UPDATE GOD.PHONGBAN set TrPHG = 'TP046' WHERE MaPB = 8;

# DE AN

In [10]:
'''
DeAn (
	MaDA 		varchar(10) primary key,
	TenDA 	varchar2(60) not null,
	NgayBD 	date,
	Phong 	number,
    TruongDeAn varchar(10)
	
)
'''
l = []
for i in range(1, 9):
    for j in range(1, rd.randint(3, 5)):
        MaDA = '\'DA' + str(i) + '0' + str(j) + '\'';
        l.append(MaDA);

        TenDA = '\'De An so ' + str(j) + ' Phong ' + str(i) + '\'';
        NgayBD  = 'TO_DATE(' + '\'' + str(rd.randint(2020, 2022)) + '-' + str(rd.randint(1, 12)) + '-' + str(rd.randint(1, 28)) + '\',\'YYYY-MM-DD\')'
        Phong = str(i)
        TruongDA = 'TDA0' + str(rd.randint(36, 38))
        final = MaDA + ', ' + TenDA + ', ' + NgayBD + ', ' + Phong + ', ' + '\'' +  TruongDA + '\''
        print('into GOD.DEAN values(' +  final + ')')

into GOD.DEAN values('DA101', 'De An so 1 Phong 1', TO_DATE('2020-12-24','YYYY-MM-DD'), 1, 'TDA038')
into GOD.DEAN values('DA102', 'De An so 2 Phong 1', TO_DATE('2022-11-25','YYYY-MM-DD'), 1, 'TDA038')
into GOD.DEAN values('DA103', 'De An so 3 Phong 1', TO_DATE('2020-6-14','YYYY-MM-DD'), 1, 'TDA036')
into GOD.DEAN values('DA104', 'De An so 4 Phong 1', TO_DATE('2022-5-24','YYYY-MM-DD'), 1, 'TDA038')
into GOD.DEAN values('DA201', 'De An so 1 Phong 2', TO_DATE('2022-2-15','YYYY-MM-DD'), 2, 'TDA037')
into GOD.DEAN values('DA202', 'De An so 2 Phong 2', TO_DATE('2020-7-12','YYYY-MM-DD'), 2, 'TDA036')
into GOD.DEAN values('DA301', 'De An so 1 Phong 3', TO_DATE('2021-12-16','YYYY-MM-DD'), 3, 'TDA038')
into GOD.DEAN values('DA302', 'De An so 2 Phong 3', TO_DATE('2022-4-27','YYYY-MM-DD'), 3, 'TDA036')
into GOD.DEAN values('DA401', 'De An so 1 Phong 4', TO_DATE('2022-5-28','YYYY-MM-DD'), 4, 'TDA037')
into GOD.DEAN values('DA402', 'De An so 2 Phong 4', TO_DATE('2020-2-15','YYYY-MM-DD'), 4, 'TDA038')
into GOD.DEAN values('DA403', 'De An so 3 Phong 4', TO_DATE('2020-10-26','YYYY-MM-DD'), 4, 'TDA038')
into GOD.DEAN values('DA404', 'De An so 4 Phong 4', TO_DATE('2020-9-23','YYYY-MM-DD'), 4, 'TDA038')
into GOD.DEAN values('DA501', 'De An so 1 Phong 5', TO_DATE('2022-12-14','YYYY-MM-DD'), 5, 'TDA037')
into GOD.DEAN values('DA502', 'De An so 2 Phong 5', TO_DATE('2021-7-11','YYYY-MM-DD'), 5, 'TDA037')
into GOD.DEAN values('DA601', 'De An so 1 Phong 6', TO_DATE('2021-6-23','YYYY-MM-DD'), 6, 'TDA037')
into GOD.DEAN values('DA602', 'De An so 2 Phong 6', TO_DATE('2021-12-7','YYYY-MM-DD'), 6, 'TDA038')
into GOD.DEAN values('DA603', 'De An so 3 Phong 6', TO_DATE('2021-3-10','YYYY-MM-DD'), 6, 'TDA037')
into GOD.DEAN values('DA604', 'De An so 4 Phong 6', TO_DATE('2022-6-22','YYYY-MM-DD'), 6, 'TDA036')
into GOD.DEAN values('DA701', 'De An so 1 Phong 7', TO_DATE('2022-5-22','YYYY-MM-DD'), 7, 'TDA038')
into GOD.DEAN values('DA702', 'De An so 2 Phong 7', TO_DATE('2022-3-12','YYYY-MM-DD'), 7, 'TDA036')
into GOD.DEAN values('DA801', 'De An so 1 Phong 8', TO_DATE('2020-4-25','YYYY-MM-DD'), 8, 'TDA038')
into GOD.DEAN values('DA802', 'De An so 2 Phong 8', TO_DATE('2020-8-23','YYYY-MM-DD'), 8, 'TDA036')
into GOD.DEAN values('DA803', 'De An so 3 Phong 8', TO_DATE('2021-10-17','YYYY-MM-DD'), 8, 'TDA038')

## Phan Cong

In [11]:
'''
	PhanCong (
	MaNV 		varchar(10) primary key,
	MaDA 		varchar(10) primary key,
	ThoiGian 	date
	
)

'''
import numpy as np
for i in range(47, 347, 3):
    MaNV = '\'NV'+ str(i) + '\''
    for j in range(1, rd.randint(2, 3)):
        MaDA = '\'DA' + str(i%8 + 1) + '0' + str(j) + '\'';
        TG  = 'TO_DATE(' + '\'' + str(rd.randint(2020, 2022)) + '-' + str(rd.randint(1, 12)) + '-' + str(rd.randint(1, 28)) + '\',\'YYYY-MM-DD\')'
        final = MaNV + ', ' + MaDA + ', ' + TG  
        print('into PHANCONG values(' +  final + ')')

into PHANCONG values('NV47', 'DA801', TO_DATE('2022-12-6','YYYY-MM-DD'))
into PHANCONG values('NV50', 'DA301', TO_DATE('2020-7-8','YYYY-MM-DD'))
into PHANCONG values('NV50', 'DA302', TO_DATE('2021-5-10','YYYY-MM-DD'))
into PHANCONG values('NV53', 'DA601', TO_DATE('2022-7-2','YYYY-MM-DD'))
into PHANCONG values('NV56', 'DA101', TO_DATE('2021-1-23','YYYY-MM-DD'))
into PHANCONG values('NV59', 'DA401', TO_DATE('2022-9-8','YYYY-MM-DD'))
into PHANCONG values('NV59', 'DA402', TO_DATE('2020-8-4','YYYY-MM-DD'))
into PHANCONG values('NV62', 'DA701', TO_DATE('2020-2-21','YYYY-MM-DD'))
into PHANCONG values('NV62', 'DA702', TO_DATE('2021-4-26','YYYY-MM-DD'))
into PHANCONG values('NV65', 'DA201', TO_DATE('2021-4-5','YYYY-MM-DD'))
into PHANCONG values('NV65', 'DA202', TO_DATE('2021-6-3','YYYY-MM-DD'))
into PHANCONG values('NV68', 'DA501', TO_DATE('2021-12-22','YYYY-MM-DD'))
into PHANCONG values('NV68', 'DA502', TO_DATE('2022-12-26','YYYY-MM-DD'))
into PHANCONG values('NV71', 'DA801', TO_DATE('2022-2-14','YYYY-MM-DD'))
into PHANCONG values('NV74', 'DA301', TO_DATE('2021-6-21','YYYY-MM-DD'))
into PHANCONG values('NV74', 'DA302', TO_DATE('2021-3-6','YYYY-MM-DD'))
into PHANCONG values('NV77', 'DA601', TO_DATE('2020-6-25','YYYY-MM-DD'))
into PHANCONG values('NV77', 'DA602', TO_DATE('2021-12-19','YYYY-MM-DD'))
into PHANCONG values('NV80', 'DA101', TO_DATE('2021-8-9','YYYY-MM-DD'))
into PHANCONG values('NV83', 'DA401', TO_DATE('2021-9-22','YYYY-MM-DD'))
into PHANCONG values('NV83', 'DA402', TO_DATE('2022-9-22','YYYY-MM-DD'))
into PHANCONG values('NV86', 'DA701', TO_DATE('2022-10-16','YYYY-MM-DD'))
into PHANCONG values('NV86', 'DA702', TO_DATE('2020-11-17','YYYY-MM-DD'))
into PHANCONG values('NV89', 'DA201', TO_DATE('2022-7-9','YYYY-MM-DD'))
into PHANCONG values('NV92', 'DA501', TO_DATE('2021-9-11','YYYY-MM-DD'))
into PHANCONG values('NV95', 'DA801', TO_DATE('2020-3-16','YYYY-MM-DD'))
into PHANCONG values('NV95', 'DA802', TO_DATE('2021-7-12','YYYY-MM-DD'))
into PHANCONG values('NV98', 'DA301', TO_DATE('2022-3-7','YYYY-MM-DD'))
into PHANCONG values('NV98', 'DA302', TO_DATE('2021-7-8','YYYY-MM-DD'))
into PHANCONG values('NV101', 'DA601', TO_DATE('2021-9-1','YYYY-MM-DD'))
into PHANCONG values('NV101', 'DA602', TO_DATE('2020-10-10','YYYY-MM-DD'))
into PHANCONG values('NV104', 'DA101', TO_DATE('2020-1-26','YYYY-MM-DD'))
into PHANCONG values('NV104', 'DA102', TO_DATE('2020-6-13','YYYY-MM-DD'))
into PHANCONG values('NV107', 'DA401', TO_DATE('2020-2-14','YYYY-MM-DD'))
into PHANCONG values('NV107', 'DA402', TO_DATE('2020-7-8','YYYY-MM-DD'))
into PHANCONG values('NV110', 'DA701', TO_DATE('2022-10-17','YYYY-MM-DD'))
into PHANCONG values('NV113', 'DA201', TO_DATE('2022-3-9','YYYY-MM-DD'))
into PHANCONG values('NV113', 'DA202', TO_DATE('2022-1-20','YYYY-MM-DD'))
into PHANCONG values('NV116', 'DA501', TO_DATE('2022-2-17','YYYY-MM-DD'))
into PHANCONG values('NV119', 'DA801', TO_DATE('2022-4-14','YYYY-MM-DD'))
into PHANCONG values('NV122', 'DA301', TO_DATE('2020-12-20','YYYY-MM-DD'))
into PHANCONG values('NV125', 'DA601', TO_DATE('2020-4-3','YYYY-MM-DD'))
into PHANCONG values('NV128', 'DA101', TO_DATE('2021-3-27','YYYY-MM-DD'))
into PHANCONG values('NV128', 'DA102', TO_DATE('2022-2-14','YYYY-MM-DD'))
into PHANCONG values('NV131', 'DA401', TO_DATE('2021-5-11','YYYY-MM-DD'))
into PHANCONG values('NV131', 'DA402', TO_DATE('2020-6-18','YYYY-MM-DD'))
into PHANCONG values('NV134', 'DA701', TO_DATE('2021-8-27','YYYY-MM-DD'))
into PHANCONG values('NV134', 'DA702', TO_DATE('2022-11-26','YYYY-MM-DD'))
into PHANCONG values('NV137', 'DA201', TO_DATE('2020-2-14','YYYY-MM-DD'))
into PHANCONG values('NV137', 'DA202', TO_DATE('2021-12-1','YYYY-MM-DD'))
into PHANCONG values('NV140', 'DA501', TO_DATE('2021-5-15','YYYY-MM-DD'))
into PHANCONG values('NV143', 'DA801', TO_DATE('2021-8-28','YYYY-MM-DD'))
into PHANCONG values('NV143', 'DA802', TO_DATE('2020-11-6','YYYY-MM-DD'))
into PHANCONG values('NV146', 'DA301', TO_DATE('2020-7-26','YYYY-MM-DD'))
into PHANCONG values('NV149', 'DA601', TO_DATE('2021-9-2','YYYY-MM-DD'))
into PHANCONG values('NV152', 'DA101', TO_DATE('2022-1-15','YYYY-MM-DD'))
into PHANCONG values('NV152', 'DA102', TO_DATE('2020-11-18','YYYY-MM-DD'))
into PHANCONG values('NV155', 'DA401', TO_DATE('2021-6-3','YYYY-MM-DD'))
into PHANCONG values('NV158', 'DA701', TO_DATE('2020-1-4','YYYY-MM-DD'))
into PHANCONG values('NV158', 'DA702', TO_DATE('2021-3-21','YYYY-MM-DD'))
into PHANCONG values('NV161', 'DA201', TO_DATE('2020-2-24','YYYY-MM-DD'))
into PHANCONG values('NV161', 'DA202', TO_DATE('2020-5-9','YYYY-MM-DD'))
into PHANCONG values('NV164', 'DA501', TO_DATE('2021-1-12','YYYY-MM-DD'))
into PHANCONG values('NV167', 'DA801', TO_DATE('2022-1-10','YYYY-MM-DD'))
into PHANCONG values('NV170', 'DA301', TO_DATE('2020-2-27','YYYY-MM-DD'))
into PHANCONG values('NV173', 'DA601', TO_DATE('2020-6-14','YYYY-MM-DD'))
into PHANCONG values('NV173', 'DA602', TO_DATE('2020-5-2','YYYY-MM-DD'))
into PHANCONG values('NV176', 'DA101', TO_DATE('2022-6-10','YYYY-MM-DD'))
into PHANCONG values('NV179', 'DA401', TO_DATE('2021-11-25','YYYY-MM-DD'))
into PHANCONG values('NV179', 'DA402', TO_DATE('2022-2-22','YYYY-MM-DD'))
into PHANCONG values('NV182', 'DA701', TO_DATE('2020-6-24','YYYY-MM-DD'))
into PHANCONG values('NV182', 'DA702', TO_DATE('2021-11-25','YYYY-MM-DD'))
into PHANCONG values('NV185', 'DA201', TO_DATE('2022-11-3','YYYY-MM-DD'))
into PHANCONG values('NV188', 'DA501', TO_DATE('2020-5-18','YYYY-MM-DD'))
into PHANCONG values('NV188', 'DA502', TO_DATE('2022-10-4','YYYY-MM-DD'))
into PHANCONG values('NV191', 'DA801', TO_DATE('2020-11-9','YYYY-MM-DD'))
into PHANCONG values('NV194', 'DA301', TO_DATE('2022-6-25','YYYY-MM-DD'))
into PHANCONG values('NV194', 'DA302', TO_DATE('2020-5-5','YYYY-MM-DD'))
into PHANCONG values('NV197', 'DA601', TO_DATE('2021-2-2','YYYY-MM-DD'))
into PHANCONG values('NV200', 'DA101', TO_DATE('2021-4-24','YYYY-MM-DD'))
into PHANCONG values('NV203', 'DA401', TO_DATE('2021-6-20','YYYY-MM-DD'))
into PHANCONG values('NV206', 'DA701', TO_DATE('2022-6-2','YYYY-MM-DD'))
into PHANCONG values('NV209', 'DA201', TO_DATE('2020-6-18','YYYY-MM-DD'))
into PHANCONG values('NV212', 'DA501', TO_DATE('2022-1-12','YYYY-MM-DD'))
into PHANCONG values('NV212', 'DA502', TO_DATE('2021-2-4','YYYY-MM-DD'))
into PHANCONG values('NV215', 'DA801', TO_DATE('2021-6-15','YYYY-MM-DD'))
into PHANCONG values('NV218', 'DA301', TO_DATE('2020-10-11','YYYY-MM-DD'))
into PHANCONG values('NV221', 'DA601', TO_DATE('2020-11-14','YYYY-MM-DD'))
into PHANCONG values('NV221', 'DA602', TO_DATE('2020-1-4','YYYY-MM-DD'))
into PHANCONG values('NV224', 'DA101', TO_DATE('2020-2-6','YYYY-MM-DD'))
into PHANCONG values('NV224', 'DA102', TO_DATE('2022-6-26','YYYY-MM-DD'))
into PHANCONG values('NV227', 'DA401', TO_DATE('2021-12-7','YYYY-MM-DD'))
into PHANCONG values('NV230', 'DA701', TO_DATE('2020-8-27','YYYY-MM-DD'))
into PHANCONG values('NV230', 'DA702', TO_DATE('2022-11-4','YYYY-MM-DD'))
into PHANCONG values('NV233', 'DA201', TO_DATE('2022-5-13','YYYY-MM-DD'))
into PHANCONG values('NV236', 'DA501', TO_DATE('2022-11-25','YYYY-MM-DD'))
into PHANCONG values('NV239', 'DA801', TO_DATE('2020-2-5','YYYY-MM-DD'))
into PHANCONG values('NV239', 'DA802', TO_DATE('2021-1-13','YYYY-MM-DD'))
into PHANCONG values('NV242', 'DA301', TO_DATE('2020-9-7','YYYY-MM-DD'))
into PHANCONG values('NV242', 'DA302', TO_DATE('2020-1-19','YYYY-MM-DD'))
into PHANCONG values('NV245', 'DA601', TO_DATE('2022-4-8','YYYY-MM-DD'))
into PHANCONG values('NV245', 'DA602', TO_DATE('2022-10-9','YYYY-MM-DD'))
into PHANCONG values('NV248', 'DA101', TO_DATE('2020-3-9','YYYY-MM-DD'))
into PHANCONG values('NV251', 'DA401', TO_DATE('2021-5-1','YYYY-MM-DD'))
into PHANCONG values('NV251', 'DA402', TO_DATE('2021-6-27','YYYY-MM-DD'))
into PHANCONG values('NV254', 'DA701', TO_DATE('2022-7-12','YYYY-MM-DD'))
into PHANCONG values('NV254', 'DA702', TO_DATE('2022-7-7','YYYY-MM-DD'))
into PHANCONG values('NV257', 'DA201', TO_DATE('2022-4-18','YYYY-MM-DD'))
into PHANCONG values('NV260', 'DA501', TO_DATE('2021-5-13','YYYY-MM-DD'))
into PHANCONG values('NV260', 'DA502', TO_DATE('2022-9-14','YYYY-MM-DD'))
into PHANCONG values('NV263', 'DA801', TO_DATE('2020-4-17','YYYY-MM-DD'))
into PHANCONG values('NV266', 'DA301', TO_DATE('2022-5-22','YYYY-MM-DD'))
into PHANCONG values('NV269', 'DA601', TO_DATE('2020-1-17','YYYY-MM-DD'))
into PHANCONG values('NV272', 'DA101', TO_DATE('2020-5-3','YYYY-MM-DD'))
into PHANCONG values('NV272', 'DA102', TO_DATE('2021-5-12','YYYY-MM-DD'))
into PHANCONG values('NV275', 'DA401', TO_DATE('2021-1-21','YYYY-MM-DD'))
into PHANCONG values('NV278', 'DA701', TO_DATE('2020-1-16','YYYY-MM-DD'))
into PHANCONG values('NV281', 'DA201', TO_DATE('2020-4-24','YYYY-MM-DD'))
into PHANCONG values('NV284', 'DA501', TO_DATE('2021-4-15','YYYY-MM-DD'))
into PHANCONG values('NV284', 'DA502', TO_DATE('2021-3-14','YYYY-MM-DD'))
into PHANCONG values('NV287', 'DA801', TO_DATE('2020-7-2','YYYY-MM-DD'))
into PHANCONG values('NV287', 'DA802', TO_DATE('2021-8-21','YYYY-MM-DD'))
into PHANCONG values('NV290', 'DA301', TO_DATE('2021-8-15','YYYY-MM-DD'))
into PHANCONG values('NV293', 'DA601', TO_DATE('2022-8-19','YYYY-MM-DD'))
into PHANCONG values('NV293', 'DA602', TO_DATE('2022-4-11','YYYY-MM-DD'))
into PHANCONG values('NV296', 'DA101', TO_DATE('2020-12-25','YYYY-MM-DD'))
into PHANCONG values('NV299', 'DA401', TO_DATE('2020-6-24','YYYY-MM-DD'))
into PHANCONG values('NV299', 'DA402', TO_DATE('2020-10-4','YYYY-MM-DD'))
into PHANCONG values('NV302', 'DA701', TO_DATE('2020-2-16','YYYY-MM-DD'))
into PHANCONG values('NV305', 'DA201', TO_DATE('2021-4-6','YYYY-MM-DD'))
into PHANCONG values('NV308', 'DA501', TO_DATE('2022-4-23','YYYY-MM-DD'))
into PHANCONG values('NV308', 'DA502', TO_DATE('2021-3-27','YYYY-MM-DD'))
into PHANCONG values('NV311', 'DA801', TO_DATE('2020-2-5','YYYY-MM-DD'))
into PHANCONG values('NV314', 'DA301', TO_DATE('2020-8-13','YYYY-MM-DD'))
into PHANCONG values('NV317', 'DA601', TO_DATE('2022-9-28','YYYY-MM-DD'))
into PHANCONG values('NV320', 'DA101', TO_DATE('2022-6-11','YYYY-MM-DD'))
into PHANCONG values('NV320', 'DA102', TO_DATE('2021-9-20','YYYY-MM-DD'))
into PHANCONG values('NV323', 'DA401', TO_DATE('2022-10-3','YYYY-MM-DD'))
into PHANCONG values('NV326', 'DA701', TO_DATE('2022-6-25','YYYY-MM-DD'))
into PHANCONG values('NV329', 'DA201', TO_DATE('2020-8-26','YYYY-MM-DD'))
into PHANCONG values('NV332', 'DA501', TO_DATE('2021-7-13','YYYY-MM-DD'))
into PHANCONG values('NV332', 'DA502', TO_DATE('2022-10-15','YYYY-MM-DD'))
into PHANCONG values('NV335', 'DA801', TO_DATE('2021-8-28','YYYY-MM-DD'))
into PHANCONG values('NV335', 'DA802', TO_DATE('2021-11-8','YYYY-MM-DD'))
into PHANCONG values('NV338', 'DA301', TO_DATE('2022-3-10','YYYY-MM-DD'))
into PHANCONG values('NV341', 'DA601', TO_DATE('2021-10-2','YYYY-MM-DD'))
into PHANCONG values('NV341', 'DA602', TO_DATE('2020-12-13','YYYY-MM-DD'))
into PHANCONG values('NV344', 'DA101', TO_DATE('2021-3-25','YYYY-MM-DD'))

# Thong bao

In [1]:
KV = ['Mien Bac', 'Mien Trung', 'Mien Nam']
LV = ['San xuat', 'Gia Cong', 'Mua ban']
VT = ['Giam doc', 'Truong phong', 'Nhan vien']

for i in VT:
    for j in LV:
        for k in KV:
            nd = '\'Thong bao toi ' + i + ' thuoc linh vuc ' + j + ' cua khu vuc ' + k + '\''
            print ('insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES(' + nd + ', \'' + i + '\',\'' + j + '\',\''  + k + '\');')

insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Giam doc thuoc linh vuc San xuat cua khu vuc Mien Bac', 'Giam doc','San xuat','Mien Bac');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Giam doc thuoc linh vuc San xuat cua khu vuc Mien Trung', 'Giam doc','San xuat','Mien Trung');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Giam doc thuoc linh vuc San xuat cua khu vuc Mien Nam', 'Giam doc','San xuat','Mien Nam');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Giam doc thuoc linh vuc Gia Cong cua khu vuc Mien Bac', 'Giam doc','Gia Cong','Mien Bac');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Giam doc thuoc linh vuc Gia Cong cua khu vuc Mien Trung', 'Giam doc','Gia Cong','Mien Trung');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Giam doc thuoc linh vuc Gia Cong cua khu vuc Mien Nam', 'Giam doc','Gia Cong','Mien Nam');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Giam doc thuoc linh vuc Mua ban cua khu vuc Mien Bac', 'Giam doc','Mua ban','Mien Bac');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Giam doc thuoc linh vuc Mua ban cua khu vuc Mien Trung', 'Giam doc','Mua ban','Mien Trung');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Giam doc thuoc linh vuc Mua ban cua khu vuc Mien Nam', 'Giam doc','Mua ban','Mien Nam');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Truong phong thuoc linh vuc San xuat cua khu vuc Mien Bac', 'Truong phong','San xuat','Mien Bac');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Truong phong thuoc linh vuc San xuat cua khu vuc Mien Trung', 'Truong phong','San xuat','Mien Trung');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Truong phong thuoc linh vuc San xuat cua khu vuc Mien Nam', 'Truong phong','San xuat','Mien Nam');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Truong phong thuoc linh vuc Gia Cong cua khu vuc Mien Bac', 'Truong phong','Gia Cong','Mien Bac');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Truong phong thuoc linh vuc Gia Cong cua khu vuc Mien Trung', 'Truong phong','Gia Cong','Mien Trung');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Truong phong thuoc linh vuc Gia Cong cua khu vuc Mien Nam', 'Truong phong','Gia Cong','Mien Nam');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Truong phong thuoc linh vuc Mua ban cua khu vuc Mien Bac', 'Truong phong','Mua ban','Mien Bac');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Truong phong thuoc linh vuc Mua ban cua khu vuc Mien Trung', 'Truong phong','Mua ban','Mien Trung');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Truong phong thuoc linh vuc Mua ban cua khu vuc Mien Nam', 'Truong phong','Mua ban','Mien Nam');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Nhan vien thuoc linh vuc San xuat cua khu vuc Mien Bac', 'Nhan vien','San xuat','Mien Bac');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Nhan vien thuoc linh vuc San xuat cua khu vuc Mien Trung', 'Nhan vien','San xuat','Mien Trung');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Nhan vien thuoc linh vuc San xuat cua khu vuc Mien Nam', 'Nhan vien','San xuat','Mien Nam');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Nhan vien thuoc linh vuc Gia Cong cua khu vuc Mien Bac', 'Nhan vien','Gia Cong','Mien Bac');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Nhan vien thuoc linh vuc Gia Cong cua khu vuc Mien Trung', 'Nhan vien','Gia Cong','Mien Trung');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Nhan vien thuoc linh vuc Gia Cong cua khu vuc Mien Nam', 'Nhan vien','Gia Cong','Mien Nam');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Nhan vien thuoc linh vuc Mua ban cua khu vuc Mien Bac', 'Nhan vien','Mua ban','Mien Bac');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Nhan vien thuoc linh vuc Mua ban cua khu vuc Mien Trung', 'Nhan vien','Mua ban','Mien Trung');
insert into THONGBAO(NOIDUNG, DOITUONG, LINHVUC, KHUVUC) VALUES('Thong bao toi Nhan vien thuoc linh vuc Mua ban cua khu vuc Mien Nam', 'Nhan vien','Mua ban','Mien Nam');