In [2]:
import random as rd

insert = "insert into table "

In [3]:
Ho = [ 'Hồ','Bùi', 'Đoàn', 'Lê', 'Nguyễn', 'Dương', 'Trần', 'Lý', 'Vũ', 'Võ', 'Đặng', 'Phạm', 'Ưng', 'An', 'Âu','Trương', 'Lại', 'Giản' ]
tendem = ['Văn','Thị','Chí','Gia','Hoàng', 'Song', 'Tùng' ]
ten = ['Ngọc Nhi','An','Anh','Bắc','Bảo','Cầu','Cúc','Đan','Đăng','Đức','Thông','Tiến','Tuấn','Tín','Tiệp','Việt','Vinh','Vũ','Vy','Minh','Giang','khanh','Sáng','Duy','Chi','Thương','Chung','Phú','Quốc','Nam','Ngần','Nguyệt','Mây' 
       ,'Tú','Thiên','Tân','Hân']

In [47]:
'''
NhanVien (
	MaNV 		varchar(10) primary key,
	TenNV 	varchar2(60) not null,
	Phai 		varchar2(4),
	NgaySinh 	date,
	DiaChi 	varchar2(100),
	SoDT 		varchar(10) not null unique,
	Luong 	number,
	PhuCap 	number,
	VaiTro 	varchar2(50),
	MaNQL 	varchar(10),
	PHG 		number
	
)
go
'''
'''
Nhân viên - 300
Quản lí - 20
Trưởng phòng - 8
Tài chính - 5
Nhân sự - 5
Trưởng đề án - 3
Ban giám đốc - 5
'''
sex = ['Nam', 'Nữ']
import string


MaNV = ''
TenNV = ''
Phai = ''
NgaySinh = ''
DiaChi 	= ''
SoDT 	= ''
Luong 	= 0
PhuCap 	= 0
VaiTro 	= ''
MaNQL 	= 'NULL'
PHG 	= 0
for i in range(1, 347):
    Luong = rd.randint(1000, 9999)
    PhuCap = rd.randint(1000, 2000)
    PHG = i % 8 + 1
    if i < 6:
        MaNV = '\'GD00'+ str(i) + '\''
        VaiTro 	= '\'Ban giám đốc\''
        Luong = 55555
    elif i < 11:
        MaNV = '\'TC0'+ str(i) + '\''
        VaiTro 	= '\'Tài chính\''
        Luong = 11000
    elif i < 16:
        MaNV = '\'NS0'+ str(i) + '\''
        VaiTro 	= '\'Nhân sự\''
        Luong = 13000
    elif i < 36:
        MaNV = '\'QL0'+ str(i) + '\''
        VaiTro 	= '\'Quản lí\''
        Luong = 25000
    elif i < 39:
        MaNV = '\'TDA0'+ str(i) + '\''
        VaiTro 	= '\'Trưởng đề án\''
        Luong = 20000
    elif i < 47:
        MaNV = '\'TP0'+ str(i) + '\''
        VaiTro 	= '\'Trưởng phòng\''
        Luong = 22000
        PHG = i - 38
    else:
        MaNV = '\'NV'+ str(i) + '\''
        VaiTro 	= '\'Nhân viên\''
    

    SoDT = '\'0945000' + str(i) + '\''
    TenNV = '\'' + rd.choice(Ho) + ' ' + rd.choice(tendem) + ' ' + rd.choice(ten) + '\''
    DiaChi = '\'227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh\'' 
    Phai = '\'' + rd.choice(sex) + '\''
    NgaySinh  = 'TO_DATE(' + '\'' + str(rd.randint(2000, 2022)) + '-' + str(rd.randint(1, 12)) + '-' + str(rd.randint(1, 28)) + '\',\'YYYY-MM-DD\')'
    final = MaNV + ', ' + TenNV + ', ' + Phai + ', ' + NgaySinh + ', ' + DiaChi +', ' + SoDT + ', ' + str(Luong) + ', ' + str(PhuCap) +', '+ VaiTro + ', ' + MaNQL + ', ' + str(PHG)
    
    print (' into NHANVIEN values(' +  final + ')')
    
   # print('insert into TaiKhoan values(' + TenTaiKhoan + HoTen + str(Mk) + sdt + DiaChi + Email + LoaiTaiKhoan +')')

 into NHANVIEN values('GD001', 'Âu Song Thương', 'Nữ', TO_DATE('2022-1-6','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450001', 55555, 1942, 'Ban giám đốc', NULL, 2)
 into NHANVIEN values('GD002', 'Dương Gia Tú', 'Nữ', TO_DATE('2008-10-14','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450002', 55555, 1337, 'Ban giám đốc', NULL, 3)
 into NHANVIEN values('GD003', 'Đoàn Văn Vũ', 'Nam', TO_DATE('2006-11-10','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450003', 55555, 1895, 'Ban giám đốc', NULL, 4)
 into NHANVIEN values('GD004', 'Ưng Gia Nam', 'Nam', TO_DATE('2006-10-6','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450004', 55555, 1709, 'Ban giám đốc', NULL, 5)
 into NHANVIEN values('GD005', 'Hồ Song Ngọc Nhi', 'Nữ', TO_DATE('2012-7-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450005', 55555, 1481, 'Ban giám đốc', NULL, 6)
 into NHANVIEN values('TC06', 'Vũ Thị Tín', 'Nam', TO_DATE('2019-1-12','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450006', 11000, 1984, 'Tài chính', NULL, 7)
 into NHANVIEN values('TC07', 'Hồ Hoàng Đăng', 'Nam', TO_DATE('2019-4-24','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450007', 11000, 1776, 'Tài chính', NULL, 8)
 into NHANVIEN values('TC08', 'Võ Tùng An', 'Nam', TO_DATE('2008-8-27','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450008', 11000, 1498, 'Tài chính', NULL, 1)
 into NHANVIEN values('TC09', 'Võ Song Cầu', 'Nữ', TO_DATE('2017-5-21','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450009', 11000, 1885, 'Tài chính', NULL, 2)
 into NHANVIEN values('TC010', 'Âu Hoàng Chung', 'Nữ', TO_DATE('2006-4-6','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500010', 11000, 1210, 'Tài chính', NULL, 3)
 into NHANVIEN values('NS011', 'Hồ Thị Đăng', 'Nữ', TO_DATE('2001-7-28','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500011', 13000, 1596, 'Nhân sự', NULL, 4)
 into NHANVIEN values('NS012', 'Trương Văn Tiệp', 'Nữ', TO_DATE('2014-6-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500012', 13000, 1922, 'Nhân sự', NULL, 5)
 into NHANVIEN values('NS013', 'Âu Tùng Anh', 'Nữ', TO_DATE('2015-5-13','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500013', 13000, 1818, 'Nhân sự', NULL, 6)
 into NHANVIEN values('NS014', 'Nguyễn Hoàng khanh', 'Nữ', TO_DATE('2004-1-16','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500014', 13000, 1620, 'Nhân sự', NULL, 7)
 into NHANVIEN values('NS015', 'An Thị Chung', 'Nam', TO_DATE('2001-1-17','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500015', 13000, 1465, 'Nhân sự', NULL, 8)
 into NHANVIEN values('QL016', 'Phạm Hoàng Đăng', 'Nam', TO_DATE('2005-11-4','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500016', 25000, 1509, 'Quản lí', NULL, 1)
 into NHANVIEN values('QL017', 'Nguyễn Song Cầu', 'Nữ', TO_DATE('2004-4-12','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500017', 25000, 1046, 'Quản lí', NULL, 2)
 into NHANVIEN values('QL018', 'Âu Chí Cúc', 'Nam', TO_DATE('2011-10-18','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500018', 25000, 1742, 'Quản lí', NULL, 3)
 into NHANVIEN values('QL019', 'Dương Chí Bảo', 'Nữ', TO_DATE('2020-8-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500019', 25000, 1832, 'Quản lí', NULL, 4)
 into NHANVIEN values('QL020', 'Bùi Chí Hân', 'Nữ', TO_DATE('2006-7-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500020', 25000, 1714, 'Quản lí', NULL, 5)
 into NHANVIEN values('QL021', 'Đoàn Gia Cúc', 'Nữ', TO_DATE('2008-12-4','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500021', 25000, 1942, 'Quản lí', NULL, 6)
 into NHANVIEN values('QL022', 'Nguyễn Gia Tú', 'Nam', TO_DATE('2010-4-9','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500022', 25000, 1560, 'Quản lí', NULL, 7)
 into NHANVIEN values('QL023', 'Lại Song Cầu', 'Nữ', TO_DATE('2019-2-20','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500023', 25000, 1825, 'Quản lí', NULL, 8)
 into NHANVIEN values('QL024', 'Ưng Chí Sáng', 'Nữ', TO_DATE('2007-2-28','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500024', 25000, 1823, 'Quản lí', NULL, 1)
 into NHANVIEN values('QL025', 'Đặng Song Giang', 'Nữ', TO_DATE('2003-6-4','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500025', 25000, 1763, 'Quản lí', NULL, 2)
 into NHANVIEN values('QL026', 'Bùi Tùng Nguyệt', 'Nam', TO_DATE('2021-1-16','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500026', 25000, 1192, 'Quản lí', NULL, 3)
 into NHANVIEN values('QL027', 'An Chí Nam', 'Nam', TO_DATE('2015-8-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500027', 25000, 1428, 'Quản lí', NULL, 4)
 into NHANVIEN values('QL028', 'Ưng Thị Chung', 'Nữ', TO_DATE('2007-3-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500028', 25000, 1834, 'Quản lí', NULL, 5)
 into NHANVIEN values('QL029', 'Phạm Hoàng Mây', 'Nam', TO_DATE('2022-5-25','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500029', 25000, 1352, 'Quản lí', NULL, 6)
 into NHANVIEN values('QL030', 'Lại Song Bảo', 'Nam', TO_DATE('2006-8-11','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500030', 25000, 1742, 'Quản lí', NULL, 7)
 into NHANVIEN values('QL031', 'Hồ Chí Cúc', 'Nữ', TO_DATE('2000-9-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500031', 25000, 1957, 'Quản lí', NULL, 8)
 into NHANVIEN values('QL032', 'Âu Văn An', 'Nam', TO_DATE('2015-7-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500032', 25000, 1512, 'Quản lí', NULL, 1)
 into NHANVIEN values('QL033', 'An Thị Chung', 'Nữ', TO_DATE('2013-12-17','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500033', 25000, 1673, 'Quản lí', NULL, 2)
 into NHANVIEN values('QL034', 'Trương Hoàng Tiến', 'Nữ', TO_DATE('2022-3-18','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500034', 25000, 1514, 'Quản lí', NULL, 3)
 into NHANVIEN values('QL035', 'Ưng Tùng Sáng', 'Nam', TO_DATE('2018-9-16','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500035', 25000, 1670, 'Quản lí', NULL, 4)
 into NHANVIEN values('TDA036', 'Lê Văn Cầu', 'Nữ', TO_DATE('2007-8-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500036', 20000, 1536, 'Trưởng đề án', NULL, 5)
 into NHANVIEN values('TDA037', 'Đặng Hoàng Thông', 'Nam', TO_DATE('2019-5-11','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500037', 20000, 1579, 'Trưởng đề án', NULL, 6)
 into NHANVIEN values('TDA038', 'Phạm Gia Quốc', 'Nam', TO_DATE('2021-4-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500038', 20000, 1125, 'Trưởng đề án', NULL, 7)
 into NHANVIEN values('TP039', 'Đặng Song An', 'Nam', TO_DATE('2012-3-4','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500039', 22000, 1464, 'Trưởng phòng', NULL, 1)
 into NHANVIEN values('TP040', 'Ưng Văn Tân', 'Nữ', TO_DATE('2013-6-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500040', 22000, 1816, 'Trưởng phòng', NULL, 2)
 into NHANVIEN values('TP041', 'An Thị Tú', 'Nữ', TO_DATE('2001-9-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500041', 22000, 1379, 'Trưởng phòng', NULL, 3)
 into NHANVIEN values('TP042', 'Trần Gia Cầu', 'Nữ', TO_DATE('2016-11-20','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500042', 22000, 1215, 'Trưởng phòng', NULL, 4)
 into NHANVIEN values('TP043', 'Võ Gia Nguyệt', 'Nam', TO_DATE('2008-11-28','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500043', 22000, 1189, 'Trưởng phòng', NULL, 5)
 into NHANVIEN values('TP044', 'Lại Hoàng Tú', 'Nam', TO_DATE('2010-4-18','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500044', 22000, 1939, 'Trưởng phòng', NULL, 6)
 into NHANVIEN values('TP045', 'Lý Chí Nam', 'Nữ', TO_DATE('2000-2-15','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500045', 22000, 1947, 'Trưởng phòng', NULL, 7)
 into NHANVIEN values('TP046', 'Đặng Chí Ngọc Nhi', 'Nữ', TO_DATE('2007-1-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500046', 22000, 1999, 'Trưởng phòng', NULL, 8)
 into NHANVIEN values('NV47', 'Nguyễn Gia Tín', 'Nam', TO_DATE('2012-3-10','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500047', 6760, 1495, 'Nhân viên', NULL, 8)
 into NHANVIEN values('NV48', 'Dương Song Anh', 'Nữ', TO_DATE('2016-11-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500048', 5311, 1517, 'Nhân viên', NULL, 1)
 into NHANVIEN values('NV49', 'Giản Chí Cúc', 'Nữ', TO_DATE('2015-7-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500049', 9829, 1008, 'Nhân viên', NULL, 2)
 into NHANVIEN values('NV50', 'Âu Chí Đan', 'Nữ', TO_DATE('2016-9-14','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500050', 1575, 1582, 'Nhân viên', NULL, 3)
 into NHANVIEN values('NV51', 'Đặng Tùng Minh', 'Nam', TO_DATE('2021-4-13','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500051', 6704, 1429, 'Nhân viên', NULL, 4)
 into NHANVIEN values('NV52', 'Ưng Văn Bắc', 'Nam', TO_DATE('2020-4-6','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500052', 5381, 1597, 'Nhân viên', NULL, 5)
 into NHANVIEN values('NV53', 'Vũ Gia Cầu', 'Nữ', TO_DATE('2013-1-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500053', 7512, 1010, 'Nhân viên', NULL, 6)
 into NHANVIEN values('NV54', 'Dương Song Ngọc Nhi', 'Nam', TO_DATE('2020-7-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500054', 9910, 1326, 'Nhân viên', NULL, 7)
 into NHANVIEN values('NV55', 'Nguyễn Tùng Chi', 'Nữ', TO_DATE('2015-11-21','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500055', 6334, 1130, 'Nhân viên', NULL, 8)
 into NHANVIEN values('NV56', 'Lại Thị Đức', 'Nữ', TO_DATE('2020-6-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500056', 9152, 1434, 'Nhân viên', NULL, 1)
 into NHANVIEN values('NV57', 'Nguyễn Chí Nguyệt', 'Nữ', TO_DATE('2020-2-11','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500057', 6581, 1979, 'Nhân viên', NULL, 2)
 into NHANVIEN values('NV58', 'Lê Tùng Cúc', 'Nữ', TO_DATE('2018-8-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500058', 2648, 1871, 'Nhân viên', NULL, 3)
 into NHANVIEN values('NV59', 'Âu Hoàng Đan', 'Nữ', TO_DATE('2012-5-21','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500059', 4366, 1705, 'Nhân viên', NULL, 4)
 into NHANVIEN values('NV60', 'Đoàn Hoàng Minh', 'Nữ', TO_DATE('2007-6-22','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500060', 9639, 1654, 'Nhân viên', NULL, 5)
 into NHANVIEN values('NV61', 'Lê Thị Mây', 'Nữ', TO_DATE('2011-6-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500061', 7749, 1636, 'Nhân viên', NULL, 6)
 into NHANVIEN values('NV62', 'Nguyễn Gia An', 'Nữ', TO_DATE('2004-5-22','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500062', 2505, 1161, 'Nhân viên', NULL, 7)
 into NHANVIEN values('NV63', 'Dương Song Chi', 'Nữ', TO_DATE('2016-6-16','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500063', 6315, 1160, 'Nhân viên', NULL, 8)
 into NHANVIEN values('NV64', 'Vũ Văn Thương', 'Nam', TO_DATE('2017-6-21','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500064', 6376, 1722, 'Nhân viên', NULL, 1)
 into NHANVIEN values('NV65', 'Giản Song Việt', 'Nam', TO_DATE('2016-10-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500065', 6325, 1246, 'Nhân viên', NULL, 2)
 into NHANVIEN values('NV66', 'Giản Tùng Duy', 'Nữ', TO_DATE('2018-6-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500066', 6299, 1405, 'Nhân viên', NULL, 3)
 into NHANVIEN values('NV67', 'Lê Văn Duy', 'Nữ', TO_DATE('2020-6-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500067', 8649, 1222, 'Nhân viên', NULL, 4)
 into NHANVIEN values('NV68', 'Ưng Chí Giang', 'Nữ', TO_DATE('2002-12-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500068', 8752, 1731, 'Nhân viên', NULL, 5)
 into NHANVIEN values('NV69', 'Dương Tùng Vũ', 'Nam', TO_DATE('2002-3-12','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500069', 1325, 1241, 'Nhân viên', NULL, 6)
 into NHANVIEN values('NV70', 'Giản Tùng Ngần', 'Nam', TO_DATE('2012-9-9','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500070', 2472, 1153, 'Nhân viên', NULL, 7)
 into NHANVIEN values('NV71', 'An Văn Hân', 'Nữ', TO_DATE('2012-6-11','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500071', 1654, 1421, 'Nhân viên', NULL, 8)
 into NHANVIEN values('NV72', 'Âu Hoàng Bảo', 'Nam', TO_DATE('2009-6-9','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500072', 8285, 1564, 'Nhân viên', NULL, 1)
 into NHANVIEN values('NV73', 'Bùi Văn Nam', 'Nữ', TO_DATE('2007-5-23','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500073', 3317, 1910, 'Nhân viên', NULL, 2)
 into NHANVIEN values('NV74', 'Trần Tùng Đan', 'Nam', TO_DATE('2015-8-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500074', 2522, 1535, 'Nhân viên', NULL, 3)
 into NHANVIEN values('NV75', 'Bùi Song Sáng', 'Nữ', TO_DATE('2004-4-16','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500075', 9873, 1449, 'Nhân viên', NULL, 4)
 into NHANVIEN values('NV76', 'Lý Hoàng Phú', 'Nam', TO_DATE('2018-7-22','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500076', 1442, 1806, 'Nhân viên', NULL, 5)
 into NHANVIEN values('NV77', 'Nguyễn Hoàng Chung', 'Nữ', TO_DATE('2014-9-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500077', 2180, 1426, 'Nhân viên', NULL, 6)
 into NHANVIEN values('NV78', 'Hồ Song Nam', 'Nữ', TO_DATE('2012-9-27','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500078', 7482, 1409, 'Nhân viên', NULL, 7)
 into NHANVIEN values('NV79', 'Ưng Thị Tín', 'Nam', TO_DATE('2019-9-22','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500079', 3264, 1531, 'Nhân viên', NULL, 8)
 into NHANVIEN values('NV80', 'Phạm Văn Thiên', 'Nam', TO_DATE('2022-9-14','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500080', 6301, 1870, 'Nhân viên', NULL, 1)
 into NHANVIEN values('NV81', 'Âu Song Cúc', 'Nữ', TO_DATE('2008-8-17','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500081', 3491, 1540, 'Nhân viên', NULL, 2)
 into NHANVIEN values('NV82', 'Trương Song Giang', 'Nam', TO_DATE('2001-4-14','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500082', 6269, 1181, 'Nhân viên', NULL, 3)
 into NHANVIEN values('NV83', 'Vũ Thị Ngọc Nhi', 'Nữ', TO_DATE('2012-2-9','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500083', 4404, 1282, 'Nhân viên', NULL, 4)
 into NHANVIEN values('NV84', 'Bùi Thị Anh', 'Nữ', TO_DATE('2009-5-21','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500084', 5463, 1716, 'Nhân viên', NULL, 5)
 into NHANVIEN values('NV85', 'Lê Tùng Đức', 'Nam', TO_DATE('2005-8-22','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500085', 4058, 1767, 'Nhân viên', NULL, 6)
 into NHANVIEN values('NV86', 'Nguyễn Chí Phú', 'Nam', TO_DATE('2021-9-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500086', 4505, 1226, 'Nhân viên', NULL, 7)
 into NHANVIEN values('NV87', 'Hồ Thị Mây', 'Nữ', TO_DATE('2019-10-6','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500087', 3944, 1183, 'Nhân viên', NULL, 8)
 into NHANVIEN values('NV88', 'Lê Thị Tuấn', 'Nam', TO_DATE('2010-3-17','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500088', 9578, 1351, 'Nhân viên', NULL, 1)
 into NHANVIEN values('NV89', 'Trần Văn Sáng', 'Nam', TO_DATE('2022-2-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500089', 5621, 1424, 'Nhân viên', NULL, 2)
 into NHANVIEN values('NV90', 'Trương Văn Đan', 'Nam', TO_DATE('2001-5-25','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500090', 6023, 1304, 'Nhân viên', NULL, 3)
 into NHANVIEN values('NV91', 'Dương Thị Nguyệt', 'Nữ', TO_DATE('2019-11-16','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500091', 1210, 1931, 'Nhân viên', NULL, 4)
 into NHANVIEN values('NV92', 'Võ Hoàng Nam', 'Nam', TO_DATE('2001-7-27','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500092', 9947, 1999, 'Nhân viên', NULL, 5)
 into NHANVIEN values('NV93', 'Ưng Song Mây', 'Nữ', TO_DATE('2011-1-14','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500093', 8650, 1906, 'Nhân viên', NULL, 6)
 into NHANVIEN values('NV94', 'Đặng Văn Chi', 'Nam', TO_DATE('2006-6-10','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500094', 7987, 1839, 'Nhân viên', NULL, 7)
 into NHANVIEN values('NV95', 'Lại Hoàng khanh', 'Nữ', TO_DATE('2022-4-27','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500095', 3423, 1268, 'Nhân viên', NULL, 8)
 into NHANVIEN values('NV96', 'Lý Song Nguyệt', 'Nam', TO_DATE('2006-11-10','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500096', 4398, 1680, 'Nhân viên', NULL, 1)
 into NHANVIEN values('NV97', 'Võ Song Vy', 'Nam', TO_DATE('2008-10-14','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500097', 8804, 1004, 'Nhân viên', NULL, 2)
 into NHANVIEN values('NV98', 'Vũ Hoàng Ngọc Nhi', 'Nam', TO_DATE('2001-11-12','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500098', 6439, 1109, 'Nhân viên', NULL, 3)
 into NHANVIEN values('NV99', 'Dương Thị Minh', 'Nam', TO_DATE('2014-9-18','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500099', 6348, 1301, 'Nhân viên', NULL, 4)
 into NHANVIEN values('NV100', 'Giản Thị Đan', 'Nữ', TO_DATE('2001-12-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '0945000100', 5122, 1962, 'Nhân viên', NULL, 5)
 into NHANVIEN values('NV101', 'An Gia Mây', 'Nữ', TO_DATE('2013-9-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '0945000101', 6413, 1109, 'Nhân viên', NULL, 6)
 into NHANVIEN values('NV102', 'Phạm Chí Duy', 'Nam', TO_DATE('2018-10-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '0945000102', 1327, 1408, 'Nhân viên', NULL, 7)
 into NHANVIEN values('NV103', 'Đặng Chí Thương', 'Nữ', TO_DATE('2021-2-14','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '0945000103', 5862, 1511, 'Nhân viên', NULL, 8)
 into NHANVIEN values('NV104', 'Đặng Văn Tiệp', 'Nam', TO_DATE('2010-11-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '0945000104', 1653, 1652, 'Nhân viên', NULL, 1)

In [6]:
KV = ['Quận 1', 'Quận 2', 'Quận 3','Quận 4','Quận 5','Quận 6','Quận 7','Quận 8','Quận 9','Quận 10','Quận 11','Quận 12','Quận 13', 'Quận Bình Thạnh', 'Quận Tân Bình', 'Hóoc Môn']

## Phong Ban

In [22]:
'''
PhongBan (
	MaPB 	number primary key,
	TenPB 	varchar2(60) not null,
	TrPHG 	varchar(10)
	
)	
'''


for i in range(1, 9):
    final = str(i) + ', ' + '\'Phong ' + str(i) + '\', NULL' 
    print('insert into PHONGBAN values(' +  final + ');')

insert into PHONGBAN values(1, 'Phong 1', NULL);
insert into PHONGBAN values(2, 'Phong 2', NULL);
insert into PHONGBAN values(3, 'Phong 3', NULL);
insert into PHONGBAN values(4, 'Phong 4', NULL);
insert into PHONGBAN values(5, 'Phong 5', NULL);
insert into PHONGBAN values(6, 'Phong 6', NULL);
insert into PHONGBAN values(7, 'Phong 7', NULL);
insert into PHONGBAN values(8, 'Phong 8', NULL);

In [55]:
for i in range(1, 9):
    print( ' UPDATE PHONGBAN set TrPHG = ' + '\'TP0'+ str(i+ 38) + '\'' + ' WHERE ' +  'MaPB = ' + str(i)+ ';')

 UPDATE PHONGBAN set TrPHG = 'TP039' WHERE MaPB = 1;
 UPDATE PHONGBAN set TrPHG = 'TP040' WHERE MaPB = 2;
 UPDATE PHONGBAN set TrPHG = 'TP041' WHERE MaPB = 3;
 UPDATE PHONGBAN set TrPHG = 'TP042' WHERE MaPB = 4;
 UPDATE PHONGBAN set TrPHG = 'TP043' WHERE MaPB = 5;
 UPDATE PHONGBAN set TrPHG = 'TP044' WHERE MaPB = 6;
 UPDATE PHONGBAN set TrPHG = 'TP045' WHERE MaPB = 7;
 UPDATE PHONGBAN set TrPHG = 'TP046' WHERE MaPB = 8;

# Nhan vien

In [48]:
'''
DeAn (
	MaDA 		varchar(10) primary key,
	TenDA 	varchar2(60) not null,
	NgayBD 	date,
	Phong 	number,
    TruongDeAn varchar(10)
	
)
'''
l = []
for i in range(1, 9):
    for j in range(1, rd.randint(3, 5)):
        MaDA = '\'DA' + str(i) + '0' + str(j) + '\'';
        l.append(MaDA);

        TenDA = '\'De An so ' + str(j) + ' Phong ' + str(i) + '\'';
        NgayBD  = 'TO_DATE(' + '\'' + str(rd.randint(2020, 2022)) + '-' + str(rd.randint(1, 12)) + '-' + str(rd.randint(1, 28)) + '\',\'YYYY-MM-DD\')'
        Phong = str(i)
        final = MaDA + ', ' + TenDA + ', ' + NgayBD + ', ' + Phong 
        print('into DEAN values(' +  final + ')')

into DEAN values('DA101', 'De An so 1 Phong 1', TO_DATE('2021-7-2','YYYY-MM-DD'), 1)
into DEAN values('DA102', 'De An so 2 Phong 1', TO_DATE('2022-6-3','YYYY-MM-DD'), 1)
into DEAN values('DA201', 'De An so 1 Phong 2', TO_DATE('2021-6-3','YYYY-MM-DD'), 2)
into DEAN values('DA202', 'De An so 2 Phong 2', TO_DATE('2022-12-25','YYYY-MM-DD'), 2)
into DEAN values('DA301', 'De An so 1 Phong 3', TO_DATE('2022-11-15','YYYY-MM-DD'), 3)
into DEAN values('DA302', 'De An so 2 Phong 3', TO_DATE('2022-7-4','YYYY-MM-DD'), 3)
into DEAN values('DA303', 'De An so 3 Phong 3', TO_DATE('2022-2-9','YYYY-MM-DD'), 3)
into DEAN values('DA401', 'De An so 1 Phong 4', TO_DATE('2021-9-22','YYYY-MM-DD'), 4)
into DEAN values('DA402', 'De An so 2 Phong 4', TO_DATE('2022-6-25','YYYY-MM-DD'), 4)
into DEAN values('DA403', 'De An so 3 Phong 4', TO_DATE('2022-2-20','YYYY-MM-DD'), 4)
into DEAN values('DA501', 'De An so 1 Phong 5', TO_DATE('2020-7-10','YYYY-MM-DD'), 5)
into DEAN values('DA502', 'De An so 2 Phong 5', TO_DATE('2021-7-11','YYYY-MM-DD'), 5)
into DEAN values('DA503', 'De An so 3 Phong 5', TO_DATE('2022-6-3','YYYY-MM-DD'), 5)
into DEAN values('DA504', 'De An so 4 Phong 5', TO_DATE('2022-9-12','YYYY-MM-DD'), 5)
into DEAN values('DA601', 'De An so 1 Phong 6', TO_DATE('2022-6-8','YYYY-MM-DD'), 6)
into DEAN values('DA602', 'De An so 2 Phong 6', TO_DATE('2020-5-9','YYYY-MM-DD'), 6)
into DEAN values('DA603', 'De An so 3 Phong 6', TO_DATE('2022-7-22','YYYY-MM-DD'), 6)
into DEAN values('DA604', 'De An so 4 Phong 6', TO_DATE('2022-11-8','YYYY-MM-DD'), 6)
into DEAN values('DA701', 'De An so 1 Phong 7', TO_DATE('2021-3-20','YYYY-MM-DD'), 7)
into DEAN values('DA702', 'De An so 2 Phong 7', TO_DATE('2022-8-14','YYYY-MM-DD'), 7)
into DEAN values('DA703', 'De An so 3 Phong 7', TO_DATE('2022-1-7','YYYY-MM-DD'), 7)
into DEAN values('DA704', 'De An so 4 Phong 7', TO_DATE('2022-7-23','YYYY-MM-DD'), 7)
into DEAN values('DA801', 'De An so 1 Phong 8', TO_DATE('2022-7-11','YYYY-MM-DD'), 8)
into DEAN values('DA802', 'De An so 2 Phong 8', TO_DATE('2021-7-8','YYYY-MM-DD'), 8)
into DEAN values('DA803', 'De An so 3 Phong 8', TO_DATE('2022-10-7','YYYY-MM-DD'), 8)

## Khach Hang

In [50]:
'''
	PhanCong (
	MaNV 		varchar(10) primary key,
	MaDA 		varchar(10) primary key,
	ThoiGian 	date
	
)

'''
import numpy as np
for i in range(47, 347, 3):
    MaNV = '\'NV'+ str(i) + '\''
    for j in range(1, rd.randint(2, 3)):
        MaDA = '\'DA' + str(i%8 + 1) + '0' + str(j) + '\'';
        TG  = 'TO_DATE(' + '\'' + str(rd.randint(2020, 2022)) + '-' + str(rd.randint(1, 12)) + '-' + str(rd.randint(1, 28)) + '\',\'YYYY-MM-DD\')'
        final = MaNV + ', ' + MaDA + ', ' + TG  
        print('into PHANCONG values(' +  final + ')')

into PHANCONG values('NV47', 'DA801', TO_DATE('2021-5-12','YYYY-MM-DD'))
into PHANCONG values('NV50', 'DA301', TO_DATE('2020-4-5','YYYY-MM-DD'))
into PHANCONG values('NV50', 'DA302', TO_DATE('2022-12-13','YYYY-MM-DD'))
into PHANCONG values('NV53', 'DA601', TO_DATE('2022-9-7','YYYY-MM-DD'))
into PHANCONG values('NV56', 'DA101', TO_DATE('2022-8-28','YYYY-MM-DD'))
into PHANCONG values('NV59', 'DA401', TO_DATE('2022-9-13','YYYY-MM-DD'))
into PHANCONG values('NV62', 'DA701', TO_DATE('2020-11-27','YYYY-MM-DD'))
into PHANCONG values('NV65', 'DA201', TO_DATE('2021-6-8','YYYY-MM-DD'))
into PHANCONG values('NV65', 'DA202', TO_DATE('2021-11-11','YYYY-MM-DD'))
into PHANCONG values('NV68', 'DA501', TO_DATE('2021-7-27','YYYY-MM-DD'))
into PHANCONG values('NV68', 'DA502', TO_DATE('2022-6-8','YYYY-MM-DD'))
into PHANCONG values('NV71', 'DA801', TO_DATE('2020-5-19','YYYY-MM-DD'))
into PHANCONG values('NV71', 'DA802', TO_DATE('2020-1-12','YYYY-MM-DD'))
into PHANCONG values('NV74', 'DA301', TO_DATE('2022-6-2','YYYY-MM-DD'))
into PHANCONG values('NV74', 'DA302', TO_DATE('2022-3-21','YYYY-MM-DD'))
into PHANCONG values('NV77', 'DA601', TO_DATE('2020-1-8','YYYY-MM-DD'))
into PHANCONG values('NV77', 'DA602', TO_DATE('2022-9-5','YYYY-MM-DD'))
into PHANCONG values('NV80', 'DA101', TO_DATE('2021-5-18','YYYY-MM-DD'))
into PHANCONG values('NV83', 'DA401', TO_DATE('2021-1-22','YYYY-MM-DD'))
into PHANCONG values('NV86', 'DA701', TO_DATE('2020-11-5','YYYY-MM-DD'))
into PHANCONG values('NV89', 'DA201', TO_DATE('2021-1-23','YYYY-MM-DD'))
into PHANCONG values('NV92', 'DA501', TO_DATE('2020-8-8','YYYY-MM-DD'))
into PHANCONG values('NV92', 'DA502', TO_DATE('2020-4-20','YYYY-MM-DD'))
into PHANCONG values('NV95', 'DA801', TO_DATE('2022-2-8','YYYY-MM-DD'))
into PHANCONG values('NV95', 'DA802', TO_DATE('2020-10-26','YYYY-MM-DD'))
into PHANCONG values('NV98', 'DA301', TO_DATE('2020-8-10','YYYY-MM-DD'))
into PHANCONG values('NV101', 'DA601', TO_DATE('2022-5-22','YYYY-MM-DD'))
into PHANCONG values('NV104', 'DA101', TO_DATE('2021-12-5','YYYY-MM-DD'))
into PHANCONG values('NV104', 'DA102', TO_DATE('2020-2-20','YYYY-MM-DD'))
into PHANCONG values('NV107', 'DA401', TO_DATE('2021-11-24','YYYY-MM-DD'))
into PHANCONG values('NV110', 'DA701', TO_DATE('2021-10-22','YYYY-MM-DD'))
into PHANCONG values('NV110', 'DA702', TO_DATE('2020-1-14','YYYY-MM-DD'))
into PHANCONG values('NV113', 'DA201', TO_DATE('2020-8-14','YYYY-MM-DD'))
into PHANCONG values('NV116', 'DA501', TO_DATE('2022-9-20','YYYY-MM-DD'))
into PHANCONG values('NV119', 'DA801', TO_DATE('2021-1-26','YYYY-MM-DD'))
into PHANCONG values('NV119', 'DA802', TO_DATE('2021-7-15','YYYY-MM-DD'))
into PHANCONG values('NV122', 'DA301', TO_DATE('2021-3-2','YYYY-MM-DD'))
into PHANCONG values('NV122', 'DA302', TO_DATE('2021-2-16','YYYY-MM-DD'))
into PHANCONG values('NV125', 'DA601', TO_DATE('2021-7-19','YYYY-MM-DD'))
into PHANCONG values('NV128', 'DA101', TO_DATE('2021-10-9','YYYY-MM-DD'))
into PHANCONG values('NV128', 'DA102', TO_DATE('2020-9-24','YYYY-MM-DD'))
into PHANCONG values('NV131', 'DA401', TO_DATE('2022-12-3','YYYY-MM-DD'))
into PHANCONG values('NV134', 'DA701', TO_DATE('2020-5-15','YYYY-MM-DD'))
into PHANCONG values('NV137', 'DA201', TO_DATE('2020-11-3','YYYY-MM-DD'))
into PHANCONG values('NV137', 'DA202', TO_DATE('2022-8-7','YYYY-MM-DD'))
into PHANCONG values('NV140', 'DA501', TO_DATE('2020-9-18','YYYY-MM-DD'))
into PHANCONG values('NV140', 'DA502', TO_DATE('2021-8-3','YYYY-MM-DD'))
into PHANCONG values('NV143', 'DA801', TO_DATE('2020-5-21','YYYY-MM-DD'))
into PHANCONG values('NV143', 'DA802', TO_DATE('2021-10-12','YYYY-MM-DD'))
into PHANCONG values('NV146', 'DA301', TO_DATE('2022-11-21','YYYY-MM-DD'))
into PHANCONG values('NV149', 'DA601', TO_DATE('2020-2-8','YYYY-MM-DD'))
into PHANCONG values('NV149', 'DA602', TO_DATE('2022-5-22','YYYY-MM-DD'))
into PHANCONG values('NV152', 'DA101', TO_DATE('2022-6-20','YYYY-MM-DD'))
into PHANCONG values('NV155', 'DA401', TO_DATE('2020-9-23','YYYY-MM-DD'))
into PHANCONG values('NV155', 'DA402', TO_DATE('2022-4-13','YYYY-MM-DD'))
into PHANCONG values('NV158', 'DA701', TO_DATE('2020-4-16','YYYY-MM-DD'))
into PHANCONG values('NV158', 'DA702', TO_DATE('2021-11-8','YYYY-MM-DD'))
into PHANCONG values('NV161', 'DA201', TO_DATE('2020-4-6','YYYY-MM-DD'))
into PHANCONG values('NV161', 'DA202', TO_DATE('2021-2-16','YYYY-MM-DD'))
into PHANCONG values('NV164', 'DA501', TO_DATE('2022-1-9','YYYY-MM-DD'))
into PHANCONG values('NV167', 'DA801', TO_DATE('2021-2-20','YYYY-MM-DD'))
into PHANCONG values('NV167', 'DA802', TO_DATE('2022-12-16','YYYY-MM-DD'))
into PHANCONG values('NV170', 'DA301', TO_DATE('2021-1-22','YYYY-MM-DD'))
into PHANCONG values('NV170', 'DA302', TO_DATE('2022-4-27','YYYY-MM-DD'))
into PHANCONG values('NV173', 'DA601', TO_DATE('2020-8-27','YYYY-MM-DD'))
into PHANCONG values('NV176', 'DA101', TO_DATE('2020-2-12','YYYY-MM-DD'))
into PHANCONG values('NV176', 'DA102', TO_DATE('2022-7-12','YYYY-MM-DD'))
into PHANCONG values('NV179', 'DA401', TO_DATE('2020-3-11','YYYY-MM-DD'))
into PHANCONG values('NV182', 'DA701', TO_DATE('2022-4-21','YYYY-MM-DD'))
into PHANCONG values('NV185', 'DA201', TO_DATE('2021-10-25','YYYY-MM-DD'))
into PHANCONG values('NV185', 'DA202', TO_DATE('2022-5-12','YYYY-MM-DD'))
into PHANCONG values('NV188', 'DA501', TO_DATE('2022-6-22','YYYY-MM-DD'))
into PHANCONG values('NV188', 'DA502', TO_DATE('2020-1-21','YYYY-MM-DD'))
into PHANCONG values('NV191', 'DA801', TO_DATE('2020-1-6','YYYY-MM-DD'))
into PHANCONG values('NV191', 'DA802', TO_DATE('2022-7-24','YYYY-MM-DD'))
into PHANCONG values('NV194', 'DA301', TO_DATE('2020-3-23','YYYY-MM-DD'))
into PHANCONG values('NV197', 'DA601', TO_DATE('2020-9-5','YYYY-MM-DD'))
into PHANCONG values('NV197', 'DA602', TO_DATE('2020-12-6','YYYY-MM-DD'))
into PHANCONG values('NV200', 'DA101', TO_DATE('2022-9-21','YYYY-MM-DD'))
into PHANCONG values('NV200', 'DA102', TO_DATE('2020-9-17','YYYY-MM-DD'))
into PHANCONG values('NV203', 'DA401', TO_DATE('2022-8-26','YYYY-MM-DD'))
into PHANCONG values('NV203', 'DA402', TO_DATE('2020-3-5','YYYY-MM-DD'))
into PHANCONG values('NV206', 'DA701', TO_DATE('2020-12-26','YYYY-MM-DD'))
into PHANCONG values('NV209', 'DA201', TO_DATE('2020-9-10','YYYY-MM-DD'))
into PHANCONG values('NV212', 'DA501', TO_DATE('2022-1-1','YYYY-MM-DD'))
into PHANCONG values('NV215', 'DA801', TO_DATE('2020-7-9','YYYY-MM-DD'))
into PHANCONG values('NV215', 'DA802', TO_DATE('2022-8-13','YYYY-MM-DD'))
into PHANCONG values('NV218', 'DA301', TO_DATE('2020-12-4','YYYY-MM-DD'))
into PHANCONG values('NV218', 'DA302', TO_DATE('2022-5-27','YYYY-MM-DD'))
into PHANCONG values('NV221', 'DA601', TO_DATE('2021-7-13','YYYY-MM-DD'))
into PHANCONG values('NV224', 'DA101', TO_DATE('2022-2-17','YYYY-MM-DD'))
into PHANCONG values('NV224', 'DA102', TO_DATE('2020-3-5','YYYY-MM-DD'))
into PHANCONG values('NV227', 'DA401', TO_DATE('2021-1-10','YYYY-MM-DD'))
into PHANCONG values('NV230', 'DA701', TO_DATE('2021-10-10','YYYY-MM-DD'))
into PHANCONG values('NV233', 'DA201', TO_DATE('2020-2-28','YYYY-MM-DD'))
into PHANCONG values('NV233', 'DA202', TO_DATE('2021-11-11','YYYY-MM-DD'))
into PHANCONG values('NV236', 'DA501', TO_DATE('2021-9-10','YYYY-MM-DD'))
into PHANCONG values('NV239', 'DA801', TO_DATE('2021-12-26','YYYY-MM-DD'))
into PHANCONG values('NV239', 'DA802', TO_DATE('2021-8-18','YYYY-MM-DD'))
into PHANCONG values('NV242', 'DA301', TO_DATE('2020-2-18','YYYY-MM-DD'))
into PHANCONG values('NV242', 'DA302', TO_DATE('2020-5-8','YYYY-MM-DD'))
into PHANCONG values('NV245', 'DA601', TO_DATE('2022-6-10','YYYY-MM-DD'))
into PHANCONG values('NV248', 'DA101', TO_DATE('2021-4-24','YYYY-MM-DD'))
into PHANCONG values('NV248', 'DA102', TO_DATE('2021-12-8','YYYY-MM-DD'))
into PHANCONG values('NV251', 'DA401', TO_DATE('2022-6-28','YYYY-MM-DD'))
into PHANCONG values('NV254', 'DA701', TO_DATE('2021-6-26','YYYY-MM-DD'))
into PHANCONG values('NV254', 'DA702', TO_DATE('2020-1-22','YYYY-MM-DD'))
into PHANCONG values('NV257', 'DA201', TO_DATE('2020-6-15','YYYY-MM-DD'))
into PHANCONG values('NV257', 'DA202', TO_DATE('2020-5-26','YYYY-MM-DD'))
into PHANCONG values('NV260', 'DA501', TO_DATE('2020-7-19','YYYY-MM-DD'))
into PHANCONG values('NV263', 'DA801', TO_DATE('2022-5-13','YYYY-MM-DD'))
into PHANCONG values('NV266', 'DA301', TO_DATE('2021-1-15','YYYY-MM-DD'))
into PHANCONG values('NV266', 'DA302', TO_DATE('2022-10-19','YYYY-MM-DD'))
into PHANCONG values('NV269', 'DA601', TO_DATE('2021-6-2','YYYY-MM-DD'))
into PHANCONG values('NV269', 'DA602', TO_DATE('2021-2-28','YYYY-MM-DD'))
into PHANCONG values('NV272', 'DA101', TO_DATE('2021-12-10','YYYY-MM-DD'))
into PHANCONG values('NV275', 'DA401', TO_DATE('2020-10-19','YYYY-MM-DD'))
into PHANCONG values('NV275', 'DA402', TO_DATE('2021-2-4','YYYY-MM-DD'))
into PHANCONG values('NV278', 'DA701', TO_DATE('2022-12-3','YYYY-MM-DD'))
into PHANCONG values('NV281', 'DA201', TO_DATE('2022-7-11','YYYY-MM-DD'))
into PHANCONG values('NV284', 'DA501', TO_DATE('2022-6-25','YYYY-MM-DD'))
into PHANCONG values('NV287', 'DA801', TO_DATE('2021-11-25','YYYY-MM-DD'))
into PHANCONG values('NV287', 'DA802', TO_DATE('2022-11-28','YYYY-MM-DD'))
into PHANCONG values('NV290', 'DA301', TO_DATE('2022-11-14','YYYY-MM-DD'))
into PHANCONG values('NV290', 'DA302', TO_DATE('2020-11-17','YYYY-MM-DD'))
into PHANCONG values('NV293', 'DA601', TO_DATE('2022-8-26','YYYY-MM-DD'))
into PHANCONG values('NV296', 'DA101', TO_DATE('2020-2-3','YYYY-MM-DD'))
into PHANCONG values('NV299', 'DA401', TO_DATE('2022-3-28','YYYY-MM-DD'))
into PHANCONG values('NV302', 'DA701', TO_DATE('2021-7-1','YYYY-MM-DD'))
into PHANCONG values('NV302', 'DA702', TO_DATE('2022-6-23','YYYY-MM-DD'))
into PHANCONG values('NV305', 'DA201', TO_DATE('2020-4-26','YYYY-MM-DD'))
into PHANCONG values('NV308', 'DA501', TO_DATE('2022-12-25','YYYY-MM-DD'))
into PHANCONG values('NV311', 'DA801', TO_DATE('2020-4-26','YYYY-MM-DD'))
into PHANCONG values('NV314', 'DA301', TO_DATE('2022-12-13','YYYY-MM-DD'))
into PHANCONG values('NV317', 'DA601', TO_DATE('2020-2-8','YYYY-MM-DD'))
into PHANCONG values('NV320', 'DA101', TO_DATE('2021-4-14','YYYY-MM-DD'))
into PHANCONG values('NV320', 'DA102', TO_DATE('2021-3-25','YYYY-MM-DD'))
into PHANCONG values('NV323', 'DA401', TO_DATE('2020-5-11','YYYY-MM-DD'))
into PHANCONG values('NV326', 'DA701', TO_DATE('2020-6-9','YYYY-MM-DD'))
into PHANCONG values('NV329', 'DA201', TO_DATE('2021-9-20','YYYY-MM-DD'))
into PHANCONG values('NV332', 'DA501', TO_DATE('2021-12-20','YYYY-MM-DD'))
into PHANCONG values('NV332', 'DA502', TO_DATE('2022-8-20','YYYY-MM-DD'))
into PHANCONG values('NV335', 'DA801', TO_DATE('2022-7-4','YYYY-MM-DD'))
into PHANCONG values('NV338', 'DA301', TO_DATE('2020-4-15','YYYY-MM-DD'))
into PHANCONG values('NV341', 'DA601', TO_DATE('2022-10-26','YYYY-MM-DD'))
into PHANCONG values('NV341', 'DA602', TO_DATE('2020-9-12','YYYY-MM-DD'))
into PHANCONG values('NV344', 'DA101', TO_DATE('2022-10-27','YYYY-MM-DD'))
into PHANCONG values('NV344', 'DA102', TO_DATE('2022-9-24','YYYY-MM-DD'))