In [1]:
import random as rd

insert = "insert into table "

In [2]:
Ho = [ 'Ho','Bui', 'Đoan', 'Le', 'Nguyen', 'Duong', 'Tran', 'Ly', 'Vu', 'Vo', 'Đang', 'Pham', 'Ung', 'An', 'Au','Truong', 'Lai', 'Gian' ]
tendem = ['Van','Thi','Chi','Gia','Hoang', 'Song', 'Tung' ]
ten = ['Ngoc Nhi','An','Anh','Bac','Bao','Cau','Cuc','Đan','Đang','Đuc','Thong','Tien','Tuan','Tin','Tiep','Viet','Vinh','Vu','Vy','Minh','Giang','khanh','Sang','Duy','Chi','Thuong','Chung','Phu','Quoc','Nam','Ngan','Nguyet','May' 
       ,'Tu','Thien','Tan','Han']

In [4]:
'''
NhanVien (
	MaNV 		varchar(10) primary key,
	TenNV 	varchar2(60) not null,
	Phai 		varchar2(4),
	NgaySinh 	date,
	DiaChi 	varchar2(100),
	SoDT 		varchar(10) not null unique,
	Luong 	number,
	PhuCap 	number,
	VaiTro 	varchar2(50),
	MaNQL 	varchar(10),
	PHG 		number
	
)
go
'''
'''
Nhân viên - 300
Quản lí - 20
Trưởng phòng - 8
Tài chính - 5
Nhân sự - 5
Trưởng đề án - 3
Ban giám đốc - 5
'''
sex = ['Nam', 'Nu']
import string

username = ''
MaNV = ''
TenNV = ''
Phai = ''
NgaySinh = ''
DiaChi 	= ''
SoDT 	= ''
Luong 	= 0
PhuCap 	= 0
VaiTro 	= ''
MaNQL 	= 'NULL'
PHG 	= 0
for i in range(1, 347):
    Luong = rd.randint(1000, 9999)
    PhuCap = rd.randint(1000, 2000)
    PHG = i % 8 + 1
    if i < 6:
        MaNV = '\'GD00'+ str(i) + '\''
        VaiTro 	= '\'Ban giam doc\''
        Luong = 55555
    elif i < 11:
        MaNV = '\'TC0'+ str(i) + '\''
        VaiTro 	= '\'Tai chinh\''
        Luong = 11000
    elif i < 16:
        MaNV = '\'NS0'+ str(i) + '\''
        VaiTro 	= '\'Nhan su\''
        Luong = 13000
    elif i < 36:
        MaNV = '\'QL0'+ str(i) + '\''
        VaiTro 	= '\'Quan li\''
        Luong = 25000
    elif i < 39:
        MaNV = '\'TDA0'+ str(i) + '\''
        VaiTro 	= '\'Truong de an\''
        Luong = 20000
    elif i < 47:
        MaNV = '\'TP0'+ str(i) + '\''
        VaiTro 	= '\'Truong phong\''
        Luong = 22000
        PHG = i - 38
    else:
        MaNV = '\'NV'+ str(i) + '\''
        VaiTro 	= '\'Nhan vien\''
        MaNQL = '\'QL0' + str((i - 47) % 20 + 16) + '\''s
     
    
    account_suffix = MaNV.replace("'", "")
    username = f'\'User{account_suffix}\''

    SoDT = '\'0945000' + str(i) + '\''
    TenNV = '\'' + rd.choice(Ho) + ' ' + rd.choice(tendem) + ' ' + rd.choice(ten) + '\''
    DiaChi = '\'227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh\'' 
    Phai = '\'' + rd.choice(sex) + '\''
    NgaySinh  = 'TO_DATE(' + '\'' + str(rd.randint(2000, 2022)) + '-' + str(rd.randint(1, 12)) + '-' + str(rd.randint(1, 28)) + '\',\'YYYY-MM-DD\')'
    
    final = MaNV + ', ' + TenNV + ', ' + Phai + ', ' + NgaySinh + ', ' + DiaChi +', ' + SoDT + ', ' + str(Luong) + ', ' + str(PhuCap) +', '+ VaiTro + ', ' + MaNQL + ', ' + str(PHG) + ', ' + username
    
    print (' into NHANVIEN values(' +  final + ')')
    
   # print('insert into TaiKhoan values(' + TenTaiKhoan + HoTen + str(Mk) + sdt + DiaChi + Email + LoaiTaiKhoan +')')

 into NHANVIEN values('GD001', 'Au Tung Cau', 'Nam', TO_DATE('2004-12-22','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450001', 55555, 1808, 'Ban giam doc', NULL, 2, 'UserGD001')
 into NHANVIEN values('GD002', 'Gian Chi khanh', 'Nam', TO_DATE('2004-10-12','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450002', 55555, 1193, 'Ban giam doc', NULL, 3, 'UserGD002')
 into NHANVIEN values('GD003', 'Ung Hoang Quoc', 'Nu', TO_DATE('2006-1-3','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450003', 55555, 1726, 'Ban giam doc', NULL, 4, 'UserGD003')
 into NHANVIEN values('GD004', 'Đoan Gia Tin', 'Nam', TO_DATE('2010-3-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450004', 55555, 1965, 'Ban giam doc', NULL, 5, 'UserGD004')
 into NHANVIEN values('GD005', 'Truong Tung Bac', 'Nam', TO_DATE('2014-12-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450005', 55555, 1993, 'Ban giam doc', NULL, 6, 'UserGD005')
 into NHANVIEN values('TC06', 'Duong Hoang Vy', 'Nam', TO_DATE('2000-3-25','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450006', 11000, 1196, 'Tai chinh', NULL, 7, 'UserTC06')
 into NHANVIEN values('TC07', 'Đoan Thi Bao', 'Nam', TO_DATE('2008-2-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450007', 11000, 1965, 'Tai chinh', NULL, 8, 'UserTC07')
 into NHANVIEN values('TC08', 'Tran Chi May', 'Nu', TO_DATE('2021-2-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450008', 11000, 1945, 'Tai chinh', NULL, 1, 'UserTC08')
 into NHANVIEN values('TC09', 'Vo Hoang Giang', 'Nu', TO_DATE('2015-1-16','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450009', 11000, 1945, 'Tai chinh', NULL, 2, 'UserTC09')
 into NHANVIEN values('TC010', 'Au Song Quoc', 'Nu', TO_DATE('2018-6-3','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500010', 11000, 1225, 'Tai chinh', NULL, 3, 'UserTC010')
 into NHANVIEN values('NS011', 'Ho Van Vinh', 'Nam', TO_DATE('2016-5-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500011', 13000, 1254, 'Nhan su', NULL, 4, 'UserNS011')
 into NHANVIEN values('NS012', 'Lai Song An', 'Nam', TO_DATE('2006-7-19','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500012', 13000, 1137, 'Nhan su', NULL, 5, 'UserNS012')
 into NHANVIEN values('NS013', 'Tran Song Chi', 'Nam', TO_DATE('2004-10-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500013', 13000, 1788, 'Nhan su', NULL, 6, 'UserNS013')
 into NHANVIEN values('NS014', 'Duong Tung Vy', 'Nu', TO_DATE('2005-6-20','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500014', 13000, 1912, 'Nhan su', NULL, 7, 'UserNS014')
 into NHANVIEN values('NS015', 'Pham Thi Vinh', 'Nam', TO_DATE('2003-1-23','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500015', 13000, 1197, 'Nhan su', NULL, 8, 'UserNS015')
 into NHANVIEN values('QL016', 'Vu Chi Ngoc Nhi', 'Nu', TO_DATE('2016-12-28','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500016', 25000, 1707, 'Quan li', NULL, 1, 'UserQL016')
 into NHANVIEN values('QL017', 'Truong Van Thien', 'Nam', TO_DATE('2009-6-3','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500017', 25000, 1721, 'Quan li', NULL, 2, 'UserQL017')
 into NHANVIEN values('QL018', 'Bui Song Ngoc Nhi', 'Nam', TO_DATE('2020-10-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500018', 25000, 1634, 'Quan li', NULL, 3, 'UserQL018')
 into NHANVIEN values('QL019', 'Duong Gia Chung', 'Nam', TO_DATE('2021-5-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500019', 25000, 1429, 'Quan li', NULL, 4, 'UserQL019')
 into NHANVIEN values('QL020', 'Ung Song Đuc', 'Nam', TO_DATE('2016-8-13','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500020', 25000, 1824, 'Quan li', NULL, 5, 'UserQL020')
 into NHANVIEN values('QL021', 'Vo Van Bac', 'Nam', TO_DATE('2000-5-11','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500021', 25000, 1121, 'Quan li', NULL, 6, 'UserQL021')
 into NHANVIEN values('QL022', 'Đang Song Đan', 'Nam', TO_DATE('2010-4-28','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500022', 25000, 1899, 'Quan li', NULL, 7, 'UserQL022')
 into NHANVIEN values('QL023', 'Pham Gia Tin', 'Nu', TO_DATE('2013-2-17','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500023', 25000, 1304, 'Quan li', NULL, 8, 'UserQL023')
 into NHANVIEN values('QL024', 'Au Gia Anh', 'Nu', TO_DATE('2005-12-23','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500024', 25000, 1790, 'Quan li', NULL, 1, 'UserQL024')
 into NHANVIEN values('QL025', 'Tran Gia Tien', 'Nam', TO_DATE('2009-3-17','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500025', 25000, 1586, 'Quan li', NULL, 2, 'UserQL025')
 into NHANVIEN values('QL026', 'Lai Thi Chung', 'Nu', TO_DATE('2008-6-20','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500026', 25000, 1389, 'Quan li', NULL, 3, 'UserQL026')
 into NHANVIEN values('QL027', 'Au Thi Anh', 'Nam', TO_DATE('2011-7-25','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500027', 25000, 1801, 'Quan li', NULL, 4, 'UserQL027')
 into NHANVIEN values('QL028', 'Duong Gia Vu', 'Nam', TO_DATE('2010-2-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500028', 25000, 1135, 'Quan li', NULL, 5, 'UserQL028')
 into NHANVIEN values('QL029', 'Bui Van Bac', 'Nam', TO_DATE('2017-3-18','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500029', 25000, 1859, 'Quan li', NULL, 6, 'UserQL029')
 into NHANVIEN values('QL030', 'Le Thi Tin', 'Nam', TO_DATE('2011-7-19','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500030', 25000, 1968, 'Quan li', NULL, 7, 'UserQL030')
 into NHANVIEN values('QL031', 'Truong Van Han', 'Nam', TO_DATE('2022-12-10','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500031', 25000, 1419, 'Quan li', NULL, 8, 'UserQL031')
 into NHANVIEN values('QL032', 'Ly Hoang Cau', 'Nam', TO_DATE('2012-10-17','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500032', 25000, 1395, 'Quan li', NULL, 1, 'UserQL032')
 into NHANVIEN values('QL033', 'Le Chi Nguyet', 'Nam', TO_DATE('2009-12-24','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500033', 25000, 1610, 'Quan li', NULL, 2, 'UserQL033')
 into NHANVIEN values('QL034', 'Pham Song Minh', 'Nam', TO_DATE('2010-2-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500034', 25000, 1834, 'Quan li', NULL, 3, 'UserQL034')
 into NHANVIEN values('QL035', 'Le Gia Ngoc Nhi', 'Nam', TO_DATE('2003-12-20','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500035', 25000, 1167, 'Quan li', NULL, 4, 'UserQL035')
 into NHANVIEN values('TDA036', 'Nguyen Tung Duy', 'Nu', TO_DATE('2013-11-4','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500036', 20000, 1683, 'Truong de an', NULL, 5, 'UserTDA036')
 into NHANVIEN values('TDA037', 'Gian Chi Vinh', 'Nam', TO_DATE('2020-7-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500037', 20000, 1480, 'Truong de an', NULL, 6, 'UserTDA037')
 into NHANVIEN values('TDA038', 'Duong Tung Viet', 'Nu', TO_DATE('2003-8-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500038', 20000, 1935, 'Truong de an', NULL, 7, 'UserTDA038')
 into NHANVIEN values('TP039', 'Truong Chi Quoc', 'Nam', TO_DATE('2020-12-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500039', 22000, 1305, 'Truong phong', NULL, 1, 'UserTP039')
 into NHANVIEN values('TP040', 'An Chi Vinh', 'Nu', TO_DATE('2020-2-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500040', 22000, 1055, 'Truong phong', NULL, 2, 'UserTP040')
 into NHANVIEN values('TP041', 'Pham Van Vy', 'Nam', TO_DATE('2017-12-21','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500041', 22000, 1660, 'Truong phong', NULL, 3, 'UserTP041')
 into NHANVIEN values('TP042', 'Duong Song Minh', 'Nam', TO_DATE('2004-11-9','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500042', 22000, 1319, 'Truong phong', NULL, 4, 'UserTP042')
 into NHANVIEN values('TP043', 'An Tung Duy', 'Nu', TO_DATE('2007-9-23','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500043', 22000, 1453, 'Truong phong', NULL, 5, 'UserTP043')
 into NHANVIEN values('TP044', 'Duong Gia Nam', 'Nu', TO_DATE('2017-12-15','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500044', 22000, 1252, 'Truong phong', NULL, 6, 'UserTP044')
 into NHANVIEN values('TP045', 'Pham Hoang Vy', 'Nu', TO_DATE('2012-1-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500045', 22000, 1207, 'Truong phong', NULL, 7, 'UserTP045')
 into NHANVIEN values('TP046', 'Đang Van Tu', 'Nu', TO_DATE('2008-12-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500046', 22000, 1805, 'Truong phong', NULL, 8, 'UserTP046')
 into NHANVIEN values('NV47', 'Ho Thi Cuc', 'Nam', TO_DATE('2015-7-17','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500047', 1725, 1983, 'Nhan vien', 'QL016', 8, 'UserNV47')
 into NHANVIEN values('NV48', 'Lai Hoang Bac', 'Nu', TO_DATE('2012-2-13','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500048', 9368, 1525, 'Nhan vien', 'QL017', 1, 'UserNV48')
 into NHANVIEN values('NV49', 'Vo Hoang Duy', 'Nu', TO_DATE('2019-3-3','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500049', 4339, 1600, 'Nhan vien', 'QL018', 2, 'UserNV49')
 into NHANVIEN values('NV50', 'Ly Tung Sang', 'Nam', TO_DATE('2018-4-20','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500050', 1902, 1185, 'Nhan vien', 'QL019', 3, 'UserNV50')
 into NHANVIEN values('NV51', 'Nguyen Thi Phu', 'Nu', TO_DATE('2008-12-23','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500051', 2269, 1904, 'Nhan vien', 'QL020', 4, 'UserNV51')
 into NHANVIEN values('NV52', 'Đoan Chi Tin', 'Nam', TO_DATE('2013-1-15','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500052', 8353, 1471, 'Nhan vien', 'QL021', 5, 'UserNV52')
 into NHANVIEN values('NV53', 'An Chi Vy', 'Nu', TO_DATE('2014-6-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500053', 7049, 1609, 'Nhan vien', 'QL022', 6, 'UserNV53')
 into NHANVIEN values('NV54', 'Tran Hoang Tuan', 'Nam', TO_DATE('2017-4-13','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500054', 2777, 1273, 'Nhan vien', 'QL023', 7, 'UserNV54')
 into NHANVIEN values('NV55', 'Gian Van May', 'Nu', TO_DATE('2000-7-20','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500055', 7892, 1726, 'Nhan vien', 'QL024', 8, 'UserNV55')
 into NHANVIEN values('NV56', 'Vu Tung Anh', 'Nam', TO_DATE('2005-12-12','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500056', 1775, 1105, 'Nhan vien', 'QL025', 1, 'UserNV56')
 into NHANVIEN values('NV57', 'Le Chi Minh', 'Nu', TO_DATE('2002-11-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500057', 2318, 1427, 'Nhan vien', 'QL026', 2, 'UserNV57')
 into NHANVIEN values('NV58', 'Truong Thi Ngoc Nhi', 'Nu', TO_DATE('2008-6-22','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500058', 8728, 1046, 'Nhan vien', 'QL027', 3, 'UserNV58')
 into NHANVIEN values('NV59', 'Ho Van Tuan', 'Nam', TO_DATE('2014-3-12','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500059', 2985, 1961, 'Nhan vien', 'QL028', 4, 'UserNV59')
 into NHANVIEN values('NV60', 'Tran Hoang Ngan', 'Nu', TO_DATE('2008-1-23','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500060', 4985, 1888, 'Nhan vien', 'QL029', 5, 'UserNV60')
 into NHANVIEN values('NV61', 'Đang Van Sang', 'Nu', TO_DATE('2006-2-10','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500061', 7069, 1970, 'Nhan vien', 'QL030', 6, 'UserNV61')
 into NHANVIEN values('NV62', 'Vo Hoang Chung', 'Nam', TO_DATE('2005-4-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500062', 5331, 1645, 'Nhan vien', 'QL031', 7, 'UserNV62')
 into NHANVIEN values('NV63', 'Nguyen Gia Bac', 'Nu', TO_DATE('2014-10-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500063', 3991, 1708, 'Nhan vien', 'QL032', 8, 'UserNV63')
 into NHANVIEN values('NV64', 'Gian Gia Đuc', 'Nam', TO_DATE('2015-6-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500064', 4015, 1866, 'Nhan vien', 'QL033', 1, 'UserNV64')
 into NHANVIEN values('NV65', 'Vo Thi Bao', 'Nam', TO_DATE('2010-4-21','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500065', 5827, 1831, 'Nhan vien', 'QL034', 2, 'UserNV65')
 into NHANVIEN values('NV66', 'Vo Chi Chi', 'Nam', TO_DATE('2006-7-23','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500066', 2615, 1691, 'Nhan vien', 'QL035', 3, 'UserNV66')
 into NHANVIEN values('NV67', 'Đang Song Anh', 'Nam', TO_DATE('2004-10-6','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500067', 4897, 1305, 'Nhan vien', 'QL016', 4, 'UserNV67')
 into NHANVIEN values('NV68', 'Duong Song Anh', 'Nu', TO_DATE('2016-1-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500068', 1421, 1812, 'Nhan vien', 'QL017', 5, 'UserNV68')
 into NHANVIEN values('NV69', 'Ung Van Thien', 'Nu', TO_DATE('2003-12-11','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500069', 9584, 1281, 'Nhan vien', 'QL018', 6, 'UserNV69')
 into NHANVIEN values('NV70', 'Vo Chi Đang', 'Nu', TO_DATE('2001-9-24','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500070', 7334, 1885, 'Nhan vien', 'QL019', 7, 'UserNV70')
 into NHANVIEN values('NV71', 'Bui Chi Sang', 'Nam', TO_DATE('2007-11-10','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500071', 8097, 1289, 'Nhan vien', 'QL020', 8, 'UserNV71')
 into NHANVIEN values('NV72', 'An Tung Thien', 'Nam', TO_DATE('2020-5-28','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500072', 6404, 1457, 'Nhan vien', 'QL021', 1, 'UserNV72')
 into NHANVIEN values('NV73', 'Ly Chi Vinh', 'Nam', TO_DATE('2005-5-21','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500073', 4047, 1130, 'Nhan vien', 'QL022', 2, 'UserNV73')
 into NHANVIEN values('NV74', 'Ly Gia Thien', 'Nam', TO_DATE('2009-8-15','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500074', 6763, 1461, 'Nhan vien', 'QL023', 3, 'UserNV74')
 into NHANVIEN values('NV75', 'Nguyen Chi Đuc', 'Nu', TO_DATE('2006-9-18','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500075', 7743, 1951, 'Nhan vien', 'QL024', 4, 'UserNV75')
 into NHANVIEN values('NV76', 'Vu Hoang Vinh', 'Nu', TO_DATE('2020-7-27','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500076', 3601, 1175, 'Nhan vien', 'QL025', 5, 'UserNV76')
 into NHANVIEN values('NV77', 'Đang Chi Chi', 'Nam', TO_DATE('2020-12-11','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500077', 1517, 1603, 'Nhan vien', 'QL026', 6, 'UserNV77')
 into NHANVIEN values('NV78', 'Lai Thi Vu', 'Nu', TO_DATE('2013-2-23','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500078', 7564, 1672, 'Nhan vien', 'QL027', 7, 'UserNV78')
 into NHANVIEN values('NV79', 'Pham Tung Ngan', 'Nam', TO_DATE('2004-5-4','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500079', 7096, 1021, 'Nhan vien', 'QL028', 8, 'UserNV79')
 into NHANVIEN values('NV80', 'Đoan Tung Thien', 'Nu', TO_DATE('2018-3-6','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500080', 8694, 1971, 'Nhan vien', 'QL029', 1, 'UserNV80')
 into NHANVIEN values('NV81', 'Đoan Thi Đuc', 'Nu', TO_DATE('2006-10-14','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500081', 6682, 1135, 'Nhan vien', 'QL030', 2, 'UserNV81')
 into NHANVIEN values('NV82', 'Vu Van Han', 'Nam', TO_DATE('2008-3-12','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500082', 4849, 1294, 'Nhan vien', 'QL031', 3, 'UserNV82')
 into NHANVIEN values('NV83', 'Nguyen Song khanh', 'Nam', TO_DATE('2013-2-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500083', 6858, 2000, 'Nhan vien', 'QL032', 4, 'UserNV83')
 into NHANVIEN values('NV84', 'Ly Hoang Vinh', 'Nu', TO_DATE('2009-1-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500084', 7830, 1816, 'Nhan vien', 'QL033', 5, 'UserNV84')
 into NHANVIEN values('NV85', 'Vu Gia Thien', 'Nam', TO_DATE('2016-11-23','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500085', 3156, 1906, 'Nhan vien', 'QL034', 6, 'UserNV85')
 into NHANVIEN values('NV86', 'Đang Chi Sang', 'Nu', TO_DATE('2013-10-14','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500086', 2289, 1046, 'Nhan vien', 'QL035', 7, 'UserNV86')
 into NHANVIEN values('NV87', 'Đoan Van May', 'Nam', TO_DATE('2005-1-18','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500087', 5517, 1610, 'Nhan vien', 'QL016', 8, 'UserNV87')
 into NHANVIEN values('NV88', 'Duong Van Nam', 'Nu', TO_DATE('2008-6-18','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500088', 2087, 1672, 'Nhan vien', 'QL017', 1, 'UserNV88')
 into NHANVIEN values('NV89', 'Tran Song Bac', 'Nam', TO_DATE('2006-10-25','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500089', 6027, 1757, 'Nhan vien', 'QL018', 2, 'UserNV89')
 into NHANVIEN values('NV90', 'Duong Van Thong', 'Nu', TO_DATE('2011-2-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500090', 4461, 1627, 'Nhan vien', 'QL019', 3, 'UserNV90')
 into NHANVIEN values('NV91', 'Lai Tung Tin', 'Nu', TO_DATE('2003-2-17','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500091', 7176, 1241, 'Nhan vien', 'QL020', 4, 'UserNV91')
 into NHANVIEN values('NV92', 'Ho Van Đang', 'Nu', TO_DATE('2012-3-10','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500092', 9203, 1239, 'Nhan vien', 'QL021', 5, 'UserNV92')
 into NHANVIEN values('NV93', 'Duong Tung Tiep', 'Nam', TO_DATE('2009-11-6','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500093', 9835, 1119, 'Nhan vien', 'QL022', 6, 'UserNV93')
 into NHANVIEN values('NV94', 'Au Gia Minh', 'Nu', TO_DATE('2010-9-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500094', 3408, 1669, 'Nhan vien', 'QL023', 7, 'UserNV94')
 into NHANVIEN values('NV95', 'Gian Song May', 'Nam', TO_DATE('2020-10-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500095', 5789, 1353, 'Nhan vien', 'QL024', 8, 'UserNV95')
 into NHANVIEN values('NV96', 'Ung Song Bao', 'Nam', TO_DATE('2007-12-11','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500096', 5259, 1161, 'Nhan vien', 'QL025', 1, 'UserNV96')
 into NHANVIEN values('NV97', 'Pham Van Minh', 'Nu', TO_DATE('2017-11-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500097', 2828, 1378, 'Nhan vien', 'QL026', 2, 'UserNV97')

In [9]:
KV = ['Quan 1', 'Quan 2', 'Quan 3','Quan 4','Quan 5','Quan 6','Quan 7','Quan 8','Quan 9','Quan 10','Quan 11','Quan 12','Quan 13', 'Quan Bình Thạnh', 'Quan Tân Bình', 'Hóoc Môn']

## Phong Ban

In [22]:
'''
PhongBan (
	MaPB 	number primary key,
	TenPB 	varchar2(60) not null,
	TrPHG 	varchar(10)
	
)	
'''


for i in range(1, 9):
    final = str(i) + ', ' + '\'Phong ' + str(i) + '\', NULL' 
    print('insert into PHONGBAN values(' +  final + ');')

insert into PHONGBAN values(1, 'Phong 1', NULL);
insert into PHONGBAN values(2, 'Phong 2', NULL);
insert into PHONGBAN values(3, 'Phong 3', NULL);
insert into PHONGBAN values(4, 'Phong 4', NULL);
insert into PHONGBAN values(5, 'Phong 5', NULL);
insert into PHONGBAN values(6, 'Phong 6', NULL);
insert into PHONGBAN values(7, 'Phong 7', NULL);
insert into PHONGBAN values(8, 'Phong 8', NULL);

In [55]:
for i in range(1, 9):
    print( ' UPDATE PHONGBAN set TrPHG = ' + '\'TP0'+ str(i+ 38) + '\'' + ' WHERE ' +  'MaPB = ' + str(i)+ ';')

 UPDATE PHONGBAN set TrPHG = 'TP039' WHERE MaPB = 1;
 UPDATE PHONGBAN set TrPHG = 'TP040' WHERE MaPB = 2;
 UPDATE PHONGBAN set TrPHG = 'TP041' WHERE MaPB = 3;
 UPDATE PHONGBAN set TrPHG = 'TP042' WHERE MaPB = 4;
 UPDATE PHONGBAN set TrPHG = 'TP043' WHERE MaPB = 5;
 UPDATE PHONGBAN set TrPHG = 'TP044' WHERE MaPB = 6;
 UPDATE PHONGBAN set TrPHG = 'TP045' WHERE MaPB = 7;
 UPDATE PHONGBAN set TrPHG = 'TP046' WHERE MaPB = 8;

# DE AN

In [32]:
'''
DeAn (
	MaDA 		varchar(10) primary key,
	TenDA 	varchar2(60) not null,
	NgayBD 	date,
	Phong 	number,
    TruongDeAn varchar(10)
	
)
'''
l = []
for i in range(1, 9):
    for j in range(1, rd.randint(3, 5)):
        MaDA = '\'DA' + str(i) + '0' + str(j) + '\'';
        l.append(MaDA);

        TenDA = '\'De An so ' + str(j) + ' Phong ' + str(i) + '\'';
        NgayBD  = 'TO_DATE(' + '\'' + str(rd.randint(2020, 2022)) + '-' + str(rd.randint(1, 12)) + '-' + str(rd.randint(1, 28)) + '\',\'YYYY-MM-DD\')'
        Phong = str(i)
        TruongDA = 'TDA0' + str(rd.randint(36, 38))
        final = MaDA + ', ' + TenDA + ', ' + NgayBD + ', ' + Phong + ', ' + TruongDA
        print('into DEAN values(' +  final + ')')

into DEAN values('DA101', 'De An so 1 Phong 1', TO_DATE('2021-7-10','YYYY-MM-DD'), 1, TDA036)
into DEAN values('DA102', 'De An so 2 Phong 1', TO_DATE('2021-3-28','YYYY-MM-DD'), 1, TDA037)
into DEAN values('DA201', 'De An so 1 Phong 2', TO_DATE('2021-10-13','YYYY-MM-DD'), 2, TDA037)
into DEAN values('DA202', 'De An so 2 Phong 2', TO_DATE('2020-8-2','YYYY-MM-DD'), 2, TDA038)
into DEAN values('DA203', 'De An so 3 Phong 2', TO_DATE('2021-3-24','YYYY-MM-DD'), 2, TDA037)
into DEAN values('DA301', 'De An so 1 Phong 3', TO_DATE('2020-4-11','YYYY-MM-DD'), 3, TDA037)
into DEAN values('DA302', 'De An so 2 Phong 3', TO_DATE('2022-12-11','YYYY-MM-DD'), 3, TDA036)
into DEAN values('DA401', 'De An so 1 Phong 4', TO_DATE('2020-9-3','YYYY-MM-DD'), 4, TDA036)
into DEAN values('DA402', 'De An so 2 Phong 4', TO_DATE('2020-12-15','YYYY-MM-DD'), 4, TDA037)
into DEAN values('DA403', 'De An so 3 Phong 4', TO_DATE('2021-9-2','YYYY-MM-DD'), 4, TDA036)
into DEAN values('DA501', 'De An so 1 Phong 5', TO_DATE('2021-7-25','YYYY-MM-DD'), 5, TDA036)
into DEAN values('DA502', 'De An so 2 Phong 5', TO_DATE('2020-2-25','YYYY-MM-DD'), 5, TDA038)
into DEAN values('DA601', 'De An so 1 Phong 6', TO_DATE('2022-4-26','YYYY-MM-DD'), 6, TDA038)
into DEAN values('DA602', 'De An so 2 Phong 6', TO_DATE('2021-1-17','YYYY-MM-DD'), 6, TDA037)
into DEAN values('DA603', 'De An so 3 Phong 6', TO_DATE('2020-11-26','YYYY-MM-DD'), 6, TDA038)
into DEAN values('DA604', 'De An so 4 Phong 6', TO_DATE('2021-6-5','YYYY-MM-DD'), 6, TDA037)
into DEAN values('DA701', 'De An so 1 Phong 7', TO_DATE('2021-4-11','YYYY-MM-DD'), 7, TDA038)
into DEAN values('DA702', 'De An so 2 Phong 7', TO_DATE('2020-8-24','YYYY-MM-DD'), 7, TDA037)
into DEAN values('DA703', 'De An so 3 Phong 7', TO_DATE('2020-4-22','YYYY-MM-DD'), 7, TDA037)
into DEAN values('DA704', 'De An so 4 Phong 7', TO_DATE('2022-12-2','YYYY-MM-DD'), 7, TDA037)
into DEAN values('DA801', 'De An so 1 Phong 8', TO_DATE('2022-11-7','YYYY-MM-DD'), 8, TDA037)
into DEAN values('DA802', 'De An so 2 Phong 8', TO_DATE('2021-9-21','YYYY-MM-DD'), 8, TDA038)
into DEAN values('DA803', 'De An so 3 Phong 8', TO_DATE('2020-8-17','YYYY-MM-DD'), 8, TDA037)
into DEAN values('DA804', 'De An so 4 Phong 8', TO_DATE('2021-9-23','YYYY-MM-DD'), 8, TDA037)

## Phan Cong

In [50]:
'''
	PhanCong (
	MaNV 		varchar(10) primary key,
	MaDA 		varchar(10) primary key,
	ThoiGian 	date
	
)

'''
import numpy as np
for i in range(47, 347, 3):
    MaNV = '\'NV'+ str(i) + '\''
    for j in range(1, rd.randint(2, 3)):
        MaDA = '\'DA' + str(i%8 + 1) + '0' + str(j) + '\'';
        TG  = 'TO_DATE(' + '\'' + str(rd.randint(2020, 2022)) + '-' + str(rd.randint(1, 12)) + '-' + str(rd.randint(1, 28)) + '\',\'YYYY-MM-DD\')'
        final = MaNV + ', ' + MaDA + ', ' + TG  
        print('into PHANCONG values(' +  final + ')')

into PHANCONG values('NV47', 'DA801', TO_DATE('2021-5-12','YYYY-MM-DD'))
into PHANCONG values('NV50', 'DA301', TO_DATE('2020-4-5','YYYY-MM-DD'))
into PHANCONG values('NV50', 'DA302', TO_DATE('2022-12-13','YYYY-MM-DD'))
into PHANCONG values('NV53', 'DA601', TO_DATE('2022-9-7','YYYY-MM-DD'))
into PHANCONG values('NV56', 'DA101', TO_DATE('2022-8-28','YYYY-MM-DD'))
into PHANCONG values('NV59', 'DA401', TO_DATE('2022-9-13','YYYY-MM-DD'))
into PHANCONG values('NV62', 'DA701', TO_DATE('2020-11-27','YYYY-MM-DD'))
into PHANCONG values('NV65', 'DA201', TO_DATE('2021-6-8','YYYY-MM-DD'))
into PHANCONG values('NV65', 'DA202', TO_DATE('2021-11-11','YYYY-MM-DD'))
into PHANCONG values('NV68', 'DA501', TO_DATE('2021-7-27','YYYY-MM-DD'))
into PHANCONG values('NV68', 'DA502', TO_DATE('2022-6-8','YYYY-MM-DD'))
into PHANCONG values('NV71', 'DA801', TO_DATE('2020-5-19','YYYY-MM-DD'))
into PHANCONG values('NV71', 'DA802', TO_DATE('2020-1-12','YYYY-MM-DD'))
into PHANCONG values('NV74', 'DA301', TO_DATE('2022-6-2','YYYY-MM-DD'))
into PHANCONG values('NV74', 'DA302', TO_DATE('2022-3-21','YYYY-MM-DD'))
into PHANCONG values('NV77', 'DA601', TO_DATE('2020-1-8','YYYY-MM-DD'))
into PHANCONG values('NV77', 'DA602', TO_DATE('2022-9-5','YYYY-MM-DD'))
into PHANCONG values('NV80', 'DA101', TO_DATE('2021-5-18','YYYY-MM-DD'))
into PHANCONG values('NV83', 'DA401', TO_DATE('2021-1-22','YYYY-MM-DD'))
into PHANCONG values('NV86', 'DA701', TO_DATE('2020-11-5','YYYY-MM-DD'))
into PHANCONG values('NV89', 'DA201', TO_DATE('2021-1-23','YYYY-MM-DD'))
into PHANCONG values('NV92', 'DA501', TO_DATE('2020-8-8','YYYY-MM-DD'))
into PHANCONG values('NV92', 'DA502', TO_DATE('2020-4-20','YYYY-MM-DD'))
into PHANCONG values('NV95', 'DA801', TO_DATE('2022-2-8','YYYY-MM-DD'))
into PHANCONG values('NV95', 'DA802', TO_DATE('2020-10-26','YYYY-MM-DD'))
into PHANCONG values('NV98', 'DA301', TO_DATE('2020-8-10','YYYY-MM-DD'))
into PHANCONG values('NV101', 'DA601', TO_DATE('2022-5-22','YYYY-MM-DD'))
into PHANCONG values('NV104', 'DA101', TO_DATE('2021-12-5','YYYY-MM-DD'))
into PHANCONG values('NV104', 'DA102', TO_DATE('2020-2-20','YYYY-MM-DD'))
into PHANCONG values('NV107', 'DA401', TO_DATE('2021-11-24','YYYY-MM-DD'))
into PHANCONG values('NV110', 'DA701', TO_DATE('2021-10-22','YYYY-MM-DD'))
into PHANCONG values('NV110', 'DA702', TO_DATE('2020-1-14','YYYY-MM-DD'))
into PHANCONG values('NV113', 'DA201', TO_DATE('2020-8-14','YYYY-MM-DD'))
into PHANCONG values('NV116', 'DA501', TO_DATE('2022-9-20','YYYY-MM-DD'))
into PHANCONG values('NV119', 'DA801', TO_DATE('2021-1-26','YYYY-MM-DD'))
into PHANCONG values('NV119', 'DA802', TO_DATE('2021-7-15','YYYY-MM-DD'))
into PHANCONG values('NV122', 'DA301', TO_DATE('2021-3-2','YYYY-MM-DD'))
into PHANCONG values('NV122', 'DA302', TO_DATE('2021-2-16','YYYY-MM-DD'))
into PHANCONG values('NV125', 'DA601', TO_DATE('2021-7-19','YYYY-MM-DD'))
into PHANCONG values('NV128', 'DA101', TO_DATE('2021-10-9','YYYY-MM-DD'))
into PHANCONG values('NV128', 'DA102', TO_DATE('2020-9-24','YYYY-MM-DD'))
into PHANCONG values('NV131', 'DA401', TO_DATE('2022-12-3','YYYY-MM-DD'))
into PHANCONG values('NV134', 'DA701', TO_DATE('2020-5-15','YYYY-MM-DD'))
into PHANCONG values('NV137', 'DA201', TO_DATE('2020-11-3','YYYY-MM-DD'))
into PHANCONG values('NV137', 'DA202', TO_DATE('2022-8-7','YYYY-MM-DD'))
into PHANCONG values('NV140', 'DA501', TO_DATE('2020-9-18','YYYY-MM-DD'))
into PHANCONG values('NV140', 'DA502', TO_DATE('2021-8-3','YYYY-MM-DD'))
into PHANCONG values('NV143', 'DA801', TO_DATE('2020-5-21','YYYY-MM-DD'))
into PHANCONG values('NV143', 'DA802', TO_DATE('2021-10-12','YYYY-MM-DD'))
into PHANCONG values('NV146', 'DA301', TO_DATE('2022-11-21','YYYY-MM-DD'))
into PHANCONG values('NV149', 'DA601', TO_DATE('2020-2-8','YYYY-MM-DD'))
into PHANCONG values('NV149', 'DA602', TO_DATE('2022-5-22','YYYY-MM-DD'))
into PHANCONG values('NV152', 'DA101', TO_DATE('2022-6-20','YYYY-MM-DD'))
into PHANCONG values('NV155', 'DA401', TO_DATE('2020-9-23','YYYY-MM-DD'))
into PHANCONG values('NV155', 'DA402', TO_DATE('2022-4-13','YYYY-MM-DD'))
into PHANCONG values('NV158', 'DA701', TO_DATE('2020-4-16','YYYY-MM-DD'))
into PHANCONG values('NV158', 'DA702', TO_DATE('2021-11-8','YYYY-MM-DD'))
into PHANCONG values('NV161', 'DA201', TO_DATE('2020-4-6','YYYY-MM-DD'))
into PHANCONG values('NV161', 'DA202', TO_DATE('2021-2-16','YYYY-MM-DD'))
into PHANCONG values('NV164', 'DA501', TO_DATE('2022-1-9','YYYY-MM-DD'))
into PHANCONG values('NV167', 'DA801', TO_DATE('2021-2-20','YYYY-MM-DD'))
into PHANCONG values('NV167', 'DA802', TO_DATE('2022-12-16','YYYY-MM-DD'))
into PHANCONG values('NV170', 'DA301', TO_DATE('2021-1-22','YYYY-MM-DD'))
into PHANCONG values('NV170', 'DA302', TO_DATE('2022-4-27','YYYY-MM-DD'))
into PHANCONG values('NV173', 'DA601', TO_DATE('2020-8-27','YYYY-MM-DD'))
into PHANCONG values('NV176', 'DA101', TO_DATE('2020-2-12','YYYY-MM-DD'))
into PHANCONG values('NV176', 'DA102', TO_DATE('2022-7-12','YYYY-MM-DD'))
into PHANCONG values('NV179', 'DA401', TO_DATE('2020-3-11','YYYY-MM-DD'))
into PHANCONG values('NV182', 'DA701', TO_DATE('2022-4-21','YYYY-MM-DD'))
into PHANCONG values('NV185', 'DA201', TO_DATE('2021-10-25','YYYY-MM-DD'))
into PHANCONG values('NV185', 'DA202', TO_DATE('2022-5-12','YYYY-MM-DD'))
into PHANCONG values('NV188', 'DA501', TO_DATE('2022-6-22','YYYY-MM-DD'))
into PHANCONG values('NV188', 'DA502', TO_DATE('2020-1-21','YYYY-MM-DD'))
into PHANCONG values('NV191', 'DA801', TO_DATE('2020-1-6','YYYY-MM-DD'))
into PHANCONG values('NV191', 'DA802', TO_DATE('2022-7-24','YYYY-MM-DD'))
into PHANCONG values('NV194', 'DA301', TO_DATE('2020-3-23','YYYY-MM-DD'))
into PHANCONG values('NV197', 'DA601', TO_DATE('2020-9-5','YYYY-MM-DD'))
into PHANCONG values('NV197', 'DA602', TO_DATE('2020-12-6','YYYY-MM-DD'))
into PHANCONG values('NV200', 'DA101', TO_DATE('2022-9-21','YYYY-MM-DD'))
into PHANCONG values('NV200', 'DA102', TO_DATE('2020-9-17','YYYY-MM-DD'))
into PHANCONG values('NV203', 'DA401', TO_DATE('2022-8-26','YYYY-MM-DD'))
into PHANCONG values('NV203', 'DA402', TO_DATE('2020-3-5','YYYY-MM-DD'))
into PHANCONG values('NV206', 'DA701', TO_DATE('2020-12-26','YYYY-MM-DD'))
into PHANCONG values('NV209', 'DA201', TO_DATE('2020-9-10','YYYY-MM-DD'))
into PHANCONG values('NV212', 'DA501', TO_DATE('2022-1-1','YYYY-MM-DD'))
into PHANCONG values('NV215', 'DA801', TO_DATE('2020-7-9','YYYY-MM-DD'))
into PHANCONG values('NV215', 'DA802', TO_DATE('2022-8-13','YYYY-MM-DD'))
into PHANCONG values('NV218', 'DA301', TO_DATE('2020-12-4','YYYY-MM-DD'))
into PHANCONG values('NV218', 'DA302', TO_DATE('2022-5-27','YYYY-MM-DD'))
into PHANCONG values('NV221', 'DA601', TO_DATE('2021-7-13','YYYY-MM-DD'))
into PHANCONG values('NV224', 'DA101', TO_DATE('2022-2-17','YYYY-MM-DD'))
into PHANCONG values('NV224', 'DA102', TO_DATE('2020-3-5','YYYY-MM-DD'))
into PHANCONG values('NV227', 'DA401', TO_DATE('2021-1-10','YYYY-MM-DD'))
into PHANCONG values('NV230', 'DA701', TO_DATE('2021-10-10','YYYY-MM-DD'))
into PHANCONG values('NV233', 'DA201', TO_DATE('2020-2-28','YYYY-MM-DD'))
into PHANCONG values('NV233', 'DA202', TO_DATE('2021-11-11','YYYY-MM-DD'))
into PHANCONG values('NV236', 'DA501', TO_DATE('2021-9-10','YYYY-MM-DD'))
into PHANCONG values('NV239', 'DA801', TO_DATE('2021-12-26','YYYY-MM-DD'))
into PHANCONG values('NV239', 'DA802', TO_DATE('2021-8-18','YYYY-MM-DD'))
into PHANCONG values('NV242', 'DA301', TO_DATE('2020-2-18','YYYY-MM-DD'))
into PHANCONG values('NV242', 'DA302', TO_DATE('2020-5-8','YYYY-MM-DD'))
into PHANCONG values('NV245', 'DA601', TO_DATE('2022-6-10','YYYY-MM-DD'))
into PHANCONG values('NV248', 'DA101', TO_DATE('2021-4-24','YYYY-MM-DD'))
into PHANCONG values('NV248', 'DA102', TO_DATE('2021-12-8','YYYY-MM-DD'))
into PHANCONG values('NV251', 'DA401', TO_DATE('2022-6-28','YYYY-MM-DD'))
into PHANCONG values('NV254', 'DA701', TO_DATE('2021-6-26','YYYY-MM-DD'))
into PHANCONG values('NV254', 'DA702', TO_DATE('2020-1-22','YYYY-MM-DD'))
into PHANCONG values('NV257', 'DA201', TO_DATE('2020-6-15','YYYY-MM-DD'))
into PHANCONG values('NV257', 'DA202', TO_DATE('2020-5-26','YYYY-MM-DD'))
into PHANCONG values('NV260', 'DA501', TO_DATE('2020-7-19','YYYY-MM-DD'))
into PHANCONG values('NV263', 'DA801', TO_DATE('2022-5-13','YYYY-MM-DD'))
into PHANCONG values('NV266', 'DA301', TO_DATE('2021-1-15','YYYY-MM-DD'))
into PHANCONG values('NV266', 'DA302', TO_DATE('2022-10-19','YYYY-MM-DD'))
into PHANCONG values('NV269', 'DA601', TO_DATE('2021-6-2','YYYY-MM-DD'))
into PHANCONG values('NV269', 'DA602', TO_DATE('2021-2-28','YYYY-MM-DD'))
into PHANCONG values('NV272', 'DA101', TO_DATE('2021-12-10','YYYY-MM-DD'))
into PHANCONG values('NV275', 'DA401', TO_DATE('2020-10-19','YYYY-MM-DD'))
into PHANCONG values('NV275', 'DA402', TO_DATE('2021-2-4','YYYY-MM-DD'))
into PHANCONG values('NV278', 'DA701', TO_DATE('2022-12-3','YYYY-MM-DD'))
into PHANCONG values('NV281', 'DA201', TO_DATE('2022-7-11','YYYY-MM-DD'))
into PHANCONG values('NV284', 'DA501', TO_DATE('2022-6-25','YYYY-MM-DD'))
into PHANCONG values('NV287', 'DA801', TO_DATE('2021-11-25','YYYY-MM-DD'))
into PHANCONG values('NV287', 'DA802', TO_DATE('2022-11-28','YYYY-MM-DD'))
into PHANCONG values('NV290', 'DA301', TO_DATE('2022-11-14','YYYY-MM-DD'))
into PHANCONG values('NV290', 'DA302', TO_DATE('2020-11-17','YYYY-MM-DD'))
into PHANCONG values('NV293', 'DA601', TO_DATE('2022-8-26','YYYY-MM-DD'))
into PHANCONG values('NV296', 'DA101', TO_DATE('2020-2-3','YYYY-MM-DD'))
into PHANCONG values('NV299', 'DA401', TO_DATE('2022-3-28','YYYY-MM-DD'))
into PHANCONG values('NV302', 'DA701', TO_DATE('2021-7-1','YYYY-MM-DD'))
into PHANCONG values('NV302', 'DA702', TO_DATE('2022-6-23','YYYY-MM-DD'))
into PHANCONG values('NV305', 'DA201', TO_DATE('2020-4-26','YYYY-MM-DD'))
into PHANCONG values('NV308', 'DA501', TO_DATE('2022-12-25','YYYY-MM-DD'))
into PHANCONG values('NV311', 'DA801', TO_DATE('2020-4-26','YYYY-MM-DD'))
into PHANCONG values('NV314', 'DA301', TO_DATE('2022-12-13','YYYY-MM-DD'))
into PHANCONG values('NV317', 'DA601', TO_DATE('2020-2-8','YYYY-MM-DD'))
into PHANCONG values('NV320', 'DA101', TO_DATE('2021-4-14','YYYY-MM-DD'))
into PHANCONG values('NV320', 'DA102', TO_DATE('2021-3-25','YYYY-MM-DD'))
into PHANCONG values('NV323', 'DA401', TO_DATE('2020-5-11','YYYY-MM-DD'))
into PHANCONG values('NV326', 'DA701', TO_DATE('2020-6-9','YYYY-MM-DD'))
into PHANCONG values('NV329', 'DA201', TO_DATE('2021-9-20','YYYY-MM-DD'))
into PHANCONG values('NV332', 'DA501', TO_DATE('2021-12-20','YYYY-MM-DD'))
into PHANCONG values('NV332', 'DA502', TO_DATE('2022-8-20','YYYY-MM-DD'))
into PHANCONG values('NV335', 'DA801', TO_DATE('2022-7-4','YYYY-MM-DD'))
into PHANCONG values('NV338', 'DA301', TO_DATE('2020-4-15','YYYY-MM-DD'))
into PHANCONG values('NV341', 'DA601', TO_DATE('2022-10-26','YYYY-MM-DD'))
into PHANCONG values('NV341', 'DA602', TO_DATE('2020-9-12','YYYY-MM-DD'))
into PHANCONG values('NV344', 'DA101', TO_DATE('2022-10-27','YYYY-MM-DD'))
into PHANCONG values('NV344', 'DA102', TO_DATE('2022-9-24','YYYY-MM-DD'))

# Tai khoan

In [11]:
'''
tai khoan:
    username varchar(50),
    password varchar(150),
    MaNV varchar(10)
'''
import random
import string

username = ''
password = ''
MaNV = ''
for i in range(1, 347):
    if i < 6:
        MaNV = '\'GD00'+ str(i) + '\''
        username = f'UserGD00{i}'
    elif i < 11:
        MaNV = '\'TC0'+ str(i) + '\''
        username = f'UserTC0{i}'
    elif i < 16:
        MaNV = '\'NS0'+ str(i) + '\''
        username = f'UserNS0{i}'
    elif i < 36:
        MaNV = '\'QL0'+ str(i) + '\''
        username = f'UserQL0{i}'
    elif i < 39:
        MaNV = '\'TDA0'+ str(i) + '\''
        username = f'UserTDA0{i}'
    elif i < 47:
        MaNV = '\'TP0'+ str(i) + '\''
        username = f'UserTP0{i}'
    else:
        MaNV = '\'NV'+ str(i) + '\''
        username = f'UserNV{i}'
    
    # pass random mac dinh 10 char
    password = ''.join(random.choice(string.ascii_letters) for i in range(10))

    print (f'INSERT INTO TAIKHOAN VALUES(\'{username}\', \'{password}\'. \'{MaNV}\')')

INSERT INTO TAIKHOAN VALUES('UserGD001', 'tzEDjqNvYl'. ''GD001'')
INSERT INTO TAIKHOAN VALUES('UserGD002', 'zpfhHsErnD'. ''GD002'')
INSERT INTO TAIKHOAN VALUES('UserGD003', 'BVYjxEeRPi'. ''GD003'')
INSERT INTO TAIKHOAN VALUES('UserGD004', 'kZCxsEFdrF'. ''GD004'')
INSERT INTO TAIKHOAN VALUES('UserGD005', 'hbsgdRNOFr'. ''GD005'')
INSERT INTO TAIKHOAN VALUES('UserTC06', 'WOtKCrdlMp'. ''TC06'')
INSERT INTO TAIKHOAN VALUES('UserTC07', 'ELhiKNVBnd'. ''TC07'')
INSERT INTO TAIKHOAN VALUES('UserTC08', 'KLQncBPxBT'. ''TC08'')
INSERT INTO TAIKHOAN VALUES('UserTC09', 'RSLSeokbxK'. ''TC09'')
INSERT INTO TAIKHOAN VALUES('UserTC010', 'NvuovJMbyR'. ''TC010'')
INSERT INTO TAIKHOAN VALUES('UserNS011', 'gSOgrlfVaP'. ''NS011'')
INSERT INTO TAIKHOAN VALUES('UserNS012', 'qjOIOJxlUh'. ''NS012'')
INSERT INTO TAIKHOAN VALUES('UserNS013', 'gDaviFRMvW'. ''NS013'')
INSERT INTO TAIKHOAN VALUES('UserNS014', 'yefmjsgwSX'. ''NS014'')
INSERT INTO TAIKHOAN VALUES('UserNS015', 'bSEcIBBHll'. ''NS015'')
INSERT INTO TAIKHOAN VALUES('UserQL016', 'AqNDnfjkoH'. ''QL016'')
INSERT INTO TAIKHOAN VALUES('UserQL017', 'YHsppZvxJQ'. ''QL017'')
INSERT INTO TAIKHOAN VALUES('UserQL018', 'jCEqLXufvv'. ''QL018'')
INSERT INTO TAIKHOAN VALUES('UserQL019', 'CBMOChJJyo'. ''QL019'')
INSERT INTO TAIKHOAN VALUES('UserQL020', 'VjmnWJuiWv'. ''QL020'')
INSERT INTO TAIKHOAN VALUES('UserQL021', 'fYhlfhSLCx'. ''QL021'')
INSERT INTO TAIKHOAN VALUES('UserQL022', 'SLOmTbOMdy'. ''QL022'')
INSERT INTO TAIKHOAN VALUES('UserQL023', 'ftfSvLHZvT'. ''QL023'')
INSERT INTO TAIKHOAN VALUES('UserQL024', 'AguFBnEFGi'. ''QL024'')
INSERT INTO TAIKHOAN VALUES('UserQL025', 'tfaLGVqOzC'. ''QL025'')
INSERT INTO TAIKHOAN VALUES('UserQL026', 'vSjdEcXjmG'. ''QL026'')
INSERT INTO TAIKHOAN VALUES('UserQL027', 'DbJuaEwEWv'. ''QL027'')
INSERT INTO TAIKHOAN VALUES('UserQL028', 'hdnFMALddm'. ''QL028'')
INSERT INTO TAIKHOAN VALUES('UserQL029', 'xGaRttoSMn'. ''QL029'')
INSERT INTO TAIKHOAN VALUES('UserQL030', 'geqJhgDhCr'. ''QL030'')
INSERT INTO TAIKHOAN VALUES('UserQL031', 'kIWCUxhnbn'. ''QL031'')
INSERT INTO TAIKHOAN VALUES('UserQL032', 'ULXFyMzERF'. ''QL032'')
INSERT INTO TAIKHOAN VALUES('UserQL033', 'IEfGPnbTOo'. ''QL033'')
INSERT INTO TAIKHOAN VALUES('UserQL034', 'FfEEkddlFY'. ''QL034'')
INSERT INTO TAIKHOAN VALUES('UserQL035', 'zGwgoMjaMG'. ''QL035'')
INSERT INTO TAIKHOAN VALUES('UserTDA036', 'QuafjLAtey'. ''TDA036'')
INSERT INTO TAIKHOAN VALUES('UserTDA037', 'lKTkKnwXix'. ''TDA037'')
INSERT INTO TAIKHOAN VALUES('UserTDA038', 'FCyEZzEZJf'. ''TDA038'')
INSERT INTO TAIKHOAN VALUES('UserTP039', 'erwhzsDaEe'. ''TP039'')
INSERT INTO TAIKHOAN VALUES('UserTP040', 'VLKFAIOvlc'. ''TP040'')
INSERT INTO TAIKHOAN VALUES('UserTP041', 'tsoMJbYmoj'. ''TP041'')
INSERT INTO TAIKHOAN VALUES('UserTP042', 'kMOvFAKsRi'. ''TP042'')
INSERT INTO TAIKHOAN VALUES('UserTP043', 'RjAFmAJSZE'. ''TP043'')
INSERT INTO TAIKHOAN VALUES('UserTP044', 'lPmqJPaRen'. ''TP044'')
INSERT INTO TAIKHOAN VALUES('UserTP045', 'vditZAiWND'. ''TP045'')
INSERT INTO TAIKHOAN VALUES('UserTP046', 'sbgmbHbdOE'. ''TP046'')
INSERT INTO TAIKHOAN VALUES('UserNV47', 'AADzlvedNU'. ''NV47'')
INSERT INTO TAIKHOAN VALUES('UserNV48', 'fiKAYMOFRD'. ''NV48'')
INSERT INTO TAIKHOAN VALUES('UserNV49', 'IsiLEGMbCH'. ''NV49'')
INSERT INTO TAIKHOAN VALUES('UserNV50', 'NGomUWmVNu'. ''NV50'')
INSERT INTO TAIKHOAN VALUES('UserNV51', 'civooLEooG'. ''NV51'')
INSERT INTO TAIKHOAN VALUES('UserNV52', 'YRvsDVvIfY'. ''NV52'')
INSERT INTO TAIKHOAN VALUES('UserNV53', 'hVmEUEIQCo'. ''NV53'')
INSERT INTO TAIKHOAN VALUES('UserNV54', 'nLGxRTrNpT'. ''NV54'')
INSERT INTO TAIKHOAN VALUES('UserNV55', 'cGVczlBmWt'. ''NV55'')
INSERT INTO TAIKHOAN VALUES('UserNV56', 'OGNjwyhJSr'. ''NV56'')
INSERT INTO TAIKHOAN VALUES('UserNV57', 'FjdIJyofMB'. ''NV57'')
INSERT INTO TAIKHOAN VALUES('UserNV58', 'tgdrZkQRNj'. ''NV58'')
INSERT INTO TAIKHOAN VALUES('UserNV59', 'LRSdTsSCgM'. ''NV59'')
INSERT INTO TAIKHOAN VALUES('UserNV60', 'yfRsLyKlWH'. ''NV60'')
INSERT INTO TAIKHOAN VALUES('UserNV61', 'UIFcuoCkVb'. ''NV61'')
INSERT INTO TAIKHOAN VALUES('UserNV62', 'OKWUjNxoWP'. ''NV62'')
INSERT INTO TAIKHOAN VALUES('UserNV63', 'ZdrqNWlsUl'. ''NV63'')
INSERT INTO TAIKHOAN VALUES('UserNV64', 'pPPyCBqQap'. ''NV64'')
INSERT INTO TAIKHOAN VALUES('UserNV65', 'cJIkuFhjTz'. ''NV65'')
INSERT INTO TAIKHOAN VALUES('UserNV66', 'GKNpKOnVXg'. ''NV66'')
INSERT INTO TAIKHOAN VALUES('UserNV67', 'dPqqaopDEJ'. ''NV67'')
INSERT INTO TAIKHOAN VALUES('UserNV68', 'kwUpbbTBwh'. ''NV68'')
INSERT INTO TAIKHOAN VALUES('UserNV69', 'RsAgsqnBAU'. ''NV69'')
INSERT INTO TAIKHOAN VALUES('UserNV70', 'cGBVSCkblM'. ''NV70'')
INSERT INTO TAIKHOAN VALUES('UserNV71', 'VkJeGonGIw'. ''NV71'')
INSERT INTO TAIKHOAN VALUES('UserNV72', 'GNEJwuHCsY'. ''NV72'')
INSERT INTO TAIKHOAN VALUES('UserNV73', 'PTQOxaFepo'. ''NV73'')
INSERT INTO TAIKHOAN VALUES('UserNV74', 'zHrBRHcXpi'. ''NV74'')
INSERT INTO TAIKHOAN VALUES('UserNV75', 'QMMZMNVJIB'. ''NV75'')
INSERT INTO TAIKHOAN VALUES('UserNV76', 'qQdBaYhuCW'. ''NV76'')
INSERT INTO TAIKHOAN VALUES('UserNV77', 'YFvpNvHkhl'. ''NV77'')
INSERT INTO TAIKHOAN VALUES('UserNV78', 'JhswnSFiVW'. ''NV78'')
INSERT INTO TAIKHOAN VALUES('UserNV79', 'tNhmcYuRBM'. ''NV79'')
INSERT INTO TAIKHOAN VALUES('UserNV80', 'TRwVTVbIwY'. ''NV80'')
INSERT INTO TAIKHOAN VALUES('UserNV81', 'hqCAJaitxh'. ''NV81'')
INSERT INTO TAIKHOAN VALUES('UserNV82', 'XqPRymAtnp'. ''NV82'')
INSERT INTO TAIKHOAN VALUES('UserNV83', 'CBLmdRRUPm'. ''NV83'')
INSERT INTO TAIKHOAN VALUES('UserNV84', 'xKmTuqMisB'. ''NV84'')
INSERT INTO TAIKHOAN VALUES('UserNV85', 'BgYyZpOesR'. ''NV85'')
INSERT INTO TAIKHOAN VALUES('UserNV86', 'AvbdAteiET'. ''NV86'')
INSERT INTO TAIKHOAN VALUES('UserNV87', 'ZqnfLIbHMw'. ''NV87'')
INSERT INTO TAIKHOAN VALUES('UserNV88', 'gdaOLYeasH'. ''NV88'')
INSERT INTO TAIKHOAN VALUES('UserNV89', 'BvjjSIkrTY'. ''NV89'')
INSERT INTO TAIKHOAN VALUES('UserNV90', 'uQfWoWuDvk'. ''NV90'')
INSERT INTO TAIKHOAN VALUES('UserNV91', 'WHTUjkGUQC'. ''NV91'')
INSERT INTO TAIKHOAN VALUES('UserNV92', 'flcUEynNwx'. ''NV92'')
INSERT INTO TAIKHOAN VALUES('UserNV93', 'ECfTLOtNbR'. ''NV93'')
INSERT INTO TAIKHOAN VALUES('UserNV94', 'GSMZBhamso'. ''NV94'')
INSERT INTO TAIKHOAN VALUES('UserNV95', 'xUEzSkVBrh'. ''NV95'')
INSERT INTO TAIKHOAN VALUES('UserNV96', 'sVRIlujaEB'. ''NV96'')
INSERT INTO TAIKHOAN VALUES('UserNV97', 'AWCZToDvBZ'. ''NV97'')
INSERT INTO TAIKHOAN VALUES('UserNV98', 'PVFBOPkaeN'. ''NV98'')
INSERT INTO TAIKHOAN VALUES('UserNV99', 'NgmazUVWVm'. ''NV99'')
INSERT INTO TAIKHOAN VALUES('UserNV100', 'LpvUWnbEgZ'. ''NV100'')
INSERT INTO TAIKHOAN VALUES('UserNV101', 'nTwmGpaCAi'. ''NV101'')
INSERT INTO TAIKHOAN VALUES('UserNV102', 'gPIKvtqiDH'. ''NV102'')
INSERT INTO TAIKHOAN VALUES('UserNV103', 'rxjHHlrgvB'. ''NV103'')
INSERT INTO TAIKHOAN VALUES('UserNV104', 'owmXeAvdUp'. ''NV104'')
INSERT INTO TAIKHOAN VALUES('UserNV105', 'RXduxMqVQv'. ''NV105'')
INSERT INTO TAIKHOAN VALUES('UserNV106', 'WIMclRiHwz'. ''NV106'')
INSERT INTO TAIKHOAN VALUES('UserNV107', 'DUQFlwSbUj'. ''NV107'')
INSERT INTO TAIKHOAN VALUES('UserNV108', 'iwUQFrpIbr'. ''NV108'')
INSERT INTO TAIKHOAN VALUES('UserNV109', 'WnOpCcZyJf'. ''NV109'')
INSERT INTO TAIKHOAN VALUES('UserNV110', 'BBOfwuOwke'. ''NV110'')
INSERT INTO TAIKHOAN VALUES('UserNV111', 'bMNaGutQta'. ''NV111'')
INSERT INTO TAIKHOAN VALUES('UserNV112', 'uZIKPMnCfC'. ''NV112'')
INSERT INTO TAIKHOAN VALUES('UserNV113', 'bhIRzcvXUa'. ''NV113'')
INSERT INTO TAIKHOAN VALUES('UserNV114', 'xtoKSoOXhF'. ''NV114'')
INSERT INTO TAIKHOAN VALUES('UserNV115', 'LeUGfmfJij'. ''NV115'')
INSERT INTO TAIKHOAN VALUES('UserNV116', 'zDHzjNgUhY'. ''NV116'')
INSERT INTO TAIKHOAN VALUES('UserNV117', 'vCUmKpQIEQ'. ''NV117'')
INSERT INTO TAIKHOAN VALUES('UserNV118', 'OqflSYYWFB'. ''NV118'')
INSERT INTO TAIKHOAN VALUES('UserNV119', 'VJUFUZCaly'. ''NV119'')
INSERT INTO TAIKHOAN VALUES('UserNV120', 'wSrtbdmZwz'. ''NV120'')
INSERT INTO TAIKHOAN VALUES('UserNV121', 'BcpJAIQwNM'. ''NV121'')
INSERT INTO TAIKHOAN VALUES('UserNV122', 'iXivbUCVSP'. ''NV122'')
INSERT INTO TAIKHOAN VALUES('UserNV123', 'pejhujlSGq'. ''NV123'')
INSERT INTO TAIKHOAN VALUES('UserNV124', 'FMaxASdXyH'. ''NV124'')
INSERT INTO TAIKHOAN VALUES('UserNV125', 'ZnLKDyVEBY'. ''NV125'')
INSERT INTO TAIKHOAN VALUES('UserNV126', 'EatBHdTvQu'. ''NV126'')
INSERT INTO TAIKHOAN VALUES('UserNV127', 'LybMWrMitr'. ''NV127'')
INSERT INTO TAIKHOAN VALUES('UserNV128', 'TXqaBIlSBs'. ''NV128'')
INSERT INTO TAIKHOAN VALUES('UserNV129', 'vyjVxAziyF'. ''NV129'')
INSERT INTO TAIKHOAN VALUES('UserNV130', 'pnvivsRUwA'. ''NV130'')
INSERT INTO TAIKHOAN VALUES('UserNV131', 'VCpzOdUfdS'. ''NV131'')
INSERT INTO TAIKHOAN VALUES('UserNV132', 'barMnXCExD'. ''NV132'')
INSERT INTO TAIKHOAN VALUES('UserNV133', 'aKbzcdRBMc'. ''NV133'')
INSERT INTO TAIKHOAN VALUES('UserNV134', 'IlIhHcRdib'. ''NV134'')
INSERT INTO TAIKHOAN VALUES('UserNV135', 'kmHCDNpTWd'. ''NV135'')
INSERT INTO TAIKHOAN VALUES('UserNV136', 'nLFPSIPrqi'. ''NV136'')
INSERT INTO TAIKHOAN VALUES('UserNV137', 'SJVZVOjccd'. ''NV137'')
INSERT INTO TAIKHOAN VALUES('UserNV138', 'AwzlwgABIq'. ''NV138'')
INSERT INTO TAIKHOAN VALUES('UserNV139', 'dHFDHqlHmE'. ''NV139'')
INSERT INTO TAIKHOAN VALUES('UserNV140', 'QMziouBCuT'. ''NV140'')
INSERT INTO TAIKHOAN VALUES('UserNV141', 'MDAGRRuAPJ'. ''NV141'')
INSERT INTO TAIKHOAN VALUES('UserNV142', 'FJRZvqXgvL'. ''NV142'')
INSERT INTO TAIKHOAN VALUES('UserNV143', 'opslbcRCYE'. ''NV143'')
INSERT INTO TAIKHOAN VALUES('UserNV144', 'kouhVJdrMK'. ''NV144'')
INSERT INTO TAIKHOAN VALUES('UserNV145', 'TpfHLcFfGu'. ''NV145'')
INSERT INTO TAIKHOAN VALUES('UserNV146', 'GipYTuFLhS'. ''NV146'')
INSERT INTO TAIKHOAN VALUES('UserNV147', 'jMUJgrfEud'. ''NV147'')
INSERT INTO TAIKHOAN VALUES('UserNV148', 'fcFWjCEChy'. ''NV148'')
INSERT INTO TAIKHOAN VALUES('UserNV149', 'fIEtAmpOQw'. ''NV149'')
INSERT INTO TAIKHOAN VALUES('UserNV150', 'UaLPmKYfOX'. ''NV150'')
INSERT INTO TAIKHOAN VALUES('UserNV151', 'xNnqMFoiaV'. ''NV151'')
INSERT INTO TAIKHOAN VALUES('UserNV152', 'YacKAhGaAg'. ''NV152'')
INSERT INTO TAIKHOAN VALUES('UserNV153', 'ExDUYadRlE'. ''NV153'')
INSERT INTO TAIKHOAN VALUES('UserNV154', 'xsbJEtoSFy'. ''NV154'')
INSERT INTO TAIKHOAN VALUES('UserNV155', 'deiIwtvQZD'. ''NV155'')
INSERT INTO TAIKHOAN VALUES('UserNV156', 'KXxzCZqwbx'. ''NV156'')
INSERT INTO TAIKHOAN VALUES('UserNV157', 'qDnHjiYPAo'. ''NV157'')
INSERT INTO TAIKHOAN VALUES('UserNV158', 'AsieGVXaEj'. ''NV158'')
INSERT INTO TAIKHOAN VALUES('UserNV159', 'IKcqEJiyOH'. ''NV159'')
INSERT INTO TAIKHOAN VALUES('UserNV160', 'GqcyjdIyop'. ''NV160'')
INSERT INTO TAIKHOAN VALUES('UserNV161', 'UqzpqUyyQN'. ''NV161'')
INSERT INTO TAIKHOAN VALUES('UserNV162', 'LuYnsBlWVD'. ''NV162'')
INSERT INTO TAIKHOAN VALUES('UserNV163', 'XBIDELVYYz'. ''NV163'')
INSERT INTO TAIKHOAN VALUES('UserNV164', 'RegANMlTwS'. ''NV164'')
INSERT INTO TAIKHOAN VALUES('UserNV165', 'BcMaIhsASg'. ''NV165'')
INSERT INTO TAIKHOAN VALUES('UserNV166', 'ZWrOVyKpdI'. ''NV166'')
INSERT INTO TAIKHOAN VALUES('UserNV167', 'YQmampSFTH'. ''NV167'')
INSERT INTO TAIKHOAN VALUES('UserNV168', 'ECHJstQkQu'. ''NV168'')
INSERT INTO TAIKHOAN VALUES('UserNV169', 'aWATJfYpho'. ''NV169'')
INSERT INTO TAIKHOAN VALUES('UserNV170', 'vpeuMFSKSp'. ''NV170'')
INSERT INTO TAIKHOAN VALUES('UserNV171', 'ckGCAkKFRP'. ''NV171'')
INSERT INTO TAIKHOAN VALUES('UserNV172', 'LaPpAfccjQ'. ''NV172'')
INSERT INTO TAIKHOAN VALUES('UserNV173', 'zovbvxDZIp'. ''NV173'')
INSERT INTO TAIKHOAN VALUES('UserNV174', 'hvOdxtTMCB'. ''NV174'')
INSERT INTO TAIKHOAN VALUES('UserNV175', 'oVLFhzLoZK'. ''NV175'')
INSERT INTO TAIKHOAN VALUES('UserNV176', 'tyfwsjZvXr'. ''NV176'')
INSERT INTO TAIKHOAN VALUES('UserNV177', 'iqqKBAhYlp'. ''NV177'')
INSERT INTO TAIKHOAN VALUES('UserNV178', 'eieabqXuGi'. ''NV178'')
INSERT INTO TAIKHOAN VALUES('UserNV179', 'DrfstQimSg'. ''NV179'')
INSERT INTO TAIKHOAN VALUES('UserNV180', 'LmEiUOYQsu'. ''NV180'')
INSERT INTO TAIKHOAN VALUES('UserNV181', 'UCkWaHJvNf'. ''NV181'')
INSERT INTO TAIKHOAN VALUES('UserNV182', 'TpTTQsWZJK'. ''NV182'')
INSERT INTO TAIKHOAN VALUES('UserNV183', 'jiIPRghWsZ'. ''NV183'')
INSERT INTO TAIKHOAN VALUES('UserNV184', 'nfNHlUaMuZ'. ''NV184'')
INSERT INTO TAIKHOAN VALUES('UserNV185', 'CWoelUNPzO'. ''NV185'')
INSERT INTO TAIKHOAN VALUES('UserNV186', 'mCVnnrFHIR'. ''NV186'')
INSERT INTO TAIKHOAN VALUES('UserNV187', 'teEHJwEoLd'. ''NV187'')
INSERT INTO TAIKHOAN VALUES('UserNV188', 'ENLoGEDPCU'. ''NV188'')
INSERT INTO TAIKHOAN VALUES('UserNV189', 'RhTqcweEwQ'. ''NV189'')
INSERT INTO TAIKHOAN VALUES('UserNV190', 'faQCWdKUua'. ''NV190'')
INSERT INTO TAIKHOAN VALUES('UserNV191', 'iUWuhplNyx'. ''NV191'')
INSERT INTO TAIKHOAN VALUES('UserNV192', 'cRvwDquPlX'. ''NV192'')
INSERT INTO TAIKHOAN VALUES('UserNV193', 'bMcMUiXtit'. ''NV193'')
INSERT INTO TAIKHOAN VALUES('UserNV194', 'HveTumefyG'. ''NV194'')
INSERT INTO TAIKHOAN VALUES('UserNV195', 'geXTJcvLRk'. ''NV195'')
INSERT INTO TAIKHOAN VALUES('UserNV196', 'rtenYfYGKK'. ''NV196'')
INSERT INTO TAIKHOAN VALUES('UserNV197', 'oHAekBtknr'. ''NV197'')
INSERT INTO TAIKHOAN VALUES('UserNV198', 'odVBBVhPFd'. ''NV198'')
INSERT INTO TAIKHOAN VALUES('UserNV199', 'gbdDCsCWcD'. ''NV199'')
INSERT INTO TAIKHOAN VALUES('UserNV200', 'CFPxdCyPHV'. ''NV200'')
INSERT INTO TAIKHOAN VALUES('UserNV201', 'pCLGATMKKg'. ''NV201'')
INSERT INTO TAIKHOAN VALUES('UserNV202', 'WSijYwOsLg'. ''NV202'')
INSERT INTO TAIKHOAN VALUES('UserNV203', 'cwzsGhCKpr'. ''NV203'')
INSERT INTO TAIKHOAN VALUES('UserNV204', 'KxJzgPzVTx'. ''NV204'')
INSERT INTO TAIKHOAN VALUES('UserNV205', 'EySNCFFodx'. ''NV205'')
INSERT INTO TAIKHOAN VALUES('UserNV206', 'EydBFLgMlQ'. ''NV206'')
INSERT INTO TAIKHOAN VALUES('UserNV207', 'WpsvygaQYF'. ''NV207'')
INSERT INTO TAIKHOAN VALUES('UserNV208', 'QKJqqhbsya'. ''NV208'')
INSERT INTO TAIKHOAN VALUES('UserNV209', 'HzbBCtMCyX'. ''NV209'')
INSERT INTO TAIKHOAN VALUES('UserNV210', 'mvOEspdlTY'. ''NV210'')
INSERT INTO TAIKHOAN VALUES('UserNV211', 'vlUQYTdEeU'. ''NV211'')
INSERT INTO TAIKHOAN VALUES('UserNV212', 'ItgseMqGQC'. ''NV212'')
INSERT INTO TAIKHOAN VALUES('UserNV213', 'blnvFQaVet'. ''NV213'')
INSERT INTO TAIKHOAN VALUES('UserNV214', 'qDWVdqsTrg'. ''NV214'')
INSERT INTO TAIKHOAN VALUES('UserNV215', 'pUTymdiwZC'. ''NV215'')
INSERT INTO TAIKHOAN VALUES('UserNV216', 'gEzxvUjqew'. ''NV216'')
INSERT INTO TAIKHOAN VALUES('UserNV217', 'vosPdqcKYS'. ''NV217'')
INSERT INTO TAIKHOAN VALUES('UserNV218', 'oylRwxrckO'. ''NV218'')
INSERT INTO TAIKHOAN VALUES('UserNV219', 'eCDQCBTGRq'. ''NV219'')
INSERT INTO TAIKHOAN VALUES('UserNV220', 'SuFWTHtLhU'. ''NV220'')
INSERT INTO TAIKHOAN VALUES('UserNV221', 'BfcwfkBMiI'. ''NV221'')
INSERT INTO TAIKHOAN VALUES('UserNV222', 'dewNmDIUCn'. ''NV222'')
INSERT INTO TAIKHOAN VALUES('UserNV223', 'lbxJjwdTyY'. ''NV223'')
INSERT INTO TAIKHOAN VALUES('UserNV224', 'YgEfGZpLRA'. ''NV224'')
INSERT INTO TAIKHOAN VALUES('UserNV225', 'rawUGjuajy'. ''NV225'')
INSERT INTO TAIKHOAN VALUES('UserNV226', 'IFLLMFqxPk'. ''NV226'')
INSERT INTO TAIKHOAN VALUES('UserNV227', 'VyOWKonGnB'. ''NV227'')
INSERT INTO TAIKHOAN VALUES('UserNV228', 'mQWTQKYBAl'. ''NV228'')
INSERT INTO TAIKHOAN VALUES('UserNV229', 'tqFNJlviga'. ''NV229'')
INSERT INTO TAIKHOAN VALUES('UserNV230', 'TArxEKcSDM'. ''NV230'')
INSERT INTO TAIKHOAN VALUES('UserNV231', 'zXXjxZTHiY'. ''NV231'')
INSERT INTO TAIKHOAN VALUES('UserNV232', 'WTzoiJSVBA'. ''NV232'')
INSERT INTO TAIKHOAN VALUES('UserNV233', 'dlqCzmcOHW'. ''NV233'')
INSERT INTO TAIKHOAN VALUES('UserNV234', 'OYDdqDKiTp'. ''NV234'')
INSERT INTO TAIKHOAN VALUES('UserNV235', 'UMgEVkqNWQ'. ''NV235'')
INSERT INTO TAIKHOAN VALUES('UserNV236', 'MlJfgyRaUa'. ''NV236'')
INSERT INTO TAIKHOAN VALUES('UserNV237', 'TDVAjuHjNy'. ''NV237'')
INSERT INTO TAIKHOAN VALUES('UserNV238', 'zrQIFVEcko'. ''NV238'')
INSERT INTO TAIKHOAN VALUES('UserNV239', 'GvADRZHTzW'. ''NV239'')
INSERT INTO TAIKHOAN VALUES('UserNV240', 'pNmJpuhnPO'. ''NV240'')
INSERT INTO TAIKHOAN VALUES('UserNV241', 'PVniAitVDh'. ''NV241'')
INSERT INTO TAIKHOAN VALUES('UserNV242', 'JmSDstoibK'. ''NV242'')
INSERT INTO TAIKHOAN VALUES('UserNV243', 'uMZWyaWeVb'. ''NV243'')
INSERT INTO TAIKHOAN VALUES('UserNV244', 'tcUJSVGNyi'. ''NV244'')
INSERT INTO TAIKHOAN VALUES('UserNV245', 'sEIMTNKdHE'. ''NV245'')
INSERT INTO TAIKHOAN VALUES('UserNV246', 'ToFOLjmCvk'. ''NV246'')
INSERT INTO TAIKHOAN VALUES('UserNV247', 'wOzBigUWue'. ''NV247'')
INSERT INTO TAIKHOAN VALUES('UserNV248', 'NVojJliPaq'. ''NV248'')
INSERT INTO TAIKHOAN VALUES('UserNV249', 'bJIaacuRbE'. ''NV249'')
INSERT INTO TAIKHOAN VALUES('UserNV250', 'MKRlUaCBAX'. ''NV250'')
INSERT INTO TAIKHOAN VALUES('UserNV251', 'AInTzOUcsD'. ''NV251'')
INSERT INTO TAIKHOAN VALUES('UserNV252', 'bfjuQDadYL'. ''NV252'')
INSERT INTO TAIKHOAN VALUES('UserNV253', 'WooSrCcCZJ'. ''NV253'')
INSERT INTO TAIKHOAN VALUES('UserNV254', 'hqgwXvzxGM'. ''NV254'')
INSERT INTO TAIKHOAN VALUES('UserNV255', 'cCBeDryukA'. ''NV255'')
INSERT INTO TAIKHOAN VALUES('UserNV256', 'tTLzZUVyRa'. ''NV256'')
INSERT INTO TAIKHOAN VALUES('UserNV257', 'QKUsBNcsXF'. ''NV257'')
INSERT INTO TAIKHOAN VALUES('UserNV258', 'DdvWXIefHL'. ''NV258'')
INSERT INTO TAIKHOAN VALUES('UserNV259', 'rIvWgqsYsY'. ''NV259'')
INSERT INTO TAIKHOAN VALUES('UserNV260', 'QElmiAEZTd'. ''NV260'')
INSERT INTO TAIKHOAN VALUES('UserNV261', 'YqpNPwNpLz'. ''NV261'')
INSERT INTO TAIKHOAN VALUES('UserNV262', 'JfDMnvtnIk'. ''NV262'')
INSERT INTO TAIKHOAN VALUES('UserNV263', 'HDUUJFFVrK'. ''NV263'')
INSERT INTO TAIKHOAN VALUES('UserNV264', 'vRxaejyzqF'. ''NV264'')
INSERT INTO TAIKHOAN VALUES('UserNV265', 'mzbefQqBKB'. ''NV265'')
INSERT INTO TAIKHOAN VALUES('UserNV266', 'GgRrVbfsjt'. ''NV266'')
INSERT INTO TAIKHOAN VALUES('UserNV267', 'CnGvLNUTXG'. ''NV267'')
INSERT INTO TAIKHOAN VALUES('UserNV268', 'OwKlIvXvcd'. ''NV268'')
INSERT INTO TAIKHOAN VALUES('UserNV269', 'jtICjeIhGy'. ''NV269'')
INSERT INTO TAIKHOAN VALUES('UserNV270', 'lKHdQpytAQ'. ''NV270'')
INSERT INTO TAIKHOAN VALUES('UserNV271', 'sjfadSiBKR'. ''NV271'')
INSERT INTO TAIKHOAN VALUES('UserNV272', 'TrumKIrbcN'. ''NV272'')
INSERT INTO TAIKHOAN VALUES('UserNV273', 'wpipWncyUN'. ''NV273'')
INSERT INTO TAIKHOAN VALUES('UserNV274', 'NKUbjqwIot'. ''NV274'')
INSERT INTO TAIKHOAN VALUES('UserNV275', 'mruANocVMx'. ''NV275'')
INSERT INTO TAIKHOAN VALUES('UserNV276', 'EhtOfRZiVj'. ''NV276'')
INSERT INTO TAIKHOAN VALUES('UserNV277', 'ruLgfhObfF'. ''NV277'')
INSERT INTO TAIKHOAN VALUES('UserNV278', 'gcmmPROoSl'. ''NV278'')
INSERT INTO TAIKHOAN VALUES('UserNV279', 'lLPtjoCRnt'. ''NV279'')
INSERT INTO TAIKHOAN VALUES('UserNV280', 'sTgqlliuCv'. ''NV280'')
INSERT INTO TAIKHOAN VALUES('UserNV281', 'omZeuRNwgC'. ''NV281'')
INSERT INTO TAIKHOAN VALUES('UserNV282', 'BadSGTwyXw'. ''NV282'')
INSERT INTO TAIKHOAN VALUES('UserNV283', 'uxsnppJTEY'. ''NV283'')
INSERT INTO TAIKHOAN VALUES('UserNV284', 'QknpZpZWJy'. ''NV284'')
INSERT INTO TAIKHOAN VALUES('UserNV285', 'kaGaBrKeEp'. ''NV285'')
INSERT INTO TAIKHOAN VALUES('UserNV286', 'EandpFQhVr'. ''NV286'')
INSERT INTO TAIKHOAN VALUES('UserNV287', 'HLWmnKzBtJ'. ''NV287'')
INSERT INTO TAIKHOAN VALUES('UserNV288', 'tTsHngmrij'. ''NV288'')
INSERT INTO TAIKHOAN VALUES('UserNV289', 'eXkqcOEVrN'. ''NV289'')
INSERT INTO TAIKHOAN VALUES('UserNV290', 'hOwXNXECRC'. ''NV290'')
INSERT INTO TAIKHOAN VALUES('UserNV291', 'IVmMKarqYd'. ''NV291'')
INSERT INTO TAIKHOAN VALUES('UserNV292', 'NCBzRROwDy'. ''NV292'')
INSERT INTO TAIKHOAN VALUES('UserNV293', 'eJZnTUrZOG'. ''NV293'')
INSERT INTO TAIKHOAN VALUES('UserNV294', 'ziWeovYBIw'. ''NV294'')
INSERT INTO TAIKHOAN VALUES('UserNV295', 'plLSynBget'. ''NV295'')
INSERT INTO TAIKHOAN VALUES('UserNV296', 'NFrxIphXuf'. ''NV296'')
INSERT INTO TAIKHOAN VALUES('UserNV297', 'QbMGOqRzWB'. ''NV297'')
INSERT INTO TAIKHOAN VALUES('UserNV298', 'tUxxAfuvAF'. ''NV298'')
INSERT INTO TAIKHOAN VALUES('UserNV299', 'WpNHXAtKkE'. ''NV299'')
INSERT INTO TAIKHOAN VALUES('UserNV300', 'LxajCnhMFp'. ''NV300'')
INSERT INTO TAIKHOAN VALUES('UserNV301', 'mHPkJoxgQe'. ''NV301'')
INSERT INTO TAIKHOAN VALUES('UserNV302', 'vZSUYxkSbH'. ''NV302'')
INSERT INTO TAIKHOAN VALUES('UserNV303', 'ryQnklpvZL'. ''NV303'')
INSERT INTO TAIKHOAN VALUES('UserNV304', 'AuBTMFaVwi'. ''NV304'')