In [2]:
import random as rd

insert = "insert into table "

In [3]:
Ho = [ 'Ho','Bui', 'Đoan', 'Le', 'Nguyen', 'Duong', 'Tran', 'Ly', 'Vu', 'Vo', 'Đang', 'Pham', 'Ung', 'An', 'Au','Truong', 'Lai', 'Gian' ]
tendem = ['Van','Thi','Chi','Gia','Hoang', 'Song', 'Tung' ]
ten = ['Ngoc Nhi','An','Anh','Bac','Bao','Cau','Cuc','Đan','Đang','Đuc','Thong','Tien','Tuan','Tin','Tiep','Viet','Vinh','Vu','Vy','Minh','Giang','khanh','Sang','Duy','Chi','Thuong','Chung','Phu','Quoc','Nam','Ngan','Nguyet','May' 
       ,'Tu','Thien','Tan','Han']

In [5]:
'''
NhanVien (
	MaNV 		varchar(10) primary key,
	TenNV 	varchar2(60) not null,
	Phai 		varchar2(4),
	NgaySinh 	date,
	DiaChi 	varchar2(100),
	SoDT 		varchar(10) not null unique,
	Luong 	number,
	PhuCap 	number,
	VaiTro 	varchar2(50),
	MaNQL 	varchar(10),
	PHG 		number
	
)
go
'''
'''
Nhân viên - 300
Quản lí - 20
Trưởng phòng - 8
Tài chính - 5
Nhân sự - 5
Trưởng đề án - 3
Ban giám đốc - 5
'''
sex = ['Nam', 'Nu']
import string

username = ''
MaNV = ''
TenNV = ''
Phai = ''
NgaySinh = ''
DiaChi 	= ''
SoDT 	= ''
Luong 	= 0
PhuCap 	= 0
VaiTro 	= ''
MaNQL 	= 'NULL'
PHG 	= 0
for i in range(1, 347):
    Luong = rd.randint(1000, 9999)
    PhuCap = rd.randint(1000, 2000)
    PHG = i % 8 + 1
    if i < 6:
        MaNV = '\'GD00'+ str(i) + '\''
        VaiTro 	= '\'Ban giam doc\''
        Luong = 55555
    elif i < 11:
        MaNV = '\'TC0'+ str(i) + '\''
        VaiTro 	= '\'Tai chinh\''
        Luong = 11000
    elif i < 16:
        MaNV = '\'NS0'+ str(i) + '\''
        VaiTro 	= '\'Nhan su\''
        Luong = 13000
    elif i < 36:
        MaNV = '\'QL0'+ str(i) + '\''
        VaiTro 	= '\'Quan li\''
        Luong = 25000
    elif i < 39:
        MaNV = '\'TDA0'+ str(i) + '\''
        VaiTro 	= '\'Truong de an\''
        Luong = 20000
    elif i < 47:
        MaNV = '\'TP0'+ str(i) + '\''
        VaiTro 	= '\'Truong phong\''
        Luong = 22000
        PHG = i - 38
    else:
        MaNV = '\'NV'+ str(i) + '\''
        VaiTro 	= '\'Nhan vien\''
        MaNQL = '\'QL0'+ str((i-47)% 20 + 16) + '\'' #16-35
    
    account_suffix = MaNV.replace("'", "")
    username = f'\'User{account_suffix}\''
    

    SoDT = '\'0945000' + str(i) + '\''
    tenD = rd.choice(tendem);
    TenNV = '\'' + rd.choice(Ho) + ' ' + tenD + ' ' + rd.choice(ten) + '\''
    DiaChi = '\'227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh\'' 
    Phai = '\'Nam\''
    if (tenD == 'Thi' or tenD == 'Song'):
        Phai = '\'Nu\''
    NgaySinh  = 'TO_DATE(' + '\'' + str(rd.randint(2000, 2022)) + '-' + str(rd.randint(1, 12)) + '-' + str(rd.randint(1, 28)) + '\',\'YYYY-MM-DD\')'
    
    final = MaNV + ', ' + TenNV + ', ' + Phai + ', ' + NgaySinh + ', ' + DiaChi +', ' + SoDT + ', ' + str(Luong) + ', ' + str(PhuCap) +', '+ VaiTro + ', ' + MaNQL + ', ' + str(PHG) + ', ' + username
    
    print (' into NHANVIEN values(' +  final + ')')
    
   # print('insert into TaiKhoan values(' + TenTaiKhoan + HoTen + str(Mk) + sdt + DiaChi + Email + LoaiTaiKhoan +')')

 into NHANVIEN values('GD001', 'Vu Van Chung', 'Nam', TO_DATE('2016-8-4','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450001', 55555, 1569, 'Ban giam doc', NULL, 2, 'UserGD001')
 into NHANVIEN values('GD002', 'Au Van Thien', 'Nam', TO_DATE('2015-12-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450002', 55555, 1216, 'Ban giam doc', NULL, 3, 'UserGD002')
 into NHANVIEN values('GD003', 'Vu Hoang Cuc', 'Nam', TO_DATE('2017-6-9','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450003', 55555, 1438, 'Ban giam doc', NULL, 4, 'UserGD003')
 into NHANVIEN values('GD004', 'Duong Song Cuc', 'Nu', TO_DATE('2002-8-9','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450004', 55555, 1532, 'Ban giam doc', NULL, 5, 'UserGD004')
 into NHANVIEN values('GD005', 'Gian Chi Thong', 'Nam', TO_DATE('2010-10-3','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450005', 55555, 1360, 'Ban giam doc', NULL, 6, 'UserGD005')
 into NHANVIEN values('TC06', 'Ung Tung Quoc', 'Nam', TO_DATE('2018-1-16','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450006', 11000, 1828, 'Tai chinh', NULL, 7, 'UserTC06')
 into NHANVIEN values('TC07', 'An Song May', 'Nu', TO_DATE('2019-12-16','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450007', 11000, 1788, 'Tai chinh', NULL, 8, 'UserTC07')
 into NHANVIEN values('TC08', 'Ho Chi Tin', 'Nam', TO_DATE('2004-7-18','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450008', 11000, 1056, 'Tai chinh', NULL, 1, 'UserTC08')
 into NHANVIEN values('TC09', 'Lai Gia Tuan', 'Nam', TO_DATE('2011-3-17','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '09450009', 11000, 1039, 'Tai chinh', NULL, 2, 'UserTC09')
 into NHANVIEN values('TC010', 'Tran Gia Minh', 'Nam', TO_DATE('2009-6-6','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500010', 11000, 1699, 'Tai chinh', NULL, 3, 'UserTC010')
 into NHANVIEN values('NS011', 'Ly Chi Ngan', 'Nam', TO_DATE('2003-11-13','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500011', 13000, 1513, 'Nhan su', NULL, 4, 'UserNS011')
 into NHANVIEN values('NS012', 'Vu Song Minh', 'Nu', TO_DATE('2014-6-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500012', 13000, 1318, 'Nhan su', NULL, 5, 'UserNS012')
 into NHANVIEN values('NS013', 'Au Chi Tien', 'Nam', TO_DATE('2015-4-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500013', 13000, 1763, 'Nhan su', NULL, 6, 'UserNS013')
 into NHANVIEN values('NS014', 'Duong Chi Phu', 'Nam', TO_DATE('2002-9-20','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500014', 13000, 1921, 'Nhan su', NULL, 7, 'UserNS014')
 into NHANVIEN values('NS015', 'Bui Van Đang', 'Nam', TO_DATE('2007-3-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500015', 13000, 1368, 'Nhan su', NULL, 8, 'UserNS015')
 into NHANVIEN values('QL016', 'Đang Thi Anh', 'Nu', TO_DATE('2002-7-22','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500016', 25000, 1760, 'Quan li', NULL, 1, 'UserQL016')
 into NHANVIEN values('QL017', 'Duong Gia Chung', 'Nam', TO_DATE('2002-5-28','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500017', 25000, 1000, 'Quan li', NULL, 2, 'UserQL017')
 into NHANVIEN values('QL018', 'Truong Gia Nguyet', 'Nam', TO_DATE('2008-2-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500018', 25000, 1476, 'Quan li', NULL, 3, 'UserQL018')
 into NHANVIEN values('QL019', 'Duong Hoang khanh', 'Nam', TO_DATE('2015-3-14','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500019', 25000, 1709, 'Quan li', NULL, 4, 'UserQL019')
 into NHANVIEN values('QL020', 'Duong Song Tu', 'Nu', TO_DATE('2019-12-17','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500020', 25000, 1053, 'Quan li', NULL, 5, 'UserQL020')
 into NHANVIEN values('QL021', 'Nguyen Song Viet', 'Nu', TO_DATE('2010-5-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500021', 25000, 1322, 'Quan li', NULL, 6, 'UserQL021')
 into NHANVIEN values('QL022', 'Ung Chi Tuan', 'Nam', TO_DATE('2017-9-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500022', 25000, 1877, 'Quan li', NULL, 7, 'UserQL022')
 into NHANVIEN values('QL023', 'An Van Cuc', 'Nam', TO_DATE('2003-11-24','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500023', 25000, 1608, 'Quan li', NULL, 8, 'UserQL023')
 into NHANVIEN values('QL024', 'Lai Chi Tien', 'Nam', TO_DATE('2020-5-17','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500024', 25000, 1568, 'Quan li', NULL, 1, 'UserQL024')
 into NHANVIEN values('QL025', 'Nguyen Tung khanh', 'Nam', TO_DATE('2000-4-24','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500025', 25000, 1475, 'Quan li', NULL, 2, 'UserQL025')
 into NHANVIEN values('QL026', 'Đoan Song Bao', 'Nu', TO_DATE('2006-3-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500026', 25000, 1170, 'Quan li', NULL, 3, 'UserQL026')
 into NHANVIEN values('QL027', 'Vo Gia Anh', 'Nam', TO_DATE('2012-10-10','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500027', 25000, 1794, 'Quan li', NULL, 4, 'UserQL027')
 into NHANVIEN values('QL028', 'Duong Chi Chung', 'Nam', TO_DATE('2002-10-28','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500028', 25000, 1490, 'Quan li', NULL, 5, 'UserQL028')
 into NHANVIEN values('QL029', 'Vo Chi Duy', 'Nam', TO_DATE('2013-11-27','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500029', 25000, 1227, 'Quan li', NULL, 6, 'UserQL029')
 into NHANVIEN values('QL030', 'Gian Hoang Tien', 'Nam', TO_DATE('2001-6-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500030', 25000, 1189, 'Quan li', NULL, 7, 'UserQL030')
 into NHANVIEN values('QL031', 'Ly Van Vinh', 'Nam', TO_DATE('2001-3-4','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500031', 25000, 1042, 'Quan li', NULL, 8, 'UserQL031')
 into NHANVIEN values('QL032', 'Ho Hoang Chung', 'Nam', TO_DATE('2022-11-10','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500032', 25000, 1623, 'Quan li', NULL, 1, 'UserQL032')
 into NHANVIEN values('QL033', 'Bui Song May', 'Nu', TO_DATE('2022-4-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500033', 25000, 1892, 'Quan li', NULL, 2, 'UserQL033')
 into NHANVIEN values('QL034', 'Pham Van Phu', 'Nam', TO_DATE('2014-9-27','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500034', 25000, 1922, 'Quan li', NULL, 3, 'UserQL034')
 into NHANVIEN values('QL035', 'Đoan Tung Thien', 'Nam', TO_DATE('2003-10-9','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500035', 25000, 1757, 'Quan li', NULL, 4, 'UserQL035')
 into NHANVIEN values('TDA036', 'Pham Song Phu', 'Nu', TO_DATE('2006-10-23','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500036', 20000, 1072, 'Truong de an', NULL, 5, 'UserTDA036')
 into NHANVIEN values('TDA037', 'Duong Song Bac', 'Nu', TO_DATE('2018-7-14','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500037', 20000, 1633, 'Truong de an', NULL, 6, 'UserTDA037')
 into NHANVIEN values('TDA038', 'Le Hoang Viet', 'Nam', TO_DATE('2013-8-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500038', 20000, 1343, 'Truong de an', NULL, 7, 'UserTDA038')
 into NHANVIEN values('TP039', 'Ly Hoang Thien', 'Nam', TO_DATE('2015-2-3','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500039', 22000, 1000, 'Truong phong', NULL, 1, 'UserTP039')
 into NHANVIEN values('TP040', 'Truong Van Nguyet', 'Nam', TO_DATE('2019-1-27','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500040', 22000, 1537, 'Truong phong', NULL, 2, 'UserTP040')
 into NHANVIEN values('TP041', 'Đang Gia An', 'Nam', TO_DATE('2005-6-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500041', 22000, 1688, 'Truong phong', NULL, 3, 'UserTP041')
 into NHANVIEN values('TP042', 'Bui Hoang Anh', 'Nam', TO_DATE('2005-12-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500042', 22000, 1545, 'Truong phong', NULL, 4, 'UserTP042')
 into NHANVIEN values('TP043', 'Le Chi Chung', 'Nam', TO_DATE('2017-1-20','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500043', 22000, 1862, 'Truong phong', NULL, 5, 'UserTP043')
 into NHANVIEN values('TP044', 'Le Thi Duy', 'Nu', TO_DATE('2003-12-25','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500044', 22000, 1281, 'Truong phong', NULL, 6, 'UserTP044')
 into NHANVIEN values('TP045', 'Gian Thi Tuan', 'Nu', TO_DATE('2004-12-28','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500045', 22000, 1022, 'Truong phong', NULL, 7, 'UserTP045')
 into NHANVIEN values('TP046', 'Lai Song Tiep', 'Nu', TO_DATE('2016-11-12','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500046', 22000, 1918, 'Truong phong', NULL, 8, 'UserTP046')
 into NHANVIEN values('NV47', 'Vu Chi Vinh', 'Nam', TO_DATE('2010-10-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500047', 3380, 1168, 'Nhan vien', 'QL016', 8, 'UserNV47')
 into NHANVIEN values('NV48', 'Nguyen Hoang Quoc', 'Nam', TO_DATE('2011-1-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500048', 5929, 1930, 'Nhan vien', 'QL017', 1, 'UserNV48')
 into NHANVIEN values('NV49', 'Truong Van Bao', 'Nam', TO_DATE('2017-9-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500049', 6696, 1140, 'Nhan vien', 'QL018', 2, 'UserNV49')
 into NHANVIEN values('NV50', 'Truong Tung Sang', 'Nam', TO_DATE('2001-10-28','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500050', 9394, 1545, 'Nhan vien', 'QL019', 3, 'UserNV50')
 into NHANVIEN values('NV51', 'Tran Song Tuan', 'Nu', TO_DATE('2022-12-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500051', 8062, 1892, 'Nhan vien', 'QL020', 4, 'UserNV51')
 into NHANVIEN values('NV52', 'Pham Tung Thong', 'Nam', TO_DATE('2014-6-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500052', 2440, 1189, 'Nhan vien', 'QL021', 5, 'UserNV52')
 into NHANVIEN values('NV53', 'Ung Hoang Phu', 'Nam', TO_DATE('2010-11-27','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500053', 1797, 1303, 'Nhan vien', 'QL022', 6, 'UserNV53')
 into NHANVIEN values('NV54', 'Ung Gia Đang', 'Nam', TO_DATE('2012-11-25','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500054', 2287, 1106, 'Nhan vien', 'QL023', 7, 'UserNV54')
 into NHANVIEN values('NV55', 'Ly Hoang Cuc', 'Nam', TO_DATE('2004-2-12','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500055', 7807, 1332, 'Nhan vien', 'QL024', 8, 'UserNV55')
 into NHANVIEN values('NV56', 'Duong Thi Thuong', 'Nu', TO_DATE('2002-2-10','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500056', 1947, 1119, 'Nhan vien', 'QL025', 1, 'UserNV56')
 into NHANVIEN values('NV57', 'Đang Hoang Tien', 'Nam', TO_DATE('2014-12-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500057', 3175, 1969, 'Nhan vien', 'QL026', 2, 'UserNV57')
 into NHANVIEN values('NV58', 'Vo Van Vy', 'Nam', TO_DATE('2001-12-11','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500058', 1731, 1801, 'Nhan vien', 'QL027', 3, 'UserNV58')
 into NHANVIEN values('NV59', 'Vo Hoang Bao', 'Nam', TO_DATE('2020-5-25','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500059', 8898, 1606, 'Nhan vien', 'QL028', 4, 'UserNV59')
 into NHANVIEN values('NV60', 'Đang Van Ngoc Nhi', 'Nam', TO_DATE('2019-9-21','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500060', 2927, 1861, 'Nhan vien', 'QL029', 5, 'UserNV60')
 into NHANVIEN values('NV61', 'Tran Tung Sang', 'Nam', TO_DATE('2003-3-18','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500061', 6074, 1444, 'Nhan vien', 'QL030', 6, 'UserNV61')
 into NHANVIEN values('NV62', 'Ung Tung Quoc', 'Nam', TO_DATE('2010-7-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500062', 2001, 1523, 'Nhan vien', 'QL031', 7, 'UserNV62')
 into NHANVIEN values('NV63', 'Pham Thi Sang', 'Nu', TO_DATE('2003-3-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500063', 4323, 1915, 'Nhan vien', 'QL032', 8, 'UserNV63')
 into NHANVIEN values('NV64', 'Nguyen Song Chung', 'Nu', TO_DATE('2019-7-24','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500064', 5748, 1033, 'Nhan vien', 'QL033', 1, 'UserNV64')
 into NHANVIEN values('NV65', 'Duong Chi Nam', 'Nam', TO_DATE('2004-11-16','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500065', 4598, 1683, 'Nhan vien', 'QL034', 2, 'UserNV65')
 into NHANVIEN values('NV66', 'Ung Song Ngoc Nhi', 'Nu', TO_DATE('2003-9-3','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500066', 4714, 1981, 'Nhan vien', 'QL035', 3, 'UserNV66')
 into NHANVIEN values('NV67', 'Truong Chi Ngoc Nhi', 'Nam', TO_DATE('2003-1-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500067', 3428, 1592, 'Nhan vien', 'QL016', 4, 'UserNV67')
 into NHANVIEN values('NV68', 'Đang Van Chung', 'Nam', TO_DATE('2020-5-6','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500068', 6822, 1436, 'Nhan vien', 'QL017', 5, 'UserNV68')
 into NHANVIEN values('NV69', 'Vu Gia Nguyet', 'Nam', TO_DATE('2008-7-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500069', 8724, 1411, 'Nhan vien', 'QL018', 6, 'UserNV69')
 into NHANVIEN values('NV70', 'Vo Chi Giang', 'Nam', TO_DATE('2003-12-18','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500070', 2567, 1449, 'Nhan vien', 'QL019', 7, 'UserNV70')
 into NHANVIEN values('NV71', 'Vu Van Nguyet', 'Nam', TO_DATE('2010-7-5','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500071', 1699, 1878, 'Nhan vien', 'QL020', 8, 'UserNV71')
 into NHANVIEN values('NV72', 'Gian Tung Ngoc Nhi', 'Nam', TO_DATE('2000-5-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500072', 3226, 1297, 'Nhan vien', 'QL021', 1, 'UserNV72')
 into NHANVIEN values('NV73', 'Truong Song Vy', 'Nu', TO_DATE('2015-7-4','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500073', 6566, 1561, 'Nhan vien', 'QL022', 2, 'UserNV73')
 into NHANVIEN values('NV74', 'Ung Song Chi', 'Nu', TO_DATE('2003-3-1','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500074', 7832, 1874, 'Nhan vien', 'QL023', 3, 'UserNV74')
 into NHANVIEN values('NV75', 'Ho Van Vinh', 'Nam', TO_DATE('2015-8-19','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500075', 4615, 1673, 'Nhan vien', 'QL024', 4, 'UserNV75')
 into NHANVIEN values('NV76', 'Nguyen Hoang Tin', 'Nam', TO_DATE('2018-8-4','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500076', 5410, 1614, 'Nhan vien', 'QL025', 5, 'UserNV76')
 into NHANVIEN values('NV77', 'Lai Hoang Ngoc Nhi', 'Nam', TO_DATE('2013-7-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500077', 4223, 1591, 'Nhan vien', 'QL026', 6, 'UserNV77')
 into NHANVIEN values('NV78', 'Ung Van Nguyet', 'Nam', TO_DATE('2001-9-23','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500078', 9897, 1390, 'Nhan vien', 'QL027', 7, 'UserNV78')
 into NHANVIEN values('NV79', 'Tran Tung Tu', 'Nam', TO_DATE('2003-1-24','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500079', 4827, 1930, 'Nhan vien', 'QL028', 8, 'UserNV79')
 into NHANVIEN values('NV80', 'Ung Hoang Vinh', 'Nam', TO_DATE('2009-12-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500080', 2459, 1400, 'Nhan vien', 'QL029', 1, 'UserNV80')
 into NHANVIEN values('NV81', 'Lai Song Vinh', 'Nu', TO_DATE('2022-2-16','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500081', 6957, 1680, 'Nhan vien', 'QL030', 2, 'UserNV81')
 into NHANVIEN values('NV82', 'Le Song Ngoc Nhi', 'Nu', TO_DATE('2022-6-16','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500082', 8755, 1188, 'Nhan vien', 'QL031', 3, 'UserNV82')
 into NHANVIEN values('NV83', 'Ly Chi Tin', 'Nam', TO_DATE('2001-8-15','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500083', 6005, 1944, 'Nhan vien', 'QL032', 4, 'UserNV83')
 into NHANVIEN values('NV84', 'Nguyen Thi Phu', 'Nu', TO_DATE('2022-5-22','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500084', 1107, 1758, 'Nhan vien', 'QL033', 5, 'UserNV84')
 into NHANVIEN values('NV85', 'Au Thi Chi', 'Nu', TO_DATE('2021-7-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500085', 8755, 1180, 'Nhan vien', 'QL034', 6, 'UserNV85')
 into NHANVIEN values('NV86', 'Đang Van Tuan', 'Nam', TO_DATE('2001-2-7','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500086', 5605, 1043, 'Nhan vien', 'QL035', 7, 'UserNV86')
 into NHANVIEN values('NV87', 'Duong Chi Han', 'Nam', TO_DATE('2007-3-17','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500087', 5681, 1203, 'Nhan vien', 'QL016', 8, 'UserNV87')
 into NHANVIEN values('NV88', 'Lai Hoang Viet', 'Nam', TO_DATE('2018-5-21','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500088', 4884, 1731, 'Nhan vien', 'QL017', 1, 'UserNV88')
 into NHANVIEN values('NV89', 'Tran Song Duy', 'Nu', TO_DATE('2012-10-24','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500089', 5727, 1511, 'Nhan vien', 'QL018', 2, 'UserNV89')
 into NHANVIEN values('NV90', 'Le Hoang Chi', 'Nam', TO_DATE('2013-10-22','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500090', 8762, 1934, 'Nhan vien', 'QL019', 3, 'UserNV90')
 into NHANVIEN values('NV91', 'Vo Van Nguyet', 'Nam', TO_DATE('2017-7-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500091', 8470, 1965, 'Nhan vien', 'QL020', 4, 'UserNV91')
 into NHANVIEN values('NV92', 'Lai Thi Anh', 'Nu', TO_DATE('2003-9-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500092', 1050, 1070, 'Nhan vien', 'QL021', 5, 'UserNV92')
 into NHANVIEN values('NV93', 'Au Tung Tan', 'Nam', TO_DATE('2004-2-23','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500093', 7843, 1764, 'Nhan vien', 'QL022', 6, 'UserNV93')
 into NHANVIEN values('NV94', 'Ly Hoang Nam', 'Nam', TO_DATE('2010-2-2','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500094', 1729, 1240, 'Nhan vien', 'QL023', 7, 'UserNV94')
 into NHANVIEN values('NV95', 'Duong Hoang Viet', 'Nam', TO_DATE('2001-3-26','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500095', 1516, 1896, 'Nhan vien', 'QL024', 8, 'UserNV95')
 into NHANVIEN values('NV96', 'Vo Song Ngoc Nhi', 'Nu', TO_DATE('2008-1-8','YYYY-MM-DD'), '227 Nguyễn Văn Cừ, Phường 4, Quận 5, TP. Hồ Chí Minh', '094500096', 7708, 1902, 'Nhan vien', 'QL025', 1, 'UserNV96')

In [9]:
KV = ['Quan 1', 'Quan 2', 'Quan 3','Quan 4','Quan 5','Quan 6','Quan 7','Quan 8','Quan 9','Quan 10','Quan 11','Quan 12','Quan 13', 'Quan Bình Thạnh', 'Quan Tân Bình', 'Hóoc Môn']

## Phong Ban

In [22]:
'''
PhongBan (
	MaPB 	number primary key,
	TenPB 	varchar2(60) not null,
	TrPHG 	varchar(10)
	
)	
'''


for i in range(1, 9):
    final = str(i) + ', ' + '\'Phong ' + str(i) + '\', NULL' 
    print('insert into PHONGBAN values(' +  final + ');')

insert into PHONGBAN values(1, 'Phong 1', NULL);
insert into PHONGBAN values(2, 'Phong 2', NULL);
insert into PHONGBAN values(3, 'Phong 3', NULL);
insert into PHONGBAN values(4, 'Phong 4', NULL);
insert into PHONGBAN values(5, 'Phong 5', NULL);
insert into PHONGBAN values(6, 'Phong 6', NULL);
insert into PHONGBAN values(7, 'Phong 7', NULL);
insert into PHONGBAN values(8, 'Phong 8', NULL);

In [55]:
for i in range(1, 9):
    print( ' UPDATE PHONGBAN set TrPHG = ' + '\'TP0'+ str(i+ 38) + '\'' + ' WHERE ' +  'MaPB = ' + str(i)+ ';')

 UPDATE PHONGBAN set TrPHG = 'TP039' WHERE MaPB = 1;
 UPDATE PHONGBAN set TrPHG = 'TP040' WHERE MaPB = 2;
 UPDATE PHONGBAN set TrPHG = 'TP041' WHERE MaPB = 3;
 UPDATE PHONGBAN set TrPHG = 'TP042' WHERE MaPB = 4;
 UPDATE PHONGBAN set TrPHG = 'TP043' WHERE MaPB = 5;
 UPDATE PHONGBAN set TrPHG = 'TP044' WHERE MaPB = 6;
 UPDATE PHONGBAN set TrPHG = 'TP045' WHERE MaPB = 7;
 UPDATE PHONGBAN set TrPHG = 'TP046' WHERE MaPB = 8;

# DE AN

In [48]:
'''
DeAn (
	MaDA 		varchar(10) primary key,
	TenDA 	varchar2(60) not null,
	NgayBD 	date,
	Phong 	number,
    TruongDeAn varchar(10)
	
)
'''
l = []
for i in range(1, 9):
    for j in range(1, rd.randint(3, 5)):
        MaDA = '\'DA' + str(i) + '0' + str(j) + '\'';
        l.append(MaDA);

        TenDA = '\'De An so ' + str(j) + ' Phong ' + str(i) + '\'';
        NgayBD  = 'TO_DATE(' + '\'' + str(rd.randint(2020, 2022)) + '-' + str(rd.randint(1, 12)) + '-' + str(rd.randint(1, 28)) + '\',\'YYYY-MM-DD\')'
        Phong = str(i)
        final = MaDA + ', ' + TenDA + ', ' + NgayBD + ', ' + Phong 
        print('into DEAN values(' +  final + ')')

into DEAN values('DA101', 'De An so 1 Phong 1', TO_DATE('2021-7-2','YYYY-MM-DD'), 1)
into DEAN values('DA102', 'De An so 2 Phong 1', TO_DATE('2022-6-3','YYYY-MM-DD'), 1)
into DEAN values('DA201', 'De An so 1 Phong 2', TO_DATE('2021-6-3','YYYY-MM-DD'), 2)
into DEAN values('DA202', 'De An so 2 Phong 2', TO_DATE('2022-12-25','YYYY-MM-DD'), 2)
into DEAN values('DA301', 'De An so 1 Phong 3', TO_DATE('2022-11-15','YYYY-MM-DD'), 3)
into DEAN values('DA302', 'De An so 2 Phong 3', TO_DATE('2022-7-4','YYYY-MM-DD'), 3)
into DEAN values('DA303', 'De An so 3 Phong 3', TO_DATE('2022-2-9','YYYY-MM-DD'), 3)
into DEAN values('DA401', 'De An so 1 Phong 4', TO_DATE('2021-9-22','YYYY-MM-DD'), 4)
into DEAN values('DA402', 'De An so 2 Phong 4', TO_DATE('2022-6-25','YYYY-MM-DD'), 4)
into DEAN values('DA403', 'De An so 3 Phong 4', TO_DATE('2022-2-20','YYYY-MM-DD'), 4)
into DEAN values('DA501', 'De An so 1 Phong 5', TO_DATE('2020-7-10','YYYY-MM-DD'), 5)
into DEAN values('DA502', 'De An so 2 Phong 5', TO_DATE('2021-7-11','YYYY-MM-DD'), 5)
into DEAN values('DA503', 'De An so 3 Phong 5', TO_DATE('2022-6-3','YYYY-MM-DD'), 5)
into DEAN values('DA504', 'De An so 4 Phong 5', TO_DATE('2022-9-12','YYYY-MM-DD'), 5)
into DEAN values('DA601', 'De An so 1 Phong 6', TO_DATE('2022-6-8','YYYY-MM-DD'), 6)
into DEAN values('DA602', 'De An so 2 Phong 6', TO_DATE('2020-5-9','YYYY-MM-DD'), 6)
into DEAN values('DA603', 'De An so 3 Phong 6', TO_DATE('2022-7-22','YYYY-MM-DD'), 6)
into DEAN values('DA604', 'De An so 4 Phong 6', TO_DATE('2022-11-8','YYYY-MM-DD'), 6)
into DEAN values('DA701', 'De An so 1 Phong 7', TO_DATE('2021-3-20','YYYY-MM-DD'), 7)
into DEAN values('DA702', 'De An so 2 Phong 7', TO_DATE('2022-8-14','YYYY-MM-DD'), 7)
into DEAN values('DA703', 'De An so 3 Phong 7', TO_DATE('2022-1-7','YYYY-MM-DD'), 7)
into DEAN values('DA704', 'De An so 4 Phong 7', TO_DATE('2022-7-23','YYYY-MM-DD'), 7)
into DEAN values('DA801', 'De An so 1 Phong 8', TO_DATE('2022-7-11','YYYY-MM-DD'), 8)
into DEAN values('DA802', 'De An so 2 Phong 8', TO_DATE('2021-7-8','YYYY-MM-DD'), 8)
into DEAN values('DA803', 'De An so 3 Phong 8', TO_DATE('2022-10-7','YYYY-MM-DD'), 8)

## Phan Cong

In [50]:
'''
	PhanCong (
	MaNV 		varchar(10) primary key,
	MaDA 		varchar(10) primary key,
	ThoiGian 	date
	
)

'''
import numpy as np
for i in range(47, 347, 3):
    MaNV = '\'NV'+ str(i) + '\''
    for j in range(1, rd.randint(2, 3)):
        MaDA = '\'DA' + str(i%8 + 1) + '0' + str(j) + '\'';
        TG  = 'TO_DATE(' + '\'' + str(rd.randint(2020, 2022)) + '-' + str(rd.randint(1, 12)) + '-' + str(rd.randint(1, 28)) + '\',\'YYYY-MM-DD\')'
        final = MaNV + ', ' + MaDA + ', ' + TG  
        print('into PHANCONG values(' +  final + ')')

into PHANCONG values('NV47', 'DA801', TO_DATE('2021-5-12','YYYY-MM-DD'))
into PHANCONG values('NV50', 'DA301', TO_DATE('2020-4-5','YYYY-MM-DD'))
into PHANCONG values('NV50', 'DA302', TO_DATE('2022-12-13','YYYY-MM-DD'))
into PHANCONG values('NV53', 'DA601', TO_DATE('2022-9-7','YYYY-MM-DD'))
into PHANCONG values('NV56', 'DA101', TO_DATE('2022-8-28','YYYY-MM-DD'))
into PHANCONG values('NV59', 'DA401', TO_DATE('2022-9-13','YYYY-MM-DD'))
into PHANCONG values('NV62', 'DA701', TO_DATE('2020-11-27','YYYY-MM-DD'))
into PHANCONG values('NV65', 'DA201', TO_DATE('2021-6-8','YYYY-MM-DD'))
into PHANCONG values('NV65', 'DA202', TO_DATE('2021-11-11','YYYY-MM-DD'))
into PHANCONG values('NV68', 'DA501', TO_DATE('2021-7-27','YYYY-MM-DD'))
into PHANCONG values('NV68', 'DA502', TO_DATE('2022-6-8','YYYY-MM-DD'))
into PHANCONG values('NV71', 'DA801', TO_DATE('2020-5-19','YYYY-MM-DD'))
into PHANCONG values('NV71', 'DA802', TO_DATE('2020-1-12','YYYY-MM-DD'))
into PHANCONG values('NV74', 'DA301', TO_DATE('2022-6-2','YYYY-MM-DD'))
into PHANCONG values('NV74', 'DA302', TO_DATE('2022-3-21','YYYY-MM-DD'))
into PHANCONG values('NV77', 'DA601', TO_DATE('2020-1-8','YYYY-MM-DD'))
into PHANCONG values('NV77', 'DA602', TO_DATE('2022-9-5','YYYY-MM-DD'))
into PHANCONG values('NV80', 'DA101', TO_DATE('2021-5-18','YYYY-MM-DD'))
into PHANCONG values('NV83', 'DA401', TO_DATE('2021-1-22','YYYY-MM-DD'))
into PHANCONG values('NV86', 'DA701', TO_DATE('2020-11-5','YYYY-MM-DD'))
into PHANCONG values('NV89', 'DA201', TO_DATE('2021-1-23','YYYY-MM-DD'))
into PHANCONG values('NV92', 'DA501', TO_DATE('2020-8-8','YYYY-MM-DD'))
into PHANCONG values('NV92', 'DA502', TO_DATE('2020-4-20','YYYY-MM-DD'))
into PHANCONG values('NV95', 'DA801', TO_DATE('2022-2-8','YYYY-MM-DD'))
into PHANCONG values('NV95', 'DA802', TO_DATE('2020-10-26','YYYY-MM-DD'))
into PHANCONG values('NV98', 'DA301', TO_DATE('2020-8-10','YYYY-MM-DD'))
into PHANCONG values('NV101', 'DA601', TO_DATE('2022-5-22','YYYY-MM-DD'))
into PHANCONG values('NV104', 'DA101', TO_DATE('2021-12-5','YYYY-MM-DD'))
into PHANCONG values('NV104', 'DA102', TO_DATE('2020-2-20','YYYY-MM-DD'))
into PHANCONG values('NV107', 'DA401', TO_DATE('2021-11-24','YYYY-MM-DD'))
into PHANCONG values('NV110', 'DA701', TO_DATE('2021-10-22','YYYY-MM-DD'))
into PHANCONG values('NV110', 'DA702', TO_DATE('2020-1-14','YYYY-MM-DD'))
into PHANCONG values('NV113', 'DA201', TO_DATE('2020-8-14','YYYY-MM-DD'))
into PHANCONG values('NV116', 'DA501', TO_DATE('2022-9-20','YYYY-MM-DD'))
into PHANCONG values('NV119', 'DA801', TO_DATE('2021-1-26','YYYY-MM-DD'))
into PHANCONG values('NV119', 'DA802', TO_DATE('2021-7-15','YYYY-MM-DD'))
into PHANCONG values('NV122', 'DA301', TO_DATE('2021-3-2','YYYY-MM-DD'))
into PHANCONG values('NV122', 'DA302', TO_DATE('2021-2-16','YYYY-MM-DD'))
into PHANCONG values('NV125', 'DA601', TO_DATE('2021-7-19','YYYY-MM-DD'))
into PHANCONG values('NV128', 'DA101', TO_DATE('2021-10-9','YYYY-MM-DD'))
into PHANCONG values('NV128', 'DA102', TO_DATE('2020-9-24','YYYY-MM-DD'))
into PHANCONG values('NV131', 'DA401', TO_DATE('2022-12-3','YYYY-MM-DD'))
into PHANCONG values('NV134', 'DA701', TO_DATE('2020-5-15','YYYY-MM-DD'))
into PHANCONG values('NV137', 'DA201', TO_DATE('2020-11-3','YYYY-MM-DD'))
into PHANCONG values('NV137', 'DA202', TO_DATE('2022-8-7','YYYY-MM-DD'))
into PHANCONG values('NV140', 'DA501', TO_DATE('2020-9-18','YYYY-MM-DD'))
into PHANCONG values('NV140', 'DA502', TO_DATE('2021-8-3','YYYY-MM-DD'))
into PHANCONG values('NV143', 'DA801', TO_DATE('2020-5-21','YYYY-MM-DD'))
into PHANCONG values('NV143', 'DA802', TO_DATE('2021-10-12','YYYY-MM-DD'))
into PHANCONG values('NV146', 'DA301', TO_DATE('2022-11-21','YYYY-MM-DD'))
into PHANCONG values('NV149', 'DA601', TO_DATE('2020-2-8','YYYY-MM-DD'))
into PHANCONG values('NV149', 'DA602', TO_DATE('2022-5-22','YYYY-MM-DD'))
into PHANCONG values('NV152', 'DA101', TO_DATE('2022-6-20','YYYY-MM-DD'))
into PHANCONG values('NV155', 'DA401', TO_DATE('2020-9-23','YYYY-MM-DD'))
into PHANCONG values('NV155', 'DA402', TO_DATE('2022-4-13','YYYY-MM-DD'))
into PHANCONG values('NV158', 'DA701', TO_DATE('2020-4-16','YYYY-MM-DD'))
into PHANCONG values('NV158', 'DA702', TO_DATE('2021-11-8','YYYY-MM-DD'))
into PHANCONG values('NV161', 'DA201', TO_DATE('2020-4-6','YYYY-MM-DD'))
into PHANCONG values('NV161', 'DA202', TO_DATE('2021-2-16','YYYY-MM-DD'))
into PHANCONG values('NV164', 'DA501', TO_DATE('2022-1-9','YYYY-MM-DD'))
into PHANCONG values('NV167', 'DA801', TO_DATE('2021-2-20','YYYY-MM-DD'))
into PHANCONG values('NV167', 'DA802', TO_DATE('2022-12-16','YYYY-MM-DD'))
into PHANCONG values('NV170', 'DA301', TO_DATE('2021-1-22','YYYY-MM-DD'))
into PHANCONG values('NV170', 'DA302', TO_DATE('2022-4-27','YYYY-MM-DD'))
into PHANCONG values('NV173', 'DA601', TO_DATE('2020-8-27','YYYY-MM-DD'))
into PHANCONG values('NV176', 'DA101', TO_DATE('2020-2-12','YYYY-MM-DD'))
into PHANCONG values('NV176', 'DA102', TO_DATE('2022-7-12','YYYY-MM-DD'))
into PHANCONG values('NV179', 'DA401', TO_DATE('2020-3-11','YYYY-MM-DD'))
into PHANCONG values('NV182', 'DA701', TO_DATE('2022-4-21','YYYY-MM-DD'))
into PHANCONG values('NV185', 'DA201', TO_DATE('2021-10-25','YYYY-MM-DD'))
into PHANCONG values('NV185', 'DA202', TO_DATE('2022-5-12','YYYY-MM-DD'))
into PHANCONG values('NV188', 'DA501', TO_DATE('2022-6-22','YYYY-MM-DD'))
into PHANCONG values('NV188', 'DA502', TO_DATE('2020-1-21','YYYY-MM-DD'))
into PHANCONG values('NV191', 'DA801', TO_DATE('2020-1-6','YYYY-MM-DD'))
into PHANCONG values('NV191', 'DA802', TO_DATE('2022-7-24','YYYY-MM-DD'))
into PHANCONG values('NV194', 'DA301', TO_DATE('2020-3-23','YYYY-MM-DD'))
into PHANCONG values('NV197', 'DA601', TO_DATE('2020-9-5','YYYY-MM-DD'))
into PHANCONG values('NV197', 'DA602', TO_DATE('2020-12-6','YYYY-MM-DD'))
into PHANCONG values('NV200', 'DA101', TO_DATE('2022-9-21','YYYY-MM-DD'))
into PHANCONG values('NV200', 'DA102', TO_DATE('2020-9-17','YYYY-MM-DD'))
into PHANCONG values('NV203', 'DA401', TO_DATE('2022-8-26','YYYY-MM-DD'))
into PHANCONG values('NV203', 'DA402', TO_DATE('2020-3-5','YYYY-MM-DD'))
into PHANCONG values('NV206', 'DA701', TO_DATE('2020-12-26','YYYY-MM-DD'))
into PHANCONG values('NV209', 'DA201', TO_DATE('2020-9-10','YYYY-MM-DD'))
into PHANCONG values('NV212', 'DA501', TO_DATE('2022-1-1','YYYY-MM-DD'))
into PHANCONG values('NV215', 'DA801', TO_DATE('2020-7-9','YYYY-MM-DD'))
into PHANCONG values('NV215', 'DA802', TO_DATE('2022-8-13','YYYY-MM-DD'))
into PHANCONG values('NV218', 'DA301', TO_DATE('2020-12-4','YYYY-MM-DD'))
into PHANCONG values('NV218', 'DA302', TO_DATE('2022-5-27','YYYY-MM-DD'))
into PHANCONG values('NV221', 'DA601', TO_DATE('2021-7-13','YYYY-MM-DD'))
into PHANCONG values('NV224', 'DA101', TO_DATE('2022-2-17','YYYY-MM-DD'))
into PHANCONG values('NV224', 'DA102', TO_DATE('2020-3-5','YYYY-MM-DD'))
into PHANCONG values('NV227', 'DA401', TO_DATE('2021-1-10','YYYY-MM-DD'))
into PHANCONG values('NV230', 'DA701', TO_DATE('2021-10-10','YYYY-MM-DD'))
into PHANCONG values('NV233', 'DA201', TO_DATE('2020-2-28','YYYY-MM-DD'))
into PHANCONG values('NV233', 'DA202', TO_DATE('2021-11-11','YYYY-MM-DD'))
into PHANCONG values('NV236', 'DA501', TO_DATE('2021-9-10','YYYY-MM-DD'))
into PHANCONG values('NV239', 'DA801', TO_DATE('2021-12-26','YYYY-MM-DD'))
into PHANCONG values('NV239', 'DA802', TO_DATE('2021-8-18','YYYY-MM-DD'))
into PHANCONG values('NV242', 'DA301', TO_DATE('2020-2-18','YYYY-MM-DD'))
into PHANCONG values('NV242', 'DA302', TO_DATE('2020-5-8','YYYY-MM-DD'))
into PHANCONG values('NV245', 'DA601', TO_DATE('2022-6-10','YYYY-MM-DD'))
into PHANCONG values('NV248', 'DA101', TO_DATE('2021-4-24','YYYY-MM-DD'))
into PHANCONG values('NV248', 'DA102', TO_DATE('2021-12-8','YYYY-MM-DD'))
into PHANCONG values('NV251', 'DA401', TO_DATE('2022-6-28','YYYY-MM-DD'))
into PHANCONG values('NV254', 'DA701', TO_DATE('2021-6-26','YYYY-MM-DD'))
into PHANCONG values('NV254', 'DA702', TO_DATE('2020-1-22','YYYY-MM-DD'))
into PHANCONG values('NV257', 'DA201', TO_DATE('2020-6-15','YYYY-MM-DD'))
into PHANCONG values('NV257', 'DA202', TO_DATE('2020-5-26','YYYY-MM-DD'))
into PHANCONG values('NV260', 'DA501', TO_DATE('2020-7-19','YYYY-MM-DD'))
into PHANCONG values('NV263', 'DA801', TO_DATE('2022-5-13','YYYY-MM-DD'))
into PHANCONG values('NV266', 'DA301', TO_DATE('2021-1-15','YYYY-MM-DD'))
into PHANCONG values('NV266', 'DA302', TO_DATE('2022-10-19','YYYY-MM-DD'))
into PHANCONG values('NV269', 'DA601', TO_DATE('2021-6-2','YYYY-MM-DD'))
into PHANCONG values('NV269', 'DA602', TO_DATE('2021-2-28','YYYY-MM-DD'))
into PHANCONG values('NV272', 'DA101', TO_DATE('2021-12-10','YYYY-MM-DD'))
into PHANCONG values('NV275', 'DA401', TO_DATE('2020-10-19','YYYY-MM-DD'))
into PHANCONG values('NV275', 'DA402', TO_DATE('2021-2-4','YYYY-MM-DD'))
into PHANCONG values('NV278', 'DA701', TO_DATE('2022-12-3','YYYY-MM-DD'))
into PHANCONG values('NV281', 'DA201', TO_DATE('2022-7-11','YYYY-MM-DD'))
into PHANCONG values('NV284', 'DA501', TO_DATE('2022-6-25','YYYY-MM-DD'))
into PHANCONG values('NV287', 'DA801', TO_DATE('2021-11-25','YYYY-MM-DD'))
into PHANCONG values('NV287', 'DA802', TO_DATE('2022-11-28','YYYY-MM-DD'))
into PHANCONG values('NV290', 'DA301', TO_DATE('2022-11-14','YYYY-MM-DD'))
into PHANCONG values('NV290', 'DA302', TO_DATE('2020-11-17','YYYY-MM-DD'))
into PHANCONG values('NV293', 'DA601', TO_DATE('2022-8-26','YYYY-MM-DD'))
into PHANCONG values('NV296', 'DA101', TO_DATE('2020-2-3','YYYY-MM-DD'))
into PHANCONG values('NV299', 'DA401', TO_DATE('2022-3-28','YYYY-MM-DD'))
into PHANCONG values('NV302', 'DA701', TO_DATE('2021-7-1','YYYY-MM-DD'))
into PHANCONG values('NV302', 'DA702', TO_DATE('2022-6-23','YYYY-MM-DD'))
into PHANCONG values('NV305', 'DA201', TO_DATE('2020-4-26','YYYY-MM-DD'))
into PHANCONG values('NV308', 'DA501', TO_DATE('2022-12-25','YYYY-MM-DD'))
into PHANCONG values('NV311', 'DA801', TO_DATE('2020-4-26','YYYY-MM-DD'))
into PHANCONG values('NV314', 'DA301', TO_DATE('2022-12-13','YYYY-MM-DD'))
into PHANCONG values('NV317', 'DA601', TO_DATE('2020-2-8','YYYY-MM-DD'))
into PHANCONG values('NV320', 'DA101', TO_DATE('2021-4-14','YYYY-MM-DD'))
into PHANCONG values('NV320', 'DA102', TO_DATE('2021-3-25','YYYY-MM-DD'))
into PHANCONG values('NV323', 'DA401', TO_DATE('2020-5-11','YYYY-MM-DD'))
into PHANCONG values('NV326', 'DA701', TO_DATE('2020-6-9','YYYY-MM-DD'))
into PHANCONG values('NV329', 'DA201', TO_DATE('2021-9-20','YYYY-MM-DD'))
into PHANCONG values('NV332', 'DA501', TO_DATE('2021-12-20','YYYY-MM-DD'))
into PHANCONG values('NV332', 'DA502', TO_DATE('2022-8-20','YYYY-MM-DD'))
into PHANCONG values('NV335', 'DA801', TO_DATE('2022-7-4','YYYY-MM-DD'))
into PHANCONG values('NV338', 'DA301', TO_DATE('2020-4-15','YYYY-MM-DD'))
into PHANCONG values('NV341', 'DA601', TO_DATE('2022-10-26','YYYY-MM-DD'))
into PHANCONG values('NV341', 'DA602', TO_DATE('2020-9-12','YYYY-MM-DD'))
into PHANCONG values('NV344', 'DA101', TO_DATE('2022-10-27','YYYY-MM-DD'))
into PHANCONG values('NV344', 'DA102', TO_DATE('2022-9-24','YYYY-MM-DD'))

# Tai khoan

In [ ]:
'''
tai khoan:
    username varchar(50),
    password varchar(150),
    MaNV varchar(10)
'''